#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::items_after_statements,
    clippy::match_wildcard_for_single_variants,
    clippy::missing_panics_doc,
    clippy::needless_pass_by_value,
    clippy::used_underscore_binding,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::unreadable_literal
)]

//! Full multipart upload flow — the previously uncovered end-to-end path:
//! POST a real image to `/api/upload/{slug}`, assert the created document
//! carries the server-derived metadata AND the synchronously generated
//! image-size variant, and fetch the stored files back through the serve
//! route.

use axum::body::Body;
use axum::http::{Request, StatusCode};
use crap_cms::core::collection::CollectionDefinition;
use crap_cms::core::field::{FieldDefinition, FieldType};
use crap_cms::core::upload::{CollectionUpload, ImageSizeBuilder};
use serde_json::Value;
use tower::ServiceExt;

use crap_cms_e2e::helpers::*;

/// 4×4 opaque red RGBA PNG, generated byte-for-byte (no decoder risk).
const TINY_PNG: &[u8] = &[
    137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4, 8, 6, 0,
    0, 0, 169, 241, 158, 126, 0, 0, 0, 18, 73, 68, 65, 84, 120, 156, 99, 248, 207, 192, 240, 31,
    25, 51, 144, 46, 0, 0, 60, 64, 31, 225, 224, 129, 119, 180, 0, 0, 0, 0, 73, 69, 78, 68, 174,
    66, 96, 130,
];

fn make_media_def() -> CollectionDefinition {
    let mut def = CollectionDefinition::new("media");
    def.timestamps = true;
    def.fields = vec![
        FieldDefinition::builder("filename", FieldType::Text)
            .required(true)
            .build(),
        FieldDefinition::builder("url", FieldType::Text).build(),
        FieldDefinition::builder("width", FieldType::Number).build(),
        FieldDefinition::builder("height", FieldType::Number).build(),
        FieldDefinition::builder("filesize", FieldType::Number).build(),
        // Size-variant fields: the Lua parse path auto-injects these
        // (`inject_upload_fields`); a Rust-built def declares them itself.
        FieldDefinition::builder("thumbnail_url", FieldType::Text).build(),
        FieldDefinition::builder("thumbnail_width", FieldType::Number).build(),
        FieldDefinition::builder("thumbnail_height", FieldType::Number).build(),
        FieldDefinition::builder("caption", FieldType::Text).build(),
    ];

    let mut upload = CollectionUpload::new();
    upload.image_sizes = vec![
        ImageSizeBuilder::new("thumbnail")
            .width(8)
            .height(8)
            .build(),
    ];
    def.upload = Some(upload);
    def
}

/// Build a multipart/form-data body with a `caption` field and the image
/// under the `_file` field name the upload handler expects.
fn multipart_body(boundary: &str, png: &[u8]) -> Vec<u8> {
    let mut body = Vec::new();
    body.extend_from_slice(
        format!(
            "--{boundary}\r\nContent-Disposition: form-data; name=\"caption\"\r\n\r\nhello upload\r\n"
        )
        .as_bytes(),
    );
    body.extend_from_slice(
        format!(
            "--{boundary}\r\nContent-Disposition: form-data; name=\"_file\"; filename=\"tiny.png\"\r\nContent-Type: image/png\r\n\r\n"
        )
        .as_bytes(),
    );
    body.extend_from_slice(png);
    body.extend_from_slice(format!("\r\n--{boundary}--\r\n").as_bytes());
    body
}

#[tokio::test]
async fn multipart_upload_creates_document_with_metadata_and_thumbnail() {
    let ctx = setup_html_test(
        vec![make_users_def(), make_media_def()],
        vec![],
        "uploader@test.com",
        "pass123",
    );

    // The upload API authenticates via Bearer — reuse the session JWT
    // minted into the cookie ("crap_session=<jwt>").
    let token = ctx
        .cookie
        .strip_prefix("crap_session=")
        .expect("session cookie")
        .to_string();

    let boundary = "X-CRAP-TEST-BOUNDARY";
    let body = multipart_body(boundary, TINY_PNG);

    let resp = ctx
        .app
        .router
        .clone()
        .oneshot(
            Request::post("/api/upload/media")
                .header("Authorization", format!("Bearer {token}"))
                .header(
                    "Content-Type",
                    format!("multipart/form-data; boundary={boundary}"),
                )
                .body(Body::from(body))
                .unwrap(),
        )
        .await
        .unwrap();

    let status = resp.status();
    let body = body_string(resp.into_body()).await;
    assert!(
        status.is_success(),
        "upload must succeed, got {status}: {body}"
    );

    let doc: Value = serde_json::from_str(&body).expect("json response");
    let fields = doc
        .get("document")
        .unwrap_or_else(|| panic!("response wraps the created document: {body}"));

    // Server-derived metadata.
    assert_eq!(
        fields.get("caption").and_then(Value::as_str),
        Some("hello upload"),
        "form field must persist: {body}"
    );
    let filename = fields
        .get("filename")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("filename must be set: {body}"))
        .to_string();
    assert_eq!(fields.get("width").and_then(Value::as_i64), Some(4));
    assert_eq!(fields.get("height").and_then(Value::as_i64), Some(4));
    assert!(
        fields.get("filesize").and_then(Value::as_i64).unwrap_or(0) > 0,
        "filesize must be positive: {body}"
    );

    // The synchronously generated size variant.
    let thumb_name = fields
        .get("thumbnail_url")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("thumbnail_url must be set: {body}"))
        .rsplit('/')
        .next()
        .unwrap()
        .to_string();
    assert_eq!(
        fields.get("thumbnail_width").and_then(Value::as_i64),
        Some(8),
        "thumbnail resized to configured width: {body}"
    );
    assert_eq!(
        fields.get("thumbnail_height").and_then(Value::as_i64),
        Some(8)
    );

    // Both stored files must be retrievable through the serve route.
    for name in [filename, thumb_name] {
        let resp = ctx
            .app
            .router
            .clone()
            .oneshot(
                Request::get(format!("/uploads/media/{name}"))
                    .header("Cookie", auth_and_csrf(&ctx.cookie))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(
            resp.status(),
            StatusCode::OK,
            "stored file `{name}` must be served"
        );
    }
}
