#![allow(
    clippy::cast_possible_truncation,
    clippy::cast_possible_wrap,
    clippy::cast_sign_loss,
    clippy::items_after_statements,
    clippy::match_wildcard_for_single_variants,
    clippy::missing_panics_doc,
    clippy::needless_pass_by_value,
    clippy::used_underscore_binding,
    clippy::similar_names,
    clippy::too_many_lines,
    clippy::unreadable_literal
)]

//! Full multipart upload flow — the previously uncovered end-to-end path:
//! POST a real image to `/api/upload/{slug}`, assert the created document
//! carries the server-derived metadata AND the synchronously generated
//! image-size variant, and fetch the stored files back through the serve
//! route.

use std::{iter::repeat_n, net::SocketAddr};

use axum::{
    body::Body,
    extract::ConnectInfo,
    http::{Request, StatusCode},
};
use serde_json::Value;
use tower::ServiceExt;

use crap_cms::{
    config::CrapConfig,
    core::{
        collection::CollectionDefinition,
        field::{FieldDefinition, FieldType},
        upload::{CollectionUpload, ImageSizeBuilder},
    },
};

use crap_cms_e2e::helpers::*;

/// 4×4 opaque red RGBA PNG, generated byte-for-byte (no decoder risk).
const TINY_PNG: &[u8] = &[
    137, 80, 78, 71, 13, 10, 26, 10, 0, 0, 0, 13, 73, 72, 68, 82, 0, 0, 0, 4, 0, 0, 0, 4, 8, 6, 0,
    0, 0, 169, 241, 158, 126, 0, 0, 0, 18, 73, 68, 65, 84, 120, 156, 99, 248, 207, 192, 240, 31,
    25, 51, 144, 46, 0, 0, 60, 64, 31, 225, 224, 129, 119, 180, 0, 0, 0, 0, 73, 69, 78, 68, 174,
    66, 96, 130,
];

fn make_media_def() -> CollectionDefinition {
    let mut def = CollectionDefinition::new("media");
    def.timestamps = true;
    def.fields = vec![
        FieldDefinition::builder("filename", FieldType::Text)
            .required(true)
            .build(),
        FieldDefinition::builder("url", FieldType::Text).build(),
        FieldDefinition::builder("width", FieldType::Number).build(),
        FieldDefinition::builder("height", FieldType::Number).build(),
        FieldDefinition::builder("filesize", FieldType::Number).build(),
        // Size-variant fields: the Lua parse path auto-injects these
        // (`inject_upload_fields`); a Rust-built def declares them itself.
        FieldDefinition::builder("thumbnail_url", FieldType::Text).build(),
        FieldDefinition::builder("thumbnail_width", FieldType::Number).build(),
        FieldDefinition::builder("thumbnail_height", FieldType::Number).build(),
        FieldDefinition::builder("caption", FieldType::Text).build(),
    ];

    let mut upload = CollectionUpload::new();
    upload.image_sizes = vec![
        ImageSizeBuilder::new("thumbnail")
            .width(8)
            .height(8)
            .build(),
    ];
    def.upload = Some(upload);
    def
}

/// Build a multipart/form-data body with a `caption` field and the image
/// under the `_file` field name the upload handler expects.
fn multipart_body(boundary: &str, png: &[u8]) -> Vec<u8> {
    let mut body = Vec::new();
    body.extend_from_slice(
        format!(
            "--{boundary}\r\nContent-Disposition: form-data; name=\"caption\"\r\n\r\nhello upload\r\n"
        )
        .as_bytes(),
    );
    body.extend_from_slice(
        format!(
            "--{boundary}\r\nContent-Disposition: form-data; name=\"_file\"; filename=\"tiny.png\"\r\nContent-Type: image/png\r\n\r\n"
        )
        .as_bytes(),
    );
    body.extend_from_slice(png);
    body.extend_from_slice(format!("\r\n--{boundary}--\r\n").as_bytes());
    body
}

#[tokio::test]
async fn multipart_upload_creates_document_with_metadata_and_thumbnail() {
    let ctx = setup_html_test(
        vec![make_users_def(), make_media_def()],
        vec![],
        "uploader@test.com",
        "pass123",
    );

    // The upload API authenticates via Bearer — reuse the session JWT
    // minted into the cookie ("crap_session=<jwt>").
    let token = ctx
        .cookie
        .strip_prefix("crap_session=")
        .expect("session cookie")
        .to_string();

    let boundary = "X-CRAP-TEST-BOUNDARY";
    let body = multipart_body(boundary, TINY_PNG);

    let resp = ctx
        .app
        .router
        .clone()
        .oneshot(
            Request::post("/api/upload/media")
                .header("Authorization", format!("Bearer {token}"))
                .header(
                    "Content-Type",
                    format!("multipart/form-data; boundary={boundary}"),
                )
                .body(Body::from(body))
                .unwrap(),
        )
        .await
        .unwrap();

    let status = resp.status();
    let body = body_string(resp.into_body()).await;
    assert!(
        status.is_success(),
        "upload must succeed, got {status}: {body}"
    );

    let doc: Value = serde_json::from_str(&body).expect("json response");
    let fields = doc
        .get("document")
        .unwrap_or_else(|| panic!("response wraps the created document: {body}"));

    // Server-derived metadata.
    assert_eq!(
        fields.get("caption").and_then(Value::as_str),
        Some("hello upload"),
        "form field must persist: {body}"
    );
    let filename = fields
        .get("filename")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("filename must be set: {body}"))
        .to_string();
    assert_eq!(fields.get("width").and_then(Value::as_i64), Some(4));
    assert_eq!(fields.get("height").and_then(Value::as_i64), Some(4));
    assert!(
        fields.get("filesize").and_then(Value::as_i64).unwrap_or(0) > 0,
        "filesize must be positive: {body}"
    );

    // The synchronously generated size variant, in the shape a read returns:
    // the per-size columns folded into `sizes`, not flat `thumbnail_*` keys.
    let thumb = fields
        .get("sizes")
        .and_then(|sizes| sizes.get("thumbnail"))
        .unwrap_or_else(|| panic!("sizes.thumbnail must be set: {body}"));
    assert!(
        fields.get("thumbnail_url").is_none(),
        "per-size columns are folded into `sizes`: {body}"
    );
    let thumb_name = thumb
        .get("url")
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("sizes.thumbnail.url must be set: {body}"))
        .rsplit('/')
        .next()
        .unwrap()
        .to_string();
    assert_eq!(
        thumb.get("width").and_then(Value::as_i64),
        Some(8),
        "thumbnail resized to configured width: {body}"
    );
    assert_eq!(thumb.get("height").and_then(Value::as_i64), Some(8));

    // Both stored files must be retrievable through the serve route.
    for name in [filename, thumb_name] {
        let resp = ctx
            .app
            .router
            .clone()
            .oneshot(
                Request::get(format!("/uploads/media/{name}"))
                    .header("Cookie", auth_and_csrf(&ctx.cookie))
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(
            resp.status(),
            StatusCode::OK,
            "stored file `{name}` must be served"
        );
    }
}

/// Regression: an admin upload over the body limit answered a plain 303
/// redirect. htmx followed it and swapped a blank form into the page, so the
/// user's edits vanished without a word. The refusal must be an error status
/// (htmx swaps nothing) carrying a toast that names the limit.
#[tokio::test]
async fn admin_upload_over_the_body_limit_answers_413_with_a_toast() {
    let mut config = CrapConfig::test_default();
    config.database.path = "test.db".to_string();
    config.auth.secret = "test-jwt-secret".into();
    config.upload.max_file_size = 1024;

    let ctx = setup_html_test_with_config(
        vec![make_users_def(), make_media_def()],
        vec![],
        config,
        "uploader@test.com",
        "pass123",
    );

    // Past the body limit (upload maximum + 1 MiB headroom).
    let boundary = "X-CRAP-TEST-BOUNDARY";
    let oversized: Vec<u8> = repeat_n(0_u8, 2 * 1024 * 1024 + 4096).collect();
    let body = multipart_body(boundary, &oversized);

    let resp = ctx
        .app
        .router
        .clone()
        .oneshot(
            Request::post("/admin/collections/media")
                .header("Cookie", auth_and_csrf(&ctx.cookie))
                .header("X-CSRF-Token", TEST_CSRF)
                .header("HX-Request", "true")
                .header(
                    "Content-Type",
                    format!("multipart/form-data; boundary={boundary}"),
                )
                .body(Body::from(body))
                .unwrap(),
        )
        .await
        .unwrap();

    assert_eq!(resp.status(), StatusCode::PAYLOAD_TOO_LARGE);
    assert!(resp.headers().get("location").is_none(), "no redirect");
    assert!(resp.headers().get("hx-redirect").is_none(), "no redirect");

    let toast = resp
        .headers()
        .get("X-Crap-Toast")
        .expect("an error toast")
        .to_str()
        .unwrap()
        .to_string();
    assert!(
        toast.contains("1.0 KB"),
        "the toast names the limit: {toast}"
    );
}

const MIB: usize = 1024 * 1024;

/// A multipart body carrying `data` as a generic binary `_file`.
fn multipart_binary_body(boundary: &str, data: &[u8]) -> Vec<u8> {
    let mut body = Vec::new();
    body.extend_from_slice(
        format!(
            "--{boundary}\r\nContent-Disposition: form-data; name=\"_file\"; filename=\"big.bin\"\r\nContent-Type: application/octet-stream\r\n\r\n"
        )
        .as_bytes(),
    );
    body.extend_from_slice(data);
    body.extend_from_slice(format!("\r\n--{boundary}--\r\n").as_bytes());
    body
}

/// A config whose global upload maximum is tiny, next to a `media`
/// collection that allows 4 MiB files of its own.
fn big_collection_limit_ctx() -> HtmlTestCtx {
    let mut config = CrapConfig::test_default();
    config.database.path = "test.db".to_string();
    config.auth.secret = "test-jwt-secret".into();
    config.upload.max_file_size = 1024;

    let mut media = make_media_def();
    if let Some(upload) = media.upload.as_mut() {
        upload.image_sizes.clear();
        upload.max_file_size = Some(u64::try_from(4 * MIB).unwrap());
    }

    setup_html_test_with_config(
        vec![make_users_def(), media],
        vec![],
        config,
        "uploader@test.com",
        "pass123",
    )
}

/// A collection allowing larger files than the global maximum accepts them
/// on its admin create route and on the upload API — the body limit there
/// follows the collection, not the global default.
#[tokio::test]
async fn a_collection_limit_above_the_global_admits_larger_uploads() {
    let ctx = big_collection_limit_ctx();
    let boundary = "X-CRAP-TEST-BOUNDARY";
    let file: Vec<u8> = repeat_n(7_u8, 2 * MIB).collect();

    let admin = ctx
        .app
        .router
        .clone()
        .oneshot(
            Request::post("/admin/collections/media")
                .header("Cookie", auth_and_csrf(&ctx.cookie))
                .header("X-CSRF-Token", TEST_CSRF)
                .header(
                    "Content-Type",
                    format!("multipart/form-data; boundary={boundary}"),
                )
                .body(Body::from(multipart_binary_body(boundary, &file)))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_ne!(admin.status(), StatusCode::PAYLOAD_TOO_LARGE);

    let token = ctx
        .cookie
        .strip_prefix("crap_session=")
        .expect("session cookie")
        .to_string();

    let api = ctx
        .app
        .router
        .clone()
        .oneshot(
            Request::post("/api/upload/media")
                .header("Authorization", format!("Bearer {token}"))
                .header(
                    "Content-Type",
                    format!("multipart/form-data; boundary={boundary}"),
                )
                .body(Body::from(multipart_binary_body(boundary, &file)))
                .unwrap(),
        )
        .await
        .unwrap();
    let status = api.status();
    let body = body_string(api.into_body()).await;
    assert!(
        status.is_success(),
        "upload API refused it: {status} {body}"
    );
}

/// Regression: the largest collection upload limit was applied to the whole
/// router, so every route — the unauthenticated login form included —
/// buffered bodies up to that size. Routes that take no upload keep the
/// global limit.
#[tokio::test]
async fn routes_without_uploads_keep_the_global_body_limit() {
    let ctx = big_collection_limit_ctx();

    // Past the global limit (1 KiB + 1 MiB headroom), well inside the
    // collection's 4 MiB.
    let form = format!("email=a%40b.c&password={}", "x".repeat(2 * MIB));

    let login = ctx
        .app
        .router
        .clone()
        .oneshot(
            Request::post("/admin/login")
                .header("content-type", "application/x-www-form-urlencoded")
                .header("Cookie", format!("crap_csrf={TEST_CSRF}"))
                .header("X-CSRF-Token", TEST_CSRF)
                .extension(ConnectInfo(SocketAddr::from(([127, 0, 0, 1], 0))))
                .body(Body::from(form))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(login.status(), StatusCode::PAYLOAD_TOO_LARGE);

    let json = format!(r#"{{"caption":"{}"}}"#, "x".repeat(2 * MIB));

    let validate = ctx
        .app
        .router
        .clone()
        .oneshot(
            Request::post("/admin/collections/media/validate")
                .header("Cookie", auth_and_csrf(&ctx.cookie))
                .header("X-CSRF-Token", TEST_CSRF)
                .header("Content-Type", "application/json")
                .body(Body::from(json))
                .unwrap(),
        )
        .await
        .unwrap();
    assert_eq!(validate.status(), StatusCode::PAYLOAD_TOO_LARGE);
}
