//! Collection document unpublish.

use serde_json::Value;

use crate::{
    core::{Document, event::EventOperation},
    db::{AccessResult, LocaleContext, query},
    hooks::{AccessCheckInput, HookContext, HookEvent},
    service::{
        AfterChangeInput, ServiceContext, ServiceError, helpers, invalidate_user_streams_if_auth,
        persist_unpublish, run_after_change_hooks, run_pool_write,
    },
};

type Result<T> = std::result::Result<T, ServiceError>;

/// Unpublish a versioned document on an existing connection/transaction.
///
/// Runs the full lifecycle: access check -> before-hooks -> set draft status ->
/// hydrate -> after-hooks -> strip read-denied fields.
/// Does NOT manage transactions — caller must open/commit.
fn unpublish_document_in_conn(ctx: &ServiceContext, id: &str) -> Result<Document> {
    let conn = ctx.resolve_conn()?;
    let conn = conn.as_ref();
    let write_hooks = ctx.write_hooks()?;
    let def = ctx.collection_def()?;

    // Authoritative capability gate: unpublish sets `_status='draft'` and writes a
    // version snapshot, both of which require versioning. Enforced here at the one
    // service chokepoint so no surface (gRPC previously reached this ungated) can
    // unpublish a non-versioned collection.
    if !def.has_versions() {
        return Err(ServiceError::HookError(format!(
            "Collection '{}' does not support unpublish: versioning is not enabled",
            ctx.slug
        )));
    }

    let access = write_hooks.check_access(
        &AccessCheckInput::builder("unpublish", ctx.slug)
            .access(def.access.update.as_ref())
            .user(ctx.user)
            .id(Some(id))
            .build(),
    )?;

    if matches!(access, AccessResult::Denied) {
        return Err(ServiceError::AccessDenied("Update access denied".into()));
    }

    // When the hook returned Constrained filters, enforce row-level match.
    helpers::enforce_access_constraints(ctx, id, &access, "Update", false)?;

    // Build a default `LocaleContext` from the attached locale config so the
    // raw read picks up locale-suffixed columns (`title__en`, `title__de`)
    // for localized fields. Without this, the SELECT generated by
    // `find_by_id_raw` references bare `title` and SQLite errors with
    // `no such column: title` on collections that have any localized field.
    let locale_ctx = ctx.default_locale_ctx();

    let doc = query::find_by_id_raw(conn, ctx.slug, def, id, locale_ctx.as_ref(), false)?
        .ok_or_else(|| {
            ServiceError::NotFound(format!("Document '{id}' not found in '{}'", ctx.slug))
        })?;

    let hook_ctx = HookContext::builder(ctx.slug, "update")
        .data(doc.fields.clone())
        .document_id(id)
        .draft(true)
        .locale(locale_ctx.as_ref().map(LocaleContext::access_locale))
        .user(ctx.user)
        .build();

    let final_ctx =
        write_hooks.run_hooks_with_conn(&def.hooks, HookEvent::BeforeChange, hook_ctx, conn)?;

    persist_unpublish(ctx, id)?;

    let mut doc = doc;
    doc.fields
        .insert("_status".to_string(), Value::String("draft".into()));

    // Hydrate join fields BEFORE after-change hooks so they see nested data.
    query::hydrate_document(conn, ctx.slug, &def.fields, &mut doc, None, None)?;

    run_after_change_hooks(
        write_hooks,
        &def.hooks,
        &def.fields,
        &doc,
        AfterChangeInput::builder(ctx.slug, "update")
            .draft(true)
            .locale(locale_ctx.as_ref().map(|lc| lc.access_locale().to_string()))
            .req_context(final_ctx.context)
            .user(ctx.user)
            .build(),
        conn,
    )?;

    write_hooks.strip_read_access_doc(&def.fields, &mut doc, ctx.slug, ctx.user, None);
    doc.strip_fields(&helpers::collect_api_hidden_field_names(&def.fields, ""));

    Ok(doc)
}

/// Unpublish a versioned document.
///
/// **Pool mode** (`ctx.pool` set): opens a transaction, commits after success.
/// **Conn mode** (`ctx.conn` set, Lua CRUD path): runs on the existing connection.
///
/// # Errors
///
/// Returns service-layer errors (access denied, document not found, hook
/// errors) or a backend error if the DB transaction or persistence fails.
#[cfg(not(tarpaulin_include))]
pub fn unpublish_document(ctx: &ServiceContext, id: &str) -> Result<Document> {
    if ctx.pool.is_some() {
        unpublish_document_pool(ctx, id)
    } else {
        unpublish_document_conn(ctx, id)
    }
}

fn unpublish_document_pool(ctx: &ServiceContext, id: &str) -> Result<Document> {
    run_pool_write(
        ctx,
        None,
        |inner| unpublish_document_in_conn(inner, id),
        |ctx, doc| {
            ctx.publish_mutation_event(EventOperation::Update, &doc.id, &doc.fields);
            invalidate_user_streams_if_auth(ctx, &doc.id);
        },
    )
}

fn unpublish_document_conn(ctx: &ServiceContext, id: &str) -> Result<Document> {
    let doc = unpublish_document_in_conn(ctx, id)?;

    ctx.clear_cache();

    ctx.publish_mutation_event(EventOperation::Update, &doc.id, &doc.fields);
    invalidate_user_streams_if_auth(ctx, &doc.id);

    Ok(doc)
}
