//! Collection document unpublish.

use crate::{
    core::{Document, EventViewPlacement, event::EventOperation},
    db::{AccessResult, query},
    hooks::AccessCheckInput,
    service::{
        Gated, ServiceContext, ServiceError, StateChange, helpers, invalidate_user_streams_if_auth,
        persist_unpublish, require_unpublish_capability, run_after_change_hooks, run_pool_write,
        run_state_before_change,
        write::{UploadSettle, document_file_keys, settle_upload_write},
    },
};

type Result<T> = std::result::Result<T, ServiceError>;

/// Unpublish a versioned document on an existing connection/transaction.
///
/// Runs the full lifecycle: access check -> before-hooks -> set draft status ->
/// hydrate -> after-hooks -> strip read-denied fields. Returns the stored row
/// the unpublish event is built from alongside the document.
/// Does NOT manage transactions — caller must open/commit.
fn unpublish_document_in_conn(ctx: &ServiceContext, id: &str) -> Result<Gated<Document>> {
    let conn = ctx.resolve_conn()?;
    let conn = conn.as_ref();
    let write_hooks = ctx.write_hooks()?;
    let def = ctx.collection_def()?;

    // Authoritative capability gate: unpublish moves `_status` to `draft`,
    // which only a drafts-enabled definition has. Without drafts the document
    // stays public whatever unpublish records, so it is refused here at the one
    // service chokepoint every surface reaches.
    require_unpublish_capability(ctx)?;

    let access = write_hooks.check_access(
        &AccessCheckInput::builder("unpublish", ctx.slug)
            .access(def.access.update.as_ref())
            .user(ctx.user)
            .id(Some(id))
            .build(),
    )?;

    if matches!(access, AccessResult::Denied) {
        return Err(ServiceError::AccessDenied("Update access denied".into()));
    }

    // When the hook returned Constrained filters, enforce row-level match.
    helpers::enforce_access_constraints(ctx, id, &access, "Update", false)?;

    // Build a default `LocaleContext` from the attached locale config so the
    // raw read picks up locale-suffixed columns (`title__en`, `title__de`)
    // for localized fields. Without this, the SELECT generated by
    // `find_by_id_raw` references bare `title` and SQLite errors with
    // `no such column: title` on collections that have any localized field.
    let locale_ctx = ctx.default_locale_ctx();

    // Lock before reading: the hooks below and the draft snapshot must see the
    // row the status write lands on, not one a concurrent publish is about to
    // replace (Postgres; no-op on SQLite).
    conn.lock_row(ctx.slug, id)?;

    let doc = query::find_by_id_raw(conn, ctx.slug, def, id, locale_ctx.as_ref(), false)?
        .ok_or_else(|| {
            ServiceError::NotFound(format!("Document '{id}' not found in '{}'", ctx.slug))
        })?;

    // Where the row sat going in: unpublishing a published document moves it
    // out of the published view; one that is already a draft moves nowhere.
    let prior = EventViewPlacement::from_fields(&doc.fields);

    let change = StateChange::Unpublish;
    let req_context = run_state_before_change(ctx, change, &doc, locale_ctx.as_ref())?;

    // The files the document references going in — the published row's and
    // every version snapshot's. Unpublishing writes a version like any other
    // lifecycle step, so it prunes like one, and pruning a snapshot is what
    // drops a stored file's last reference. Without this bracket a drafted file
    // whose only snapshot the unpublish pruned stayed in storage forever with
    // nothing naming it.
    let before_files = document_file_keys(ctx, def, id, locale_ctx.as_ref())?;

    // The stored row, stamped `_status = "draft"`.
    let mut doc = persist_unpublish(ctx, id)?;

    // Only `_status` moved, so the published row still references exactly what
    // it did going in; what can go is a file only a pruned snapshot named.
    settle_upload_write(
        ctx,
        &UploadSettle::builder(def, id)
            .before(Some(&before_files))
            .build(),
    )?;

    // Hydrate join fields BEFORE after-change hooks so they see nested data.
    helpers::hydrate_reported(ctx, &mut doc, locale_ctx.as_ref())?;

    run_after_change_hooks(
        write_hooks,
        &def.hooks,
        &def.fields,
        &doc,
        change.after_change(ctx, locale_ctx.as_ref(), req_context),
        conn,
    )?;

    // The row as stored, before anything is shaped or stripped for the writer:
    // the live event is built from it — and announces a removal to the
    // subscribers that could only see it published.
    let row = ctx.event_row(&doc).map(|row| row.moved_from(Some(prior)));

    helpers::strip_reported(ctx, write_hooks, &mut doc, locale_ctx.as_ref())?;

    Ok((doc, row))
}

/// Unpublish a versioned document.
///
/// **Pool mode** (`ctx.pool` set): opens a transaction, commits after success.
/// **Conn mode** (`ctx.conn` set, Lua CRUD path): runs on the existing connection.
///
/// # Errors
///
/// Returns service-layer errors (access denied, document not found, hook
/// errors) or a backend error if the DB transaction or persistence fails.
#[cfg(not(tarpaulin_include))]
pub fn unpublish_document(ctx: &ServiceContext, id: &str) -> Result<Document> {
    if ctx.pool.is_some() {
        unpublish_document_pool(ctx, id)
    } else {
        unpublish_document_conn(ctx, id)
    }
}

fn unpublish_document_pool(ctx: &ServiceContext, id: &str) -> Result<Document> {
    let (doc, _) = run_pool_write(
        ctx,
        None,
        |inner| unpublish_document_in_conn(inner, id),
        |ctx, (doc, row)| {
            ctx.publish_mutation_event(EventOperation::Unpublish, &doc.id, row.clone());
            invalidate_user_streams_if_auth(ctx, &doc.id);
        },
    )?;

    Ok(doc)
}

fn unpublish_document_conn(ctx: &ServiceContext, id: &str) -> Result<Document> {
    let (doc, row) = unpublish_document_in_conn(ctx, id)?;

    ctx.clear_cache();

    ctx.publish_mutation_event(EventOperation::Unpublish, &doc.id, row);
    invalidate_user_streams_if_auth(ctx, &doc.id);

    Ok(doc)
}
