//! Go `ClientPrinter` — structs with json tags for gRPC clients.

use std::collections::HashSet;

use crate::{
    core::Registry,
    typegen::{
        helpers::{SubTypeKind, sorted_collection_slugs, to_pascal_case},
        idents,
    },
};

use super::{
    ClientPrinter, Document, EnumDef, Field, FieldTy, PolyDef, SubType, writer::CodeWriter,
};

/// The fixed exported field names on every Document/global struct, used to
/// pre-seed the de-collision set so a user field can't shadow them.
fn document_seen() -> HashSet<String> {
    ["ID", "CreatedAt", "UpdatedAt"]
        .into_iter()
        .map(String::from)
        .collect()
}

/// The package-level names the prelude and epilogue declare.
const PRELUDE_NAMES: [&str; 2] = ["Rel", "CollectionSlug"];

/// Emits Go type definitions.
pub(super) struct GoPrinter {
    w: CodeWriter,
    /// Every package-level identifier declared so far — types, then the
    /// select and slug constants, which are de-collided against it (a const
    /// `PostsStatusMeta` for option `meta` beside a group type
    /// `PostsStatusMeta` would not compile).
    package_names: HashSet<String>,
}

impl GoPrinter {
    pub(super) fn new() -> Self {
        Self {
            w: CodeWriter::new("\t"),
            package_names: PRELUDE_NAMES.into_iter().map(String::from).collect(),
        }
    }

    /// Emit `type NAME struct { <body> }` followed by a blank line.
    fn struct_def(&mut self, name: &str, body: impl FnOnce(&mut CodeWriter)) {
        self.package_names.insert(name.to_string());
        self.w.block(&format!("type {name} struct {{"), "}", body);
        self.w.blank();
    }

    /// `name`, de-collided against every package-level identifier so far,
    /// and claimed.
    fn package_const(&mut self, name: String) -> String {
        idents::dedup(name, &mut self.package_names)
    }
}

impl ClientPrinter for GoPrinter {
    fn prelude(&mut self) {
        let w = &mut self.w;
        w.line("// Auto-generated by crap-cms. Do not edit.");
        w.blank();
        w.line("package types");
        w.blank();

        // A relationship value: an ID string (depth=0) or a populated document
        // (depth>=1). Go has no union type, so `Rel[T]` carries both and decodes
        // whichever the JSON holds. Emitted unconditionally (like the Rust
        // `Rel<T>`); the imports it needs are used by its own methods, so an
        // unused import never results. Requires Go 1.18+ (generics).
        w.block("import (", ")", |w| {
            w.line("\"bytes\"");
            w.line("\"encoding/json\"");
        });
        w.blank();
        w.line("// Rel is a relationship field: an ID string (depth=0) or a populated");
        w.line("// document (depth>=1).");
        w.block("type Rel[T any] struct {", "}", |w| {
            w.line("ID  string");
            w.line("Doc *T");
        });
        w.blank();
        w.line("// UnmarshalJSON decodes a bare id string into ID, or an object into Doc.");
        w.block(
            "func (r *Rel[T]) UnmarshalJSON(data []byte) error {",
            "}",
            |w| {
                w.block(
                    "if t := bytes.TrimSpace(data); len(t) > 0 && t[0] == '\"' {",
                    "}",
                    |w| w.line("return json.Unmarshal(data, &r.ID)"),
                );
                w.line("r.Doc = new(T)");
                w.line("return json.Unmarshal(data, r.Doc)");
            },
        );
        w.blank();
        w.line("// MarshalJSON emits the populated document when present, else the id.");
        w.block(
            "func (r Rel[T]) MarshalJSON() ([]byte, error) {",
            "}",
            |w| {
                w.block("if r.Doc != nil {", "}", |w| {
                    w.line("return json.Marshal(r.Doc)");
                });
                w.line("return json.Marshal(r.ID)");
            },
        );
        w.blank();
    }

    // Go emits read types only; a write-shape sub-type has nothing to render.
    fn sub_type(&mut self, def: &SubType) {
        if def.input {
            return;
        }

        let name = idents::go_type(&def.name);
        let kind_desc = match def.kind {
            SubTypeKind::Array => format!("a row in the {} array field", def.field_name),
            SubTypeKind::Group => format!("the {} group field", def.field_name),
        };
        self.w.line(&format!("// {name} represents {kind_desc}."));

        let fields = &def.fields;
        self.struct_def(&name, |w| {
            let mut seen = HashSet::new();
            for f in fields {
                emit_field(w, f, &mut seen);
            }
        });
    }

    fn document(&mut self, def: &Document) {
        let base = idents::go_type(&def.name);
        let name = if def.localized {
            format!("{base}Localized")
        } else {
            base
        };
        let comment = match (def.localized, def.is_global) {
            (true, _) => format!(
                "// {name} is a {} document read with locale=all: localized fields hold one value per locale.",
                def.slug
            ),
            (false, true) => format!("// {name} represents the {} global.", def.slug),
            (false, false) => format!("// {name} represents a {} document.", def.slug),
        };
        self.w.line(&comment);

        let members = document_members(def);
        let timestamps = def.timestamps;
        self.struct_def(&name, |w| {
            w.line("ID        string  `json:\"id\"`");
            for (f, go_name) in &members {
                emit_named_field(w, f, go_name);
            }
            if timestamps {
                w.line("CreatedAt *string `json:\"created_at,omitempty\"`");
                w.line("UpdatedAt *string `json:\"updated_at,omitempty\"`");
            }
        });
    }

    fn enum_types(&mut self, defs: &[EnumDef]) {
        // Every enum type is claimed before any constant, so a constant never
        // takes a later enum type's name.
        self.package_names
            .extend(defs.iter().map(|def| idents::go_type(&def.name)));

        for def in defs {
            let type_name = idents::go_type(&def.name);
            self.w.line(&format!(
                "// {type_name} is a select/radio value; unknown values still assign (it is a string)."
            ));
            self.w.line(&format!("type {type_name} string"));
            self.w.blank();

            // Const name = <Type><Variant>, de-collided against every
            // package-level name (types and earlier constants).
            let consts: Vec<(String, &str)> = def
                .values
                .iter()
                .map(|v| {
                    let name = format!("{type_name}{}", idents::variant_ident(v));
                    (self.package_const(name), v.as_str())
                })
                .collect();
            self.w.block("const (", ")", |w| {
                for (name, value) in &consts {
                    w.line(&format!(
                        "{name} {type_name} = \"{}\"",
                        idents::escape_str(value)
                    ));
                }
            });
            self.w.blank();
        }
    }

    // Polymorphic relationships decode to `interface{}` inline; nothing to emit.
    fn poly_types(&mut self, _defs: &[PolyDef]) {}

    fn epilogue(&mut self, registry: &Registry) {
        let slugs = sorted_collection_slugs(registry);
        if slugs.is_empty() {
            return;
        }
        self.w
            .line("// CollectionSlug is one of the known collection slugs.");
        self.w.line("type CollectionSlug string");
        self.w.blank();

        let consts: Vec<(String, &str)> = slugs
            .into_iter()
            .map(|slug| {
                let name = format!(
                    "CollectionSlug{}",
                    idents::go_exported(&to_pascal_case(slug))
                );
                (self.package_const(name), &**slug)
            })
            .collect();
        self.w.block("const (", ")", |w| {
            for (name, slug) in &consts {
                w.line(&format!("{name} CollectionSlug = \"{slug}\""));
            }
        });
        self.w.blank();
    }

    fn finish(self: Box<Self>) -> String {
        self.w.finish()
    }
}

/// A document struct's members after `ID`, each with its de-collided name:
/// its fields, then the stored system keys, then the populated `collection`
/// tag.
///
/// The system keys claim their names before any user field does, so a field
/// added to the schema can never rename a system key's member. The optional
/// tag yields instead: it takes its name after every field, so a field whose
/// member is also `Collection` (`Collection`, `collection_`) keeps its name and
/// the tag member is suffixed — its json key stays `collection`.
fn document_members<'d>(def: &'d Document<'d>) -> Vec<(&'d Field<'d>, String)> {
    let mut seen = document_seen();
    let system: Vec<(&Field, String)> = def
        .system
        .iter()
        .map(|f| (f, idents::dedup(go_member(f), &mut seen)))
        .collect();

    let fields: Vec<(&Field, String)> = def
        .fields
        .iter()
        .map(|f| (f, idents::dedup(go_member(f), &mut seen)))
        .collect();

    let tag = def
        .collection_tag
        .iter()
        .map(|f| (f, idents::dedup(go_member(f), &mut seen)));

    fields.into_iter().chain(system).chain(tag).collect()
}

/// Emit one read struct field under its de-collided member name.
fn emit_field(w: &mut CodeWriter, field: &Field, seen: &mut HashSet<String>) {
    let go_name = idents::dedup(go_member(field), seen);
    emit_named_field(w, field, &go_name);
}

/// The exported Go member name a field's wire key maps to, before
/// de-collision.
fn go_member(field: &Field) -> String {
    let base = match field.name.as_ref() {
        // `_status` would PascalCase onto a `status` field's name.
        "_status" => "DraftStatus".to_string(),
        // Go spells the initialism in capitals, as a document's `ID` does.
        "id" => "ID".to_string(),
        name => to_pascal_case(name),
    };

    idents::go_exported(&base)
}

/// Emit one read struct field — every field is optional on read: an optional
/// polymorphic-target comment, then the alignment-padded name, type, and json
/// struct tag.
fn emit_named_field(w: &mut CodeWriter, field: &Field, go_name: &str) {
    if let FieldTy::PolyRel { targets, .. } = &field.ty {
        w.line(&format!(
            "// Polymorphic relationship — targets: {}",
            targets.join(", ")
        ));
    }

    let (go_type, omitempty) = go_ty(&field.ty, true);
    let tag = if omitempty {
        format!("`json:\"{},omitempty\"`", field.name)
    } else {
        format!("`json:\"{}\"`", field.name)
    };
    w.line(&format!("{go_name:<9} {go_type} {tag}"));
}

/// Map a [`FieldTy`] + optionality to its Go type and `omitempty` flag. A
/// relationship with a known target uses the generic `Rel[T]` wrapper; a
/// polymorphic / empty-target one and select/radio stay id / enum strings.
fn go_ty(ty: &FieldTy, optional: bool) -> (String, bool) {
    let ptr_or_bare = |base: &str| {
        if optional {
            (format!("*{base}"), true)
        } else {
            (base.to_string(), false)
        }
    };
    match ty {
        // A literal set stays a plain string: Go has no string-literal type.
        FieldTy::Str | FieldTy::Literal(_) => ptr_or_bare("string"),
        FieldTy::Num => ptr_or_bare("float64"),
        FieldTy::Bool => ptr_or_bare("bool"),
        FieldTy::Json => ("interface{}".to_string(), true),
        FieldTy::Map => ("map[string]interface{}".to_string(), true),
        FieldTy::StrList => ("[]string".to_string(), true),
        FieldTy::NumList => ("[]float64".to_string(), true),
        FieldTy::JsonList => ("[]map[string]interface{}".to_string(), true),
        // A typed relationship is an id string OR a populated document, carried
        // by the generic `Rel[T]` wrapper. Polymorphic / empty-target
        // relationships (`None`) and select/radio stay plain id / enum strings.
        FieldTy::Rel {
            target: Some(t),
            many,
        } => {
            let rel = format!("Rel[{}]", idents::go_type(t));
            if *many {
                (format!("[]{rel}"), true)
            } else if optional {
                (format!("*{rel}"), true)
            } else {
                (rel, false)
            }
        }
        FieldTy::Rel { target: None, many } => {
            if *many {
                ("[]string".to_string(), true)
            } else {
                ptr_or_bare("string")
            }
        }
        // A polymorphic relationship is an id string OR a populated `{collection,
        // ...doc}` object. Go has no union type, so it decodes to `interface{}`.
        FieldTy::PolyRel { many, .. } => {
            if *many {
                ("[]interface{}".to_string(), true)
            } else {
                ("interface{}".to_string(), true)
            }
        }
        // Select/radio reference the named string type (emitted by `enum_types`).
        FieldTy::Enum { name, many, .. } => {
            let n = idents::go_type(name);
            if *many {
                (format!("[]{n}"), true)
            } else if optional {
                (format!("*{n}"), true)
            } else {
                (n, false)
            }
        }
        // A locale without a value reads as `null`, so a value that can't be
        // nil is held by pointer.
        FieldTy::Localized(inner) => {
            let (inner_ty, nilable) = go_ty(inner, false);
            let value_ty = if nilable {
                inner_ty
            } else {
                format!("*{inner_ty}")
            };
            (format!("map[string]{value_ty}"), true)
        }
        FieldTy::SubType { name, list } => {
            let n = idents::go_type(name);
            if *list {
                (format!("[]{n}"), true)
            } else {
                ptr_or_bare(&n)
            }
        }
    }
}

#[cfg(test)]
mod tests;
