//! Rust `ClientPrinter` — structs with serde derives and a populated-or-id
//! `Rel<T>` for gRPC clients.

use std::collections::HashSet;

use crate::{
    core::Registry,
    typegen::{
        helpers::{sorted_collection_slugs, to_pascal_case},
        idents,
    },
};

use super::{
    ClientPrinter, Document, EnumDef, Field, FieldTy, PolyDef, SubType, writer::CodeWriter,
};

/// Emits Rust type definitions.
pub(super) struct RustPrinter {
    w: CodeWriter,
}

impl RustPrinter {
    pub(super) fn new() -> Self {
        Self {
            w: CodeWriter::new("    "),
        }
    }

    /// Emit the `#[derive(...)]` + `pub struct NAME { ... }` shell, running
    /// `body` for the struct's fields.
    fn struct_def(&mut self, name: &str, body: impl FnOnce(&mut CodeWriter)) {
        self.w
            .line("#[derive(Debug, Clone, Serialize, Deserialize)]");
        let header = format!("pub struct {} {{", idents::rust_type(name));
        self.w.block(&header, "}", body);
        self.w.blank();
    }
}

impl ClientPrinter for RustPrinter {
    fn prelude(&mut self) {
        let w = &mut self.w;
        w.line("// Auto-generated by crap-cms. Do not edit.");
        w.blank();
        w.line("use serde::{Deserialize, Serialize};");
        w.blank();

        w.line("/// A relationship field: either an ID string (depth=0)");
        w.line("/// or a populated document (depth>=1).");
        w.line("#[derive(Debug, Clone, Serialize, Deserialize)]");
        w.line("#[serde(untagged)]");
        w.block("pub enum Rel<T> {", "}", |w| {
            w.line("Doc(Box<T>),");
            w.line("Id(String),");
        });
        w.blank();
        w.block("impl<T> Rel<T> {", "}", |w| {
            w.line("/// Get the ID if unpopulated.");
            w.block("pub fn as_id(&self) -> Option<&str> {", "}", |w| {
                w.line("match self { Rel::Id(id) => Some(id), _ => None }");
            });
            w.blank();
            w.line("/// Get the populated document.");
            w.block("pub fn as_doc(&self) -> Option<&T> {", "}", |w| {
                w.line("match self { Rel::Doc(d) => Some(d), _ => None }");
            });
        });
        w.blank();
    }

    fn sub_type(&mut self, def: &SubType) {
        let fields = &def.fields;
        self.struct_def(&def.name, |w| {
            for f in fields {
                emit_field(w, f);
            }
        });
    }

    fn document(&mut self, def: &Document) {
        let fields = &def.fields;
        let timestamps = def.timestamps;
        self.struct_def(&def.name, |w| {
            w.line("pub id: String,");
            for f in fields {
                emit_field(w, f);
            }
            if timestamps {
                for col in ["created_at", "updated_at"] {
                    w.line("#[serde(skip_serializing_if = \"Option::is_none\")]");
                    w.line(&format!("pub {col}: Option<String>,"));
                }
            }
        });
    }

    fn enum_types(&mut self, defs: &[EnumDef]) {
        for def in defs {
            emit_enum(&mut self.w, def);
        }
    }

    fn poly_types(&mut self, defs: &[PolyDef]) {
        for def in defs {
            emit_poly(&mut self.w, def);
        }
    }

    fn epilogue(&mut self, registry: &Registry) {
        let slugs = sorted_collection_slugs(registry);
        if slugs.is_empty() {
            return;
        }
        self.w.line("/// All collection slugs.");
        self.w
            .line("#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]");
        self.w.block("pub enum CollectionSlug {", "}", |w| {
            for slug in slugs {
                w.line(&format!("#[serde(rename = \"{slug}\")]"));
                w.line(&format!("{},", idents::rust_type(&to_pascal_case(slug))));
            }
        });
        self.w.blank();
    }

    fn finish(self: Box<Self>) -> String {
        self.w.finish()
    }
}

/// Emit one field: an optional polymorphic-target comment, a combined
/// `#[serde(...)]` line (rename and/or skip), then the `pub ident: Type,`.
fn emit_field(w: &mut CodeWriter, field: &Field) {
    if let FieldTy::PolyRel { targets, .. } = &field.ty {
        w.line(&format!(
            "/// Polymorphic relationship — targets: {}",
            targets.join(", ")
        ));
    }
    let ty = rust_ty(&field.ty);
    let f = idents::rust_field(field.name);

    let mut serde_parts: Vec<String> = Vec::new();
    if let Some(wire) = &f.rename {
        serde_parts.push(format!("rename = \"{wire}\""));
    }
    if field.optional {
        serde_parts.push("skip_serializing_if = \"Option::is_none\"".to_string());
    }
    if !serde_parts.is_empty() {
        w.line(&format!("#[serde({})]", serde_parts.join(", ")));
    }

    if field.optional {
        w.line(&format!("pub {}: Option<{ty}>,", f.ident));
    } else {
        w.line(&format!("pub {}: {ty},", f.ident));
    }
}

/// Map a [`FieldTy`] to its Rust type string.
fn rust_ty(ty: &FieldTy) -> String {
    match ty {
        FieldTy::Str => "String".to_string(),
        FieldTy::Num => "f64".to_string(),
        FieldTy::Bool => "bool".to_string(),
        FieldTy::Json | FieldTy::Map => "serde_json::Value".to_string(),
        FieldTy::StrList => "Vec<String>".to_string(),
        FieldTy::NumList => "Vec<f64>".to_string(),
        FieldTy::JsonList => "Vec<serde_json::Value>".to_string(),
        FieldTy::Rel {
            target: Some(t),
            many,
        } => {
            let t = idents::rust_type(t);
            if *many {
                format!("Vec<Rel<{t}>>")
            } else {
                format!("Rel<{t}>")
            }
        }
        // Polymorphic / empty-target relationships are id strings.
        FieldTy::Rel { target: None, many } => {
            if *many {
                "Vec<String>".to_string()
            } else {
                "String".to_string()
            }
        }
        // Select/radio and polymorphic relationships each reference a generated
        // named type (emitted by `enum_types` / `poly_types`).
        FieldTy::Enum { name, many, .. } | FieldTy::PolyRel { name, many, .. } => {
            let n = idents::rust_type(name);
            if *many { format!("Vec<{n}>") } else { n }
        }
        FieldTy::SubType { name, list } => {
            let n = idents::rust_type(name);
            if *list { format!("Vec<{n}>") } else { n }
        }
    }
}

/// Emit a lossless select/radio enum: named variants for the known values plus
/// an `Other(String)` catch-all, wired through `#[serde(from/into)]` so an
/// unrecognized value (e.g. an option removed since generation) round-trips as
/// `Other(value)` instead of failing to deserialize.
fn emit_enum(w: &mut CodeWriter, def: &EnumDef) {
    let type_name = idents::rust_type(&def.name);

    // A unique variant identifier per value; `Other` is reserved for the catch-all.
    let mut seen = HashSet::new();
    seen.insert("Other".to_string());
    let variants: Vec<(String, &str)> = def
        .values
        .iter()
        .map(|v| {
            // `rust_type` applies the `Self` guard (a value `"self"` → variant
            // `Self` would be reserved); `variant_ident` already handled digits.
            let ident = idents::rust_type(&idents::variant_ident(v));
            (idents::dedup(ident, &mut seen), v.as_str())
        })
        .collect();

    w.line("/// Select/radio field values. An unrecognized value (e.g. an option");
    w.line("/// removed since generation) is preserved in `Other`, never rejected.");
    w.line("#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]");
    w.line("#[serde(from = \"String\", into = \"String\")]");
    w.block(&format!("pub enum {type_name} {{"), "}", |w| {
        for (variant, _) in &variants {
            w.line(&format!("{variant},"));
        }
        w.line("Other(String),");
    });
    w.blank();

    w.block(&format!("impl From<String> for {type_name} {{"), "}", |w| {
        w.block("fn from(s: String) -> Self {", "}", |w| {
            w.block("match s.as_str() {", "}", |w| {
                for (variant, value) in &variants {
                    w.line(&format!(
                        "\"{}\" => {type_name}::{variant},",
                        idents::escape_str(value)
                    ));
                }
                w.line(&format!("_ => {type_name}::Other(s),"));
            });
        });
    });
    w.blank();

    w.block(&format!("impl From<{type_name}> for String {{"), "}", |w| {
        w.block(&format!("fn from(v: {type_name}) -> Self {{"), "}", |w| {
            w.block("match v {", "}", |w| {
                for (variant, value) in &variants {
                    w.line(&format!(
                        "{type_name}::{variant} => \"{}\".to_string(),",
                        idents::escape_str(value)
                    ));
                }
                w.line(&format!("{type_name}::Other(s) => s,"));
            });
        });
    });
    w.blank();
}

/// Emit a polymorphic relationship's type: an untagged wrapper that is either
/// an id string or a populated document, with the document side an internally
/// `collection`-tagged enum over the target types. Sound at every depth — the
/// composite `"collection/id"` string decodes to `Id`, the `{collection, ...}`
/// object at depth>=1 decodes to the matching document variant.
fn emit_poly(w: &mut CodeWriter, def: &PolyDef) {
    let wrapper = idents::rust_type(&def.name);
    let doc_enum = format!("{wrapper}Ref");

    w.line("/// A polymorphic relationship: an id string, or one of the target");
    w.line("/// documents (populated at depth>=1), keyed by the `collection` field.");
    w.line("#[derive(Debug, Clone, Serialize, Deserialize)]");
    w.line("#[serde(untagged)]");
    w.block(&format!("pub enum {wrapper} {{"), "}", |w| {
        w.line(&format!("Doc({doc_enum}),"));
        w.line("Id(String),");
    });
    w.blank();

    w.line("#[derive(Debug, Clone, Serialize, Deserialize)]");
    w.line("#[serde(tag = \"collection\")]");
    w.block(&format!("pub enum {doc_enum} {{"), "}", |w| {
        for target in &def.targets {
            let struct_name = idents::rust_type(&to_pascal_case(target));
            w.line(&format!(
                "#[serde(rename = \"{}\")]",
                idents::escape_str(target)
            ));
            w.line(&format!("{struct_name}(Box<{struct_name}>),"));
        }
    });
    w.blank();
}

#[cfg(test)]
mod tests {
    use super::super::drive;
    use super::*;
    use crate::core::{
        BlockDefinition, CollectionDefinition, FieldDefinition, FieldTab, FieldType,
        GlobalDefinition, LocalizedString, RelationshipConfig, SelectOption,
    };

    fn render(registry: &Registry) -> String {
        drive(registry, Box::new(RustPrinter::new()))
    }

    fn render_collection(out: &mut String, col: &CollectionDefinition) {
        let mut r = Registry::new();
        r.register_collection(col.clone());
        out.push_str(&render(&r));
    }

    fn render_global(out: &mut String, global: &GlobalDefinition) {
        let mut r = Registry::new();
        r.register_global(global.clone());
        out.push_str(&render(&r));
    }

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Text)
            .required(required)
            .build()
    }

    fn make_col(slug: &str, fields: Vec<FieldDefinition>) -> CollectionDefinition {
        let mut def = CollectionDefinition::new(slug);
        def.timestamps = true;
        def.fields = fields;
        def
    }

    /// The generated Rust must parse — a compile-grade check that closes the
    /// string-match gap the raw-string generators left open.
    #[test]
    fn generated_rust_parses() {
        let mut registry = Registry::new();
        registry.register_collection(make_col(
            "2fa",
            vec![
                text_field("type", true),
                text_field("self", false),
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![text_field("label", true)])
                    .build(),
                FieldDefinition::builder("author", FieldType::Relationship)
                    .required(true)
                    .relationship(RelationshipConfig::new("users", false))
                    .build(),
            ],
        ));
        let mut settings = GlobalDefinition::new("settings");
        settings.fields = vec![text_field("name", true)];
        registry.register_global(settings);

        let src = render(&registry);
        syn::parse_file(&src)
            .unwrap_or_else(|e| panic!("generated Rust must parse: {e}\n---\n{src}"));
    }

    /// Identifier safety: a digit-leading slug (→ `N`-prefixed struct), a raw-able
    /// keyword field (`r#type`, no rename), a non-raw keyword (`self_` + rename),
    /// and a leading-digit field (`n2fa` + rename).
    #[test]
    fn rust_types_sanitizes_unsafe_field_names() {
        let col = make_col(
            "2fa",
            vec![
                text_field("type", true),
                text_field("self", false),
                text_field("2fa", false),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(
            out.contains("pub struct N2fa {"),
            "leading-digit struct prefixed: {out}"
        );
        assert!(
            out.contains("pub r#type: String,"),
            "keyword → r#type: {out}"
        );
        assert!(
            out.contains("#[serde(rename = \"self\""),
            "self renamed: {out}"
        );
        assert!(out.contains("pub self_:"), "self → self_: {out}");
        assert!(
            out.contains("#[serde(rename = \"2fa\""),
            "2fa renamed: {out}"
        );
        assert!(out.contains("pub n2fa:"), "2fa → n2fa: {out}");
    }

    #[test]
    fn rust_collection_output() {
        let col = make_col(
            "posts",
            vec![text_field("title", true), text_field("content", false)],
        );

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("#[derive(Debug, Clone, Serialize, Deserialize)]"));
        assert!(out.contains("pub struct Posts {"));
        assert!(out.contains("    pub id: String,"));
        assert!(out.contains("    pub title: String,"));
        assert!(out.contains("    pub content: Option<String>,"));
        assert!(out.contains("    pub created_at: Option<String>,"));
    }

    #[test]
    fn rust_relationship_has_many() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("tags", FieldType::Relationship)
                    .relationship(RelationshipConfig::new("tags", true))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Option<Vec<Rel<Tags>>>"));
    }

    #[test]
    fn rust_polymorphic_has_one() {
        let mut rc = RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".into(), "pages".into()];
        let col = make_col(
            "comments",
            vec![
                FieldDefinition::builder("subject", FieldType::Relationship)
                    .required(true)
                    .relationship(rc)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Polymorphic has-one is a typed discriminated enum (id or a target doc),
        // optional on read (populate can null it).
        assert!(
            out.contains("pub subject: Option<CommentsSubject>,"),
            "poly has-one → enum: {out}"
        );
        assert!(
            out.contains("#[serde(untagged)]"),
            "wrapper is untagged: {out}"
        );
        assert!(
            out.contains("pub enum CommentsSubject {"),
            "wrapper enum: {out}"
        );
        assert!(out.contains("Id(String),"), "id variant: {out}");
        assert!(
            out.contains("#[serde(tag = \"collection\")]"),
            "doc enum tagged by collection: {out}"
        );
        assert!(
            out.contains("pub enum CommentsSubjectRef {"),
            "doc enum: {out}"
        );
        assert!(
            out.contains("Posts(Box<Posts>),") && out.contains("Pages(Box<Pages>),"),
            "per-target variants: {out}"
        );
        assert!(out.contains("Polymorphic relationship"), "comment: {out}");
    }

    #[test]
    fn rust_polymorphic_single_target() {
        let mut rc = RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".into()];
        let col = make_col(
            "comments",
            vec![
                FieldDefinition::builder("subject", FieldType::Relationship)
                    .required(true)
                    .relationship(rc)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub enum CommentsSubjectRef {"), "{out}");
        assert!(
            out.contains("Posts(Box<Posts>),"),
            "single-target poly still emits a variant: {out}"
        );
    }

    #[test]
    fn rust_polymorphic_has_many() {
        let mut rc = RelationshipConfig::new("articles", true);
        rc.polymorphic = vec!["articles".into(), "videos".into()];
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("related", FieldType::Relationship)
                    .relationship(rc)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("pub related: Option<Vec<PostsRelated>>,"),
            "poly has-many → Vec of enum: {out}"
        );
        assert!(
            out.contains("Articles(Box<Articles>),") && out.contains("Videos(Box<Videos>),"),
            "per-target variants: {out}"
        );
        assert!(out.contains("Polymorphic relationship"), "comment: {out}");
    }

    #[test]
    fn rust_relationship_has_one_required() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("author", FieldType::Relationship)
                    .required(true)
                    .relationship(RelationshipConfig::new("users", false))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Even a required single relationship is optional on read (populate can
        // null it when the target is soft-deleted / access-denied).
        assert!(
            out.contains("pub author: Option<Rel<Users>>,"),
            "got: {out}"
        );
    }

    #[test]
    fn rust_number_checkbox_json_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("price", FieldType::Number)
                    .required(true)
                    .build(),
                FieldDefinition::builder("active", FieldType::Checkbox).build(),
                FieldDefinition::builder("meta", FieldType::Json).build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub price: f64,"));
        assert!(out.contains("Option<bool>"));
        assert!(out.contains("Option<serde_json::Value>"));
    }

    #[test]
    fn rust_array_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![text_field("label", true)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub struct PostsItems {"));
        assert!(out.contains("Option<Vec<PostsItems>>"));
    }

    #[test]
    fn rust_array_without_subfields() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("data", FieldType::Array).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Option<Vec<serde_json::Value>>"));
    }

    #[test]
    fn rust_group_and_blocks_fields() {
        let col = make_col(
            "pages",
            vec![
                FieldDefinition::builder("seo", FieldType::Group).build(),
                FieldDefinition::builder("content", FieldType::Blocks)
                    .blocks(vec![BlockDefinition::new(
                        "text",
                        vec![text_field("body", true)],
                    )])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Option<serde_json::Value>"), "empty group");
        assert!(out.contains("Option<Vec<serde_json::Value>>"), "blocks");
    }

    #[test]
    fn rust_group_field_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("seo", FieldType::Group)
                    .fields(vec![
                        text_field("title", true),
                        text_field("description", false),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("pub struct PostsSeo {"),
            "group sub-type: {out}"
        );
        assert!(out.contains("pub title: String,"), "group sub-field: {out}");
        assert!(
            out.contains("pub description: Option<String>,"),
            "group optional sub-field: {out}"
        );
    }

    #[test]
    fn rust_array_nested_in_row() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("layout", FieldType::Row)
                    .fields(vec![
                        FieldDefinition::builder("items", FieldType::Array)
                            .fields(vec![text_field("label", true)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("pub struct PostsItems {"),
            "array nested in Row should emit sub-type: {out}"
        );
    }

    #[test]
    fn rust_global_with_subtypes() {
        let mut global = GlobalDefinition::new("settings");
        global.fields = vec![
            FieldDefinition::builder("nav", FieldType::Array)
                .fields(vec![text_field("label", true)])
                .build(),
            FieldDefinition::builder("seo", FieldType::Group)
                .fields(vec![text_field("title", true)])
                .build(),
        ];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(
            out.contains("pub struct SettingsNav {"),
            "array sub-type: {out}"
        );
        assert!(
            out.contains("pub struct SettingsSeo {"),
            "group sub-type: {out}"
        );
    }

    #[test]
    fn rust_upload_and_select_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("image", FieldType::Upload)
                    .required(true)
                    .build(),
                FieldDefinition::builder("status", FieldType::Select)
                    .required(true)
                    .options(vec![SelectOption::new(
                        LocalizedString::Plain("Draft".into()),
                        "draft",
                    )])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Single upload is optional on read (populate can null it).
        assert!(out.contains("pub image: Option<String>,"), "got: {out}");
        assert!(
            out.contains("pub status: ItemsStatus,"),
            "select → enum type: {out}"
        );
    }

    /// Proves the pattern `emit_poly` generates compiles and is sound at every
    /// depth: the `"collection/id"` string (depth=0) decodes to `Id`, and the
    /// `{collection, ...doc}` object (depth>=1) decodes to the matching variant.
    #[test]
    fn poly_pattern_compiles_and_roundtrips() {
        #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
        struct Posts {
            id: String,
            title: String,
        }
        #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
        #[serde(tag = "collection")]
        enum RelatedRef {
            #[serde(rename = "posts")]
            Posts(Box<Posts>),
        }
        #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
        #[serde(untagged)]
        enum Related {
            Doc(RelatedRef),
            Id(String),
        }

        // depth=0: the composite id string.
        assert_eq!(
            serde_json::from_str::<Related>("\"posts/a1\"").unwrap(),
            Related::Id("posts/a1".to_string())
        );
        // depth>=1: the populated {collection, ...doc} object.
        let obj = r#"{"collection":"posts","id":"a1","title":"Hello"}"#;
        let got = serde_json::from_str::<Related>(obj).unwrap();
        assert!(matches!(got, Related::Doc(RelatedRef::Posts(_))));
    }

    /// Proves the pattern `emit_enum` generates actually compiles and behaves:
    /// a value not in the option set (e.g. one removed since generation) is
    /// preserved in `Other` rather than failing to deserialize, and round-trips.
    #[test]
    fn lossless_enum_pattern_compiles_and_roundtrips() {
        #[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
        #[serde(from = "String", into = "String")]
        enum Status {
            Draft,
            Published,
            Other(String),
        }
        impl From<String> for Status {
            fn from(s: String) -> Self {
                match s.as_str() {
                    "draft" => Status::Draft,
                    "published" => Status::Published,
                    _ => Status::Other(s),
                }
            }
        }
        impl From<Status> for String {
            fn from(v: Status) -> Self {
                match v {
                    Status::Draft => "draft".to_string(),
                    Status::Published => "published".to_string(),
                    Status::Other(s) => s,
                }
            }
        }

        assert_eq!(
            serde_json::from_str::<Status>("\"draft\"").unwrap(),
            Status::Draft
        );
        // A since-removed option value survives instead of erroring.
        assert_eq!(
            serde_json::from_str::<Status>("\"legacy\"").unwrap(),
            Status::Other("legacy".to_string())
        );
        assert_eq!(
            serde_json::to_string(&Status::Other("legacy".to_string())).unwrap(),
            "\"legacy\""
        );
        assert_eq!(serde_json::to_string(&Status::Draft).unwrap(), "\"draft\"");
    }

    #[test]
    fn rust_reserved_self_is_guarded_in_variant_and_type() {
        // A select option value `self` → variant `Self` would be reserved; and a
        // collection named `self` → `struct Self` / `CollectionSlug::Self` too.
        let mut registry = Registry::new();
        registry.register_collection(make_col(
            "self",
            vec![
                FieldDefinition::builder("visibility", FieldType::Select)
                    .required(true)
                    .options(vec![SelectOption::new(
                        LocalizedString::Plain("Self".into()),
                        "self",
                    )])
                    .build(),
            ],
        ));
        let out = render(&registry);

        assert!(
            out.contains("pub struct Self_ {"),
            "self collection → Self_: {out}"
        );
        assert!(
            out.contains("Self_,"),
            "self option value → Self_ variant: {out}"
        );
        assert!(
            out.contains("\"self\" => SelfVisibility::Self_,"),
            "match keeps the raw value: {out}"
        );
        assert!(
            out.contains("#[serde(rename = \"self\")]"),
            "CollectionSlug variant keeps wire slug: {out}"
        );
    }

    #[test]
    fn rust_select_options_emit_lossless_enum() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("status", FieldType::Select)
                    .required(true)
                    .options(vec![
                        SelectOption::new(LocalizedString::Plain("Draft".into()), "draft"),
                        SelectOption::new(
                            LocalizedString::Plain("In Progress".into()),
                            "in-progress",
                        ),
                    ])
                    .build(),
            ],
        );
        let out = {
            let mut r = Registry::new();
            r.register_collection(col);
            render(&r)
        };
        assert!(
            out.contains("#[serde(from = \"String\", into = \"String\")]"),
            "{out}"
        );
        assert!(out.contains("pub enum ItemsStatus {"), "{out}");
        assert!(out.contains("Draft,"), "{out}");
        assert!(
            out.contains("InProgress,"),
            "arbitrary value → valid variant: {out}"
        );
        assert!(
            out.contains("Other(String),"),
            "catch-all preserves unknowns: {out}"
        );
        assert!(
            out.contains("\"in-progress\" => ItemsStatus::InProgress,"),
            "match uses raw value: {out}"
        );
        assert!(
            out.contains("ItemsStatus::Other(s) => s,"),
            "into-String round-trips Other: {out}"
        );
    }

    #[test]
    fn upload_has_many_generates_array_type() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("images", FieldType::Upload)
                    .required(true)
                    .relationship(RelationshipConfig::new("", true))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("pub images: Vec<String>,"),
            "has-many upload should be Vec<String>: {out}"
        );
    }

    #[test]
    fn rust_global_output() {
        let mut global = GlobalDefinition::new("site_settings");
        global.fields = vec![text_field("site_name", true)];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(out.contains("pub struct SiteSettings {"));
        assert!(out.contains("pub id: String,"));
        assert!(out.contains("pub site_name: String,"));
        assert!(out.contains("pub created_at: Option<String>,"));
    }

    #[test]
    fn rust_full_render() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        let mut settings = GlobalDefinition::new("settings");
        settings.fields = vec![text_field("name", true)];
        registry.register_global(settings);
        let out = render(&registry);
        assert!(out.contains("use serde::{Deserialize, Serialize};"));
        assert!(out.contains("pub struct Posts {"));
        assert!(out.contains("pub struct Settings {"));
    }

    #[test]
    fn rust_collection_slug_enum() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        registry.register_collection(make_col("pages", vec![text_field("body", true)]));
        let out = render(&registry);
        assert!(out.contains("pub enum CollectionSlug {"), "got: {out}");
        assert!(out.contains("#[serde(rename = \"pages\")]"), "got: {out}");
        assert!(out.contains("Pages,"), "got: {out}");
        assert!(out.contains("Posts,"), "got: {out}");
    }

    #[test]
    fn rust_no_collection_slug_when_empty() {
        let out = render(&Registry::new());
        assert!(!out.contains("CollectionSlug"));
    }

    #[test]
    fn rust_no_timestamps() {
        let mut col = make_col("tags", vec![text_field("name", true)]);
        col.timestamps = false;
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(!out.contains("created_at"));
    }

    #[test]
    fn rust_text_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("tags", FieldType::Text)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("labels", FieldType::Text)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub tags: Vec<String>,"), "required: {out}");
        assert!(out.contains("Option<Vec<String>>"), "optional: {out}");
    }

    #[test]
    fn rust_number_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("scores", FieldType::Number)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("weights", FieldType::Number)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub scores: Vec<f64>,"), "required: {out}");
        assert!(out.contains("Option<Vec<f64>>"), "optional: {out}");
    }

    #[test]
    fn rust_email_date_richtext_textarea() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("email", FieldType::Email)
                    .required(true)
                    .build(),
                FieldDefinition::builder("date", FieldType::Date)
                    .required(true)
                    .build(),
                FieldDefinition::builder("body", FieldType::Richtext)
                    .required(true)
                    .build(),
                FieldDefinition::builder("notes", FieldType::Textarea)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub email: String,"));
        assert!(out.contains("pub date: String,"));
        assert!(out.contains("pub body: String,"));
        assert!(out.contains("pub notes: String,"));
    }

    #[test]
    fn rust_code_join_radio_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("snippet", FieldType::Code)
                    .required(true)
                    .build(),
                FieldDefinition::builder("refs", FieldType::Join).build(),
                FieldDefinition::builder("color", FieldType::Radio)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub snippet: String,"), "code → String: {out}");
        assert!(
            out.contains("Option<Vec<serde_json::Value>>"),
            "join → Vec<Value>: {out}"
        );
        assert!(
            out.contains("pub color: String,"),
            "radio no-options → String: {out}"
        );
    }

    #[test]
    fn rust_select_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("tags", FieldType::Select)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("sizes", FieldType::Radio)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub tags: Vec<String>,"), "required: {out}");
        assert!(out.contains("Option<Vec<String>>"), "optional: {out}");
    }

    #[test]
    fn rust_row_collapsible_tabs_promote_subfields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("layout_row", FieldType::Row)
                    .fields(vec![
                        text_field("first_name", true),
                        text_field("last_name", false),
                    ])
                    .build(),
                FieldDefinition::builder("details", FieldType::Collapsible)
                    .fields(vec![text_field("bio", false)])
                    .build(),
                FieldDefinition::builder("sections", FieldType::Tabs)
                    .tabs(vec![FieldTab::new(
                        "Tab1",
                        vec![text_field("tab_field", true)],
                    )])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(!out.contains("layout_row"), "row name not a field: {out}");
        assert!(
            out.contains("pub first_name: String,"),
            "row required: {out}"
        );
        assert!(
            out.contains("pub last_name: Option<String>,"),
            "row optional: {out}"
        );
        assert!(
            !out.contains("details"),
            "collapsible name not a field: {out}"
        );
        assert!(
            out.contains("pub bio: Option<String>,"),
            "collapsible sub: {out}"
        );
        assert!(!out.contains("sections"), "tabs name not a field: {out}");
        assert!(out.contains("pub tab_field: String,"), "tabs sub: {out}");
    }
}
