//! TypeScript `ClientPrinter` — interfaces for gRPC client wrappers.

use crate::{
    core::Registry,
    typegen::{
        helpers::{sorted_collection_slugs, to_pascal_case},
        idents,
    },
};

use super::{
    ClientPrinter, Document, EnumDef, Field, FieldTy, PolyDef, SubType, writer::CodeWriter,
};

/// Emits TypeScript type definitions.
pub(super) struct TsPrinter {
    w: CodeWriter,
}

impl TsPrinter {
    pub(super) fn new() -> Self {
        Self {
            w: CodeWriter::new("  "),
        }
    }

    /// Emit a read document: `id`, every field optional and nullable, then the
    /// stored system keys and timestamps.
    fn read_interface(&mut self, name: &str, def: &Document) {
        let (fields, system, timestamps) = (&def.fields, &def.system, def.timestamps);

        self.interface(name, |w| {
            w.line("id: string;");
            for f in fields.iter().chain(system) {
                emit_read_field(w, f);
            }
            if timestamps {
                w.line("created_at?: string;");
                w.line("updated_at?: string;");
            }
        });
    }

    /// Emit `export interface NAME { <body> }` followed by a blank line.
    fn interface(&mut self, name: &str, body: impl FnOnce(&mut CodeWriter)) {
        self.w
            .block(&format!("export interface {name} {{"), "}", body);
        self.w.blank();
    }
}

impl ClientPrinter for TsPrinter {
    fn prelude(&mut self) {
        self.w.line("// Auto-generated by crap-cms. Do not edit.");
        self.w.blank();
        self.w.line(
            "/** A localized field read with `locale = \"all\"`: one value per locale code, `null` where a locale has none. */",
        );
        self.w
            .line("export type Localized<T> = { [locale: string]: T | null };");
        self.w.blank();
    }

    /// A sub-type's input variant (`…Data`, its required fields kept) and its
    /// read type, whose every field is optional and nullable.
    fn sub_type(&mut self, def: &SubType) {
        let name = idents::ts_type(&def.name);
        let fields = &def.fields;

        if !def.read_only {
            self.interface(&format!("{name}Data"), |w| {
                for f in fields {
                    emit_input_field(w, f);
                }
            });
        }

        self.interface(&name, |w| {
            for f in fields {
                emit_read_field(w, f);
            }
        });
    }

    fn document(&mut self, def: &Document) {
        let pascal = idents::ts_type(&def.name);

        if def.localized {
            self.w.line(&format!(
                "/** {pascal} read with `locale = \"all\"`: localized fields hold one value per locale */"
            ));
            self.read_interface(&format!("{pascal}LocalizedDocument"), def);
            return;
        }

        let data_doc = if def.is_global {
            format!("/** Input data for the {pascal} global; an update accepts any subset */")
        } else {
            format!(
                "/** Input data for creating a {pascal}; an update accepts any subset (`Partial<{pascal}Data>`) */"
            )
        };
        self.w.line(&data_doc);
        let fields = &def.fields;
        self.interface(&format!("{pascal}Data"), |w| {
            for f in fields {
                emit_input_field(w, f);
            }
        });

        let doc_doc = if def.is_global {
            format!("/** {pascal} global document */")
        } else {
            format!("/** {pascal} document returned from the API */")
        };
        self.w.line(&doc_doc);
        self.read_interface(&format!("{pascal}Document"), def);
    }

    // Select/radio narrowing and polymorphic unions are inlined at each use site.
    fn enum_types(&mut self, _defs: &[EnumDef]) {}

    fn poly_types(&mut self, _defs: &[PolyDef]) {}

    fn epilogue(&mut self, registry: &Registry) {
        let slugs = sorted_collection_slugs(registry);
        if slugs.is_empty() {
            return;
        }
        let union = slugs
            .iter()
            .map(|s| format!("\"{s}\""))
            .collect::<Vec<_>>()
            .join(" | ");
        self.w.line("/** All collection slugs */");
        self.w
            .line(&format!("export type CollectionSlug = {union};"));
    }

    fn finish(self: Box<Self>) -> String {
        self.w.finish()
    }
}

/// Emit one read property: optional, and `null` where the stored value is
/// empty.
fn emit_read_field(w: &mut CodeWriter, field: &Field) {
    emit_property(w, field, true, &format!("{} | null", ts_ty(&field.ty)));
}

/// Emit one input property: its own optionality, and a nested sub-type as its
/// input variant.
fn emit_input_field(w: &mut CodeWriter, field: &Field) {
    emit_property(w, field, field.optional, &input_ty(&field.ty));
}

/// Emit one interface property: an optional polymorphic-target `JSDoc` comment,
/// then `key?: type;` (`?` when `optional`).
fn emit_property(w: &mut CodeWriter, field: &Field, optional: bool, ty: &str) {
    if let FieldTy::PolyRel { targets, .. } = &field.ty {
        w.line(&format!(
            "/** Polymorphic relationship — targets: {} */",
            targets.join(", ")
        ));
    }
    let opt = if optional { "?" } else { "" };
    w.line(&format!("{}{opt}: {ty};", idents::ts_key(&field.name)));
}

/// The TypeScript type of an input value: a sub-type is its `…Data` variant.
fn input_ty(ty: &FieldTy) -> String {
    let FieldTy::SubType { name, list } = ty else {
        return ts_ty(ty);
    };

    let n = format!("{}Data", idents::ts_type(name));
    if *list { format!("{n}[]") } else { n }
}

/// Map a [`FieldTy`] to its TypeScript type string.
fn ts_ty(ty: &FieldTy) -> String {
    match ty {
        FieldTy::Str => "string".to_string(),
        FieldTy::Num => "number".to_string(),
        FieldTy::Bool => "boolean".to_string(),
        FieldTy::Json => "unknown".to_string(),
        FieldTy::Map => "Record<string, unknown>".to_string(),
        FieldTy::StrList => "string[]".to_string(),
        FieldTy::NumList => "number[]".to_string(),
        FieldTy::JsonList => "Record<string, unknown>[]".to_string(),
        // A typed relationship is an id string OR a populated document (the API's
        // `depth` controls which), so it unions the id with the target's
        // `Document` type. Polymorphic / empty-target relationships (`None`)
        // have no known type and stay plain id strings.
        FieldTy::Rel {
            target: Some(t),
            many,
        } => {
            let doc = format!("{}Document", idents::ts_type(t));
            if *many {
                format!("(string | {doc})[]")
            } else {
                format!("string | {doc}")
            }
        }
        FieldTy::Rel { target: None, many } => {
            if *many {
                "string[]".to_string()
            } else {
                "string".to_string()
            }
        }
        // A polymorphic relationship is an id string OR one of the target docs
        // (populated at depth>=1), so it unions the id with every target's Document.
        FieldTy::PolyRel { targets, many, .. } => {
            let mut parts = vec!["string".to_string()];
            parts.extend(
                targets
                    .iter()
                    .map(|t| format!("{}Document", idents::ts_type(&to_pascal_case(t)))),
            );
            let base = parts.join(" | ");
            if *many { format!("({base})[]") } else { base }
        }
        FieldTy::SubType { name, list } => {
            let n = idents::ts_type(name);
            if *list { format!("{n}[]") } else { n }
        }
        FieldTy::Localized(inner) => format!("Localized<{}>", ts_ty(inner)),
        FieldTy::Enum { values, many, .. } => {
            let base = values
                .iter()
                .map(|v| format!("\"{}\"", idents::escape_str(v)))
                .collect::<Vec<_>>()
                .join(" | ");
            if *many { format!("({base})[]") } else { base }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::super::drive;
    use super::*;
    use crate::core::{
        BlockDefinition, CollectionDefinition, FieldAdmin, FieldDefinition, FieldTab, FieldType,
        GlobalDefinition, LocalizedString, RelationshipConfig, SelectOption, VersionsConfig,
    };

    /// One generated `export interface` block, from its header to its closing brace.
    fn interface_block<'a>(out: &'a str, header: &str) -> &'a str {
        let start = out
            .find(header)
            .unwrap_or_else(|| panic!("{header} not emitted:\n{out}"));
        let rest = &out[start..];

        &rest[..rest.find("\n}").map_or(rest.len(), |i| i + 2)]
    }

    /// A read document may lack any field — a draft may miss required values,
    /// and field read access and `select` leave keys out — so every field of
    /// the document, and of its sub-types, is optional. The create input keeps
    /// its required fields, nested ones included: its sub-types are the `…Data`
    /// variants.
    #[test]
    fn typescript_read_document_fields_are_optional() {
        let col = make_col(
            "posts",
            vec![
                text_field("title", true),
                FieldDefinition::builder("seo", FieldType::Group)
                    .fields(vec![text_field("meta_title", true)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        let doc = interface_block(&out, "export interface PostsDocument {");
        assert!(doc.contains("  title?: string | null;"), "{doc}");
        assert!(doc.contains("  seo?: PostsSeo | null;"), "{doc}");

        let seo = interface_block(&out, "export interface PostsSeo {");
        assert!(seo.contains("  meta_title?: string | null;"), "{seo}");

        let data = interface_block(&out, "export interface PostsData {");
        assert!(data.contains("  title: string;"), "{data}");
        assert!(data.contains("  seo?: PostsSeoData;"), "{data}");
        assert!(out.contains("/** Input data for creating a Posts"), "{out}");

        let seo_input = interface_block(&out, "export interface PostsSeoData {");
        assert!(seo_input.contains("  meta_title: string;"), "{seo_input}");
    }

    /// A read document carries the stored system keys its collection has, and
    /// a timezone date's `<name>_tz` companion (also accepted as input).
    #[test]
    fn typescript_read_document_has_system_keys() {
        let mut col = make_col(
            "events",
            vec![
                FieldDefinition::builder("starts", FieldType::Date)
                    .timezone(true)
                    .build(),
            ],
        );
        col.soft_delete = true;
        col.versions = Some(VersionsConfig::new(true, 10));
        let mut out = String::new();
        render_collection(&mut out, &col);

        let doc = interface_block(&out, "export interface EventsDocument {");
        assert!(doc.contains("  _status?: string | null;"), "{doc}");
        assert!(doc.contains("  _deleted_at?: string | null;"), "{doc}");
        assert!(doc.contains("  starts_tz?: string | null;"), "{doc}");

        let data = interface_block(&out, "export interface EventsData {");
        assert!(data.contains("  starts_tz?: string;"), "{data}");
        assert!(!data.contains("_status"), "{data}");
    }

    /// A code field with a language allow-list.
    fn code_with_languages(name: &str) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Code)
            .admin(
                FieldAdmin::builder()
                    .languages(vec!["python".to_string()])
                    .build(),
            )
            .build()
    }

    /// A code field with a language allow-list carries its `<name>_lang`
    /// companion (also accepted as input), at the top level and inside a group.
    #[test]
    fn typescript_code_field_has_its_language_companion() {
        let col = make_col(
            "snippets",
            vec![
                code_with_languages("snippet"),
                FieldDefinition::builder("plain", FieldType::Code).build(),
                FieldDefinition::builder("meta", FieldType::Group)
                    .fields(vec![code_with_languages("example")])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        let doc = interface_block(&out, "export interface SnippetsDocument {");
        assert!(doc.contains("  snippet_lang?: string | null;"), "{doc}");

        let data = interface_block(&out, "export interface SnippetsData {");
        assert!(data.contains("  snippet_lang?: string;"), "{data}");

        let meta = interface_block(&out, "export interface SnippetsMeta {");
        assert!(meta.contains("  example_lang?: string | null;"), "{meta}");

        assert!(!out.contains("plain_lang"), "{out}");
    }

    /// Under `locale = "all"` a localized code field's language pick is a
    /// per-locale map, like its value.
    #[test]
    fn typescript_localized_code_language_companion_is_per_locale() {
        let mut snippet = code_with_languages("snippet");
        snippet.localized = true;
        let col = make_col("snippets", vec![snippet]);
        let mut out = String::new();
        render_collection(&mut out, &col);

        let doc = interface_block(&out, "export interface SnippetsLocalizedDocument {");
        assert!(
            doc.contains("  snippet_lang?: Localized<string> | null;"),
            "{doc}"
        );
    }

    /// A `locale = "all"` read returns each localized field as a per-locale
    /// map; the localized document types it so, through localized groups too.
    #[test]
    fn typescript_localized_document_wraps_localized_fields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("title", FieldType::Text)
                    .localized(true)
                    .build(),
                text_field("slug", true),
                FieldDefinition::builder("seo", FieldType::Group)
                    .localized(true)
                    .fields(vec![text_field("meta_title", true)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(
            out.contains("export type Localized<T> = { [locale: string]: T | null };"),
            "{out}"
        );

        let doc = interface_block(&out, "export interface PostsLocalizedDocument {");
        assert!(doc.contains("  title?: Localized<string> | null;"), "{doc}");
        assert!(doc.contains("  slug?: string | null;"), "{doc}");
        assert!(doc.contains("  seo?: PostsSeoLocalized | null;"), "{doc}");

        let seo = interface_block(&out, "export interface PostsSeoLocalized {");
        assert!(
            seo.contains("  meta_title?: Localized<string> | null;"),
            "{seo}"
        );
    }

    #[test]
    fn typescript_no_localized_document_without_localized_fields() {
        let col = make_col("posts", vec![text_field("title", true)]);
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(!out.contains("LocalizedDocument"), "{out}");
    }

    fn render(registry: &Registry) -> String {
        drive(registry, Box::new(TsPrinter::new()))
    }

    fn render_collection(out: &mut String, col: &CollectionDefinition) {
        let mut r = Registry::new();
        r.register_collection(col.clone());
        out.push_str(&render(&r));
    }

    fn render_global(out: &mut String, global: &GlobalDefinition) {
        let mut r = Registry::new();
        r.register_global(global.clone());
        out.push_str(&render(&r));
    }

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Text)
            .required(required)
            .build()
    }

    fn select_field(name: &str, opts: &[&str]) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Select)
            .required(true)
            .options(
                opts.iter()
                    .map(|v| SelectOption::new(LocalizedString::Plain(v.to_string()), *v))
                    .collect(),
            )
            .build()
    }

    fn make_col(slug: &str, fields: Vec<FieldDefinition>) -> CollectionDefinition {
        let mut def = CollectionDefinition::new(slug);
        def.timestamps = true;
        def.fields = fields;
        def
    }

    /// Identifier safety: a digit-leading slug/field, a keyword field, and a
    /// select-option value with special chars must all produce valid TS.
    #[test]
    fn typescript_sanitizes_unsafe_names_and_option_values() {
        let col = make_col(
            "2fa",
            vec![
                text_field("type", true),
                text_field("2fa", false),
                select_field("status", &["a\"b"]),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(
            out.contains("export interface N2faData {"),
            "leading-digit type must be prefixed: {out}"
        );
        assert!(out.contains("  type: string;"), "keyword bare key: {out}");
        assert!(
            out.contains("  \"2fa\"?: string;"),
            "leading-digit key quoted: {out}"
        );
        assert!(out.contains("\"a\\\"b\""), "option quote escaped: {out}");
    }

    #[test]
    fn typescript_collection_output() {
        let col = make_col(
            "posts",
            vec![
                text_field("title", true),
                text_field("content", false),
                select_field("status", &["draft", "published"]),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("export interface PostsData {"));
        assert!(out.contains("  title: string;"));
        assert!(out.contains("  content?: string;"));
        assert!(out.contains("  status: \"draft\" | \"published\";"));
        assert!(out.contains("export interface PostsDocument {"));
        assert!(out.contains("  id: string;"));
        assert!(out.contains("  created_at?: string;"));
        assert!(out.contains("  updated_at?: string;"));
    }

    #[test]
    fn typescript_global_output() {
        let mut global = GlobalDefinition::new("site_settings");
        global.fields = vec![text_field("site_name", true)];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(out.contains("export interface SiteSettingsData {"));
        assert!(out.contains("export interface SiteSettingsDocument {"));
    }

    #[test]
    fn typescript_relationship_has_many() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("tags", FieldType::Relationship)
                    .relationship(RelationshipConfig::new("tags", true))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("tags?: (string | TagsDocument)[];"),
            "got: {out}"
        );
    }

    #[test]
    fn typescript_polymorphic_has_one() {
        let mut rc = RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".into(), "pages".into()];
        let col = make_col(
            "comments",
            vec![
                FieldDefinition::builder("subject", FieldType::Relationship)
                    .required(true)
                    .relationship(rc)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Poly has-one = id string OR any target doc; optional on read.
        assert!(
            out.contains("  subject?: string | PostsDocument | PagesDocument;"),
            "poly has-one union: {out}"
        );
        assert!(out.contains("Polymorphic relationship"), "comment: {out}");
    }

    #[test]
    fn typescript_polymorphic_has_many() {
        let mut rc = RelationshipConfig::new("articles", true);
        rc.polymorphic = vec!["articles".into(), "videos".into()];
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("related", FieldType::Relationship)
                    .has_many(true)
                    .relationship(rc)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("  related?: (string | ArticlesDocument | VideosDocument)[];"),
            "poly has-many union array: {out}"
        );
        assert!(out.contains("Polymorphic relationship"), "comment: {out}");
    }

    #[test]
    fn typescript_relationship_has_one() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("author", FieldType::Relationship)
                    .required(true)
                    .relationship(RelationshipConfig::new("users", false))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Single relationship is optional on read (populate can null it).
        assert!(
            out.contains("  author?: string | UsersDocument;"),
            "got: {out}"
        );
    }

    #[test]
    fn typescript_number_checkbox_json_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("price", FieldType::Number)
                    .required(true)
                    .build(),
                FieldDefinition::builder("active", FieldType::Checkbox).build(),
                FieldDefinition::builder("meta", FieldType::Json).build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  price: number;"));
        assert!(out.contains("  active?: boolean;"));
        assert!(out.contains("  meta?: unknown;"));
    }

    #[test]
    fn typescript_array_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![text_field("label", true), text_field("value", false)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("export interface PostsItems {"));
        assert!(out.contains("  label?: string | null;"));
        assert!(out.contains("  value?: string | null;"));
        assert!(out.contains("PostsItems[]"));
    }

    /// A relational array's rows carry their junction `id` — read it, and send
    /// it back so an update keeps the row — while a row nested in another row is
    /// JSON without one.
    #[test]
    fn typescript_array_rows_carry_their_id() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![
                        text_field("label", true),
                        FieldDefinition::builder("notes", FieldType::Array)
                            .fields(vec![text_field("body", false)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        let row = interface_block(&out, "export interface PostsItems {");
        assert!(row.contains("  id?: string | null;"), "{row}");
        let input = interface_block(&out, "export interface PostsItemsData {");
        assert!(input.contains("  id?: string;"), "{input}");
        let nested = interface_block(&out, "export interface PostsItemsNotes {");
        assert!(!nested.contains("id?"), "{nested}");
    }

    #[test]
    fn typescript_nested_group_in_array_uses_compound_pascal() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![
                        FieldDefinition::builder("meta", FieldType::Group)
                            .fields(vec![text_field("title", true)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("export interface PostsItemsMeta {"),
            "nested group compound pascal: {out}"
        );
        assert!(
            out.contains("PostsItemsMeta | null;"),
            "body references it: {out}"
        );
        assert!(!out.contains("PostsMeta"), "no wrong name: {out}");
    }

    #[test]
    fn typescript_array_without_subfields() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("data", FieldType::Array).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Record<string, unknown>[]"));
    }

    #[test]
    fn typescript_group_field_empty() {
        let col = make_col(
            "items",
            vec![FieldDefinition::builder("seo", FieldType::Group).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Record<string, unknown>"));
    }

    #[test]
    fn typescript_group_field_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("seo", FieldType::Group)
                    .fields(vec![
                        text_field("title", true),
                        text_field("description", false),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("export interface PostsSeo {"),
            "sub-type: {out}"
        );
        assert!(out.contains("  title?: string | null;"), "sub-field: {out}");
        assert!(
            out.contains("  description?: string | null;"),
            "optional sub: {out}"
        );
        assert!(out.contains("PostsSeo"), "reference: {out}");
    }

    #[test]
    fn typescript_blocks_field() {
        let mut bd = BlockDefinition::new("text", vec![text_field("body", true)]);
        bd.label = Some(LocalizedString::Plain("Text".to_string()));
        let col = make_col(
            "pages",
            vec![
                FieldDefinition::builder("content", FieldType::Blocks)
                    .blocks(vec![bd])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Record<string, unknown>[]"));
    }

    #[test]
    fn typescript_upload_field() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("image", FieldType::Upload)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Single upload is optional on read.
        assert!(out.contains("  image?: string;"), "got: {out}");
    }

    #[test]
    fn upload_has_many_generates_array_type() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("images", FieldType::Upload)
                    .required(true)
                    .relationship(RelationshipConfig::new("", true))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("  images: string[];"),
            "has-many upload: {out}"
        );
    }

    #[test]
    fn typescript_select_without_options() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("category", FieldType::Select)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  category: string;"));
    }

    #[test]
    fn typescript_collection_slug_type() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        registry.register_collection(make_col("pages", vec![text_field("body", true)]));
        let out = render(&registry);
        assert!(out.contains("export type CollectionSlug = \"pages\" | \"posts\";"));
    }

    #[test]
    fn typescript_collection_slug_type_empty() {
        let registry = Registry::new();
        let out = render(&registry);
        assert!(!out.contains("CollectionSlug"));
    }

    #[test]
    fn typescript_no_timestamps() {
        let mut col = make_col("tags", vec![text_field("name", true)]);
        col.timestamps = false;
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(!out.contains("created_at"));
        assert!(!out.contains("updated_at"));
    }

    #[test]
    fn typescript_text_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("tags", FieldType::Text)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("labels", FieldType::Text)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  tags: string[];"), "required: {out}");
        assert!(out.contains("  labels?: string[];"), "optional: {out}");
    }

    #[test]
    fn typescript_number_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("scores", FieldType::Number)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("weights", FieldType::Number)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  scores: number[];"), "required: {out}");
        assert!(out.contains("  weights?: number[];"), "optional: {out}");
    }

    #[test]
    fn typescript_email_date_richtext_textarea() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("contact", FieldType::Email)
                    .required(true)
                    .build(),
                FieldDefinition::builder("at", FieldType::Date)
                    .required(true)
                    .build(),
                FieldDefinition::builder("body", FieldType::Richtext)
                    .required(true)
                    .build(),
                FieldDefinition::builder("notes", FieldType::Textarea)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  contact: string;"));
        assert!(out.contains("  at: string;"));
        assert!(out.contains("  body: string;"));
        assert!(out.contains("  notes: string;"));
    }

    #[test]
    fn typescript_code_join_radio_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("snippet", FieldType::Code)
                    .required(true)
                    .build(),
                FieldDefinition::builder("refs", FieldType::Join).build(),
                FieldDefinition::builder("color", FieldType::Radio)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  snippet: string;"), "code → string: {out}");
        assert!(
            out.contains("  refs?: Record<string, unknown>[];"),
            "join → Record[]: {out}"
        );
        assert!(out.contains("  color: string;"), "radio no-options: {out}");
    }

    #[test]
    fn typescript_select_has_many_with_options() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("tags", FieldType::Select)
                    .has_many(true)
                    .required(true)
                    .options(vec![
                        SelectOption::new(LocalizedString::Plain("A".into()), "a"),
                        SelectOption::new(LocalizedString::Plain("B".into()), "b"),
                    ])
                    .build(),
                FieldDefinition::builder("cats", FieldType::Select)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("(\"a\" | \"b\")[]"), "union array: {out}");
        assert!(out.contains("string[]"), "no-options → string[]: {out}");
    }

    #[test]
    fn typescript_radio_has_many_with_options() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("sizes", FieldType::Radio)
                    .has_many(true)
                    .required(true)
                    .options(vec![
                        SelectOption::new(LocalizedString::Plain("S".into()), "s"),
                        SelectOption::new(LocalizedString::Plain("L".into()), "l"),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("(\"s\" | \"l\")[]"),
            "radio union array: {out}"
        );
    }

    #[test]
    fn typescript_row_collapsible_tabs_promote_subfields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("layout_row", FieldType::Row)
                    .fields(vec![
                        text_field("first_name", true),
                        text_field("last_name", false),
                    ])
                    .build(),
                FieldDefinition::builder("details", FieldType::Collapsible)
                    .fields(vec![text_field("bio", false)])
                    .build(),
                FieldDefinition::builder("sections", FieldType::Tabs)
                    .tabs(vec![FieldTab::new(
                        "Tab1",
                        vec![text_field("tab_field", true)],
                    )])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(!out.contains("layout_row:"), "row name not a key: {out}");
        assert!(
            out.contains("  first_name: string;"),
            "row sub promoted: {out}"
        );
        assert!(
            out.contains("  last_name?: string;"),
            "row optional sub: {out}"
        );
        assert!(
            !out.contains("details:"),
            "collapsible name not a key: {out}"
        );
        assert!(out.contains("  bio?: string;"), "collapsible sub: {out}");
        assert!(!out.contains("sections:"), "tabs name not a key: {out}");
        assert!(out.contains("  tab_field: string;"), "tabs sub: {out}");
    }

    #[test]
    fn typescript_array_nested_in_row() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("layout", FieldType::Row)
                    .fields(vec![
                        FieldDefinition::builder("items", FieldType::Array)
                            .fields(vec![text_field("label", true)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("export interface PostsItems {"),
            "sub-type: {out}"
        );
        assert!(out.contains("PostsItems[]"), "reference: {out}");
    }

    #[test]
    fn typescript_global_with_subtypes() {
        let mut global = GlobalDefinition::new("settings");
        global.fields = vec![
            FieldDefinition::builder("nav", FieldType::Array)
                .fields(vec![text_field("label", true), text_field("url", true)])
                .build(),
            FieldDefinition::builder("seo", FieldType::Group)
                .fields(vec![text_field("title", true)])
                .build(),
        ];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(
            out.contains("export interface SettingsNav {"),
            "array sub: {out}"
        );
        assert!(
            out.contains("export interface SettingsSeo {"),
            "group sub: {out}"
        );
    }

    #[test]
    fn typescript_full_render_with_globals() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        let mut settings = GlobalDefinition::new("settings");
        settings.fields = vec![text_field("name", true)];
        registry.register_global(settings);
        let out = render(&registry);
        assert!(out.contains("Auto-generated"));
        assert!(out.contains("export interface PostsData {"));
        assert!(out.contains("export interface SettingsData {"));
        assert!(out.contains("export interface SettingsDocument {"));
        assert!(out.contains("export type CollectionSlug = \"posts\";"));
    }
}
