---@meta
-- Auto-generated by crap-cms. Do not edit.

---@class crap.group.CategoriesSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.Categories
---@field id? string
---@field title string
---@field slug string
---@field description? string
---@field parent? string
---@field color? string
---@field seo? crap.group.CategoriesSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Categories
---@field title? string
---@field slug? string
---@field description? string
---@field parent? string
---@field color? string
---@field seo? crap.group.CategoriesSeo

---@class crap.doc.Categories : crap.Document
---@field id string
---@field title string
---@field slug string
---@field description? string
---@field parent? string
---@field color? string
---@field seo? crap.group.CategoriesSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Categories
---@field collection "categories"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Categories
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Categories : crap.FindResult
---@field documents crap.doc.Categories[]

---@alias crap.hook_fn.Categories fun(ctx: crap.hook.Categories): crap.hook.Categories

---@class crap.field_hook.Categories
---@field field_name string
---@field collection "categories"
---@field operation string
---@field data crap.data.Categories
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Categories
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field description? crap.FilterValue
---@field parent? crap.FilterValue
---@field color? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Categories : crap.FindQuery
---@field where? crap.where.Categories
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"description"|"-description"|"parent"|"-parent"|"color"|"-color"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Categories
local _coll_categories = {}

---@param query? crap.query.Categories
---@return crap.find_result.Categories
function _coll_categories.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Categories?
function _coll_categories.find_by_id(id, opts) end

---@param data crap.data.Categories
---@param opts? crap.CreateOptions
---@return crap.doc.Categories
function _coll_categories.create(data, opts) end

---@param id string
---@param data crap.partial.Categories
---@param opts? crap.UpdateOptions
---@return crap.doc.Categories
function _coll_categories.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_categories.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Categories
function _coll_categories.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_categories.undelete(id, opts) end

---@param data crap.data.Categories
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_categories.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_categories.count(query) end

---@param items crap.data.Categories[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_categories.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Categories
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_categories.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_categories.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_categories.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Categories
function _coll_categories.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_categories.ref_count(id) end

crap.collections.categories = _coll_categories

---@class crap.group.ClientsSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.Clients
---@field id? string
---@field company_name string
---@field logo? string
---@field website? string
---@field since? string
---@field contact_name? string
---@field contact_email? string
---@field contact_phone? string
---@field industry? "technology" | "finance" | "healthcare" | "education" | "retail" | "media" | "nonprofit" | "government"
---@field notes? string
---@field client_projects? table[]
---@field seo? crap.group.ClientsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Clients
---@field company_name? string
---@field logo? string
---@field website? string
---@field since? string
---@field contact_name? string
---@field contact_email? string
---@field contact_phone? string
---@field industry? "technology" | "finance" | "healthcare" | "education" | "retail" | "media" | "nonprofit" | "government"
---@field notes? string
---@field client_projects? table[]
---@field seo? crap.group.ClientsSeo

---@class crap.doc.Clients : crap.Document
---@field id string
---@field company_name string
---@field logo? string
---@field website? string
---@field since? string
---@field contact_name? string
---@field contact_email? string
---@field contact_phone? string
---@field industry? "technology" | "finance" | "healthcare" | "education" | "retail" | "media" | "nonprofit" | "government"
---@field notes? string
---@field client_projects? table[]
---@field seo? crap.group.ClientsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Clients
---@field collection "clients"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Clients
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Clients : crap.FindResult
---@field documents crap.doc.Clients[]

---@alias crap.hook_fn.Clients fun(ctx: crap.hook.Clients): crap.hook.Clients

---@class crap.field_hook.Clients
---@field field_name string
---@field collection "clients"
---@field operation string
---@field data crap.data.Clients
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Clients
---@field id? crap.FilterValue
---@field company_name? crap.FilterValue
---@field logo? crap.FilterValue
---@field website? crap.FilterValue
---@field since? crap.FilterValue
---@field contact_name? crap.FilterValue
---@field contact_email? crap.FilterValue
---@field contact_phone? crap.FilterValue
---@field industry? crap.FilterValue
---@field notes? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Clients : crap.FindQuery
---@field where? crap.where.Clients
---@field order_by? "id"|"-id"|"company_name"|"-company_name"|"logo"|"-logo"|"website"|"-website"|"since"|"-since"|"contact_name"|"-contact_name"|"contact_email"|"-contact_email"|"contact_phone"|"-contact_phone"|"industry"|"-industry"|"notes"|"-notes"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Clients
local _coll_clients = {}

---@param query? crap.query.Clients
---@return crap.find_result.Clients
function _coll_clients.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Clients?
function _coll_clients.find_by_id(id, opts) end

---@param data crap.data.Clients
---@param opts? crap.CreateOptions
---@return crap.doc.Clients
function _coll_clients.create(data, opts) end

---@param id string
---@param data crap.partial.Clients
---@param opts? crap.UpdateOptions
---@return crap.doc.Clients
function _coll_clients.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_clients.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Clients
function _coll_clients.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_clients.undelete(id, opts) end

---@param data crap.data.Clients
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_clients.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_clients.count(query) end

---@param items crap.data.Clients[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_clients.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Clients
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_clients.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_clients.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_clients.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Clients
function _coll_clients.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_clients.ref_count(id) end

crap.collections.clients = _coll_clients

---@class crap.group.EventsLocation
---@field venue_name? string
---@field address? string
---@field city? string
---@field country? string

---@class crap.group.EventsSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.Events
---@field id? string
---@field title string
---@field slug string
---@field description? string
---@field hero_image? string
---@field start_date string
---@field end_date? string
---@field online? boolean
---@field event_url? string
---@field location? crap.group.EventsLocation
---@field speakers? string[]
---@field categories? string[]
---@field registration_url? string
---@field max_attendees? number
---@field registration_deadline? string
---@field seo? crap.group.EventsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Events
---@field title? string
---@field slug? string
---@field description? string
---@field hero_image? string
---@field start_date? string
---@field end_date? string
---@field online? boolean
---@field event_url? string
---@field location? crap.group.EventsLocation
---@field speakers? string[]
---@field categories? string[]
---@field registration_url? string
---@field max_attendees? number
---@field registration_deadline? string
---@field seo? crap.group.EventsSeo

---@class crap.doc.Events : crap.Document
---@field id string
---@field title string
---@field slug string
---@field description? string
---@field hero_image? string
---@field start_date string
---@field end_date? string
---@field online? boolean
---@field event_url? string
---@field location? crap.group.EventsLocation
---@field speakers? string[]
---@field categories? string[]
---@field registration_url? string
---@field max_attendees? number
---@field registration_deadline? string
---@field seo? crap.group.EventsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Events
---@field collection "events"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Events
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Events : crap.FindResult
---@field documents crap.doc.Events[]

---@alias crap.hook_fn.Events fun(ctx: crap.hook.Events): crap.hook.Events

---@class crap.field_hook.Events
---@field field_name string
---@field collection "events"
---@field operation string
---@field data crap.data.Events
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Events
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field description? crap.FilterValue
---@field hero_image? crap.FilterValue
---@field start_date? crap.FilterValue
---@field start_date_tz? crap.FilterValue
---@field end_date? crap.FilterValue
---@field end_date_tz? crap.FilterValue
---@field online? crap.FilterValue
---@field event_url? crap.FilterValue
---@field location__venue_name? crap.FilterValue
---@field location__address? crap.FilterValue
---@field location__city? crap.FilterValue
---@field location__country? crap.FilterValue
---@field registration_url? crap.FilterValue
---@field max_attendees? crap.FilterValue
---@field registration_deadline? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Events : crap.FindQuery
---@field where? crap.where.Events
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"description"|"-description"|"hero_image"|"-hero_image"|"start_date"|"-start_date"|"start_date_tz"|"-start_date_tz"|"end_date"|"-end_date"|"end_date_tz"|"-end_date_tz"|"online"|"-online"|"event_url"|"-event_url"|"location__venue_name"|"-location__venue_name"|"location__address"|"-location__address"|"location__city"|"-location__city"|"location__country"|"-location__country"|"registration_url"|"-registration_url"|"max_attendees"|"-max_attendees"|"registration_deadline"|"-registration_deadline"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Events
local _coll_events = {}

---@param query? crap.query.Events
---@return crap.find_result.Events
function _coll_events.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Events?
function _coll_events.find_by_id(id, opts) end

---@param data crap.data.Events
---@param opts? crap.CreateOptions
---@return crap.doc.Events
function _coll_events.create(data, opts) end

---@param id string
---@param data crap.partial.Events
---@param opts? crap.UpdateOptions
---@return crap.doc.Events
function _coll_events.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_events.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Events
function _coll_events.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_events.undelete(id, opts) end

---@param data crap.data.Events
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_events.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_events.count(query) end

---@param items crap.data.Events[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_events.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Events
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_events.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_events.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_events.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Events
function _coll_events.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_events.ref_count(id) end

crap.collections.events = _coll_events

---@class crap.data.Inquiries
---@field id? string
---@field name string
---@field email string
---@field company? string
---@field phone? string
---@field service? string
---@field budget_range? "under_5k" | "5k_15k" | "15k_50k" | "50k_100k" | "over_100k"
---@field message string
---@field status "new" | "contacted" | "qualified" | "proposal" | "won" | "lost" | "archived"
---@field assigned_to? string
---@field internal_notes? string
---@field metadata? any
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Inquiries
---@field name? string
---@field email? string
---@field company? string
---@field phone? string
---@field service? string
---@field budget_range? "under_5k" | "5k_15k" | "15k_50k" | "50k_100k" | "over_100k"
---@field message? string
---@field status? "new" | "contacted" | "qualified" | "proposal" | "won" | "lost" | "archived"
---@field assigned_to? string
---@field internal_notes? string
---@field metadata? any

---@class crap.doc.Inquiries : crap.Document
---@field id string
---@field name string
---@field email string
---@field company? string
---@field phone? string
---@field service? string
---@field budget_range? "under_5k" | "5k_15k" | "15k_50k" | "50k_100k" | "over_100k"
---@field message string
---@field status "new" | "contacted" | "qualified" | "proposal" | "won" | "lost" | "archived"
---@field assigned_to? string
---@field internal_notes? string
---@field metadata? any
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Inquiries
---@field collection "inquiries"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Inquiries
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Inquiries : crap.FindResult
---@field documents crap.doc.Inquiries[]

---@alias crap.hook_fn.Inquiries fun(ctx: crap.hook.Inquiries): crap.hook.Inquiries

---@class crap.field_hook.Inquiries
---@field field_name string
---@field collection "inquiries"
---@field operation string
---@field data crap.data.Inquiries
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Inquiries
---@field id? crap.FilterValue
---@field name? crap.FilterValue
---@field email? crap.FilterValue
---@field company? crap.FilterValue
---@field phone? crap.FilterValue
---@field service? crap.FilterValue
---@field budget_range? crap.FilterValue
---@field message? crap.FilterValue
---@field status? crap.FilterValue
---@field assigned_to? crap.FilterValue
---@field internal_notes? crap.FilterValue
---@field metadata? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Inquiries : crap.FindQuery
---@field where? crap.where.Inquiries
---@field order_by? "id"|"-id"|"name"|"-name"|"email"|"-email"|"company"|"-company"|"phone"|"-phone"|"service"|"-service"|"budget_range"|"-budget_range"|"message"|"-message"|"status"|"-status"|"assigned_to"|"-assigned_to"|"internal_notes"|"-internal_notes"|"metadata"|"-metadata"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Inquiries
local _coll_inquiries = {}

---@param query? crap.query.Inquiries
---@return crap.find_result.Inquiries
function _coll_inquiries.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Inquiries?
function _coll_inquiries.find_by_id(id, opts) end

---@param data crap.data.Inquiries
---@param opts? crap.CreateOptions
---@return crap.doc.Inquiries
function _coll_inquiries.create(data, opts) end

---@param id string
---@param data crap.partial.Inquiries
---@param opts? crap.UpdateOptions
---@return crap.doc.Inquiries
function _coll_inquiries.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_inquiries.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Inquiries
function _coll_inquiries.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_inquiries.undelete(id, opts) end

---@param data crap.data.Inquiries
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_inquiries.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_inquiries.count(query) end

---@param items crap.data.Inquiries[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_inquiries.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Inquiries
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_inquiries.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_inquiries.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_inquiries.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Inquiries
function _coll_inquiries.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_inquiries.ref_count(id) end

crap.collections.inquiries = _coll_inquiries

---@class crap.data.Media
---@field id? string
---@field filename string
---@field mime_type? string
---@field filesize? number
---@field width? number
---@field height? number
---@field url? string
---@field focal_x? number
---@field focal_y? number
---@field thumbnail_url? string
---@field thumbnail_width? number
---@field thumbnail_height? number
---@field thumbnail_webp_url? string
---@field thumbnail_avif_url? string
---@field card_url? string
---@field card_width? number
---@field card_height? number
---@field card_webp_url? string
---@field card_avif_url? string
---@field hero_url? string
---@field hero_width? number
---@field hero_height? number
---@field hero_webp_url? string
---@field hero_avif_url? string
---@field og_url? string
---@field og_width? number
---@field og_height? number
---@field og_webp_url? string
---@field og_avif_url? string
---@field alt string
---@field caption? string
---@field credit? string
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Media
---@field filename? string
---@field mime_type? string
---@field filesize? number
---@field width? number
---@field height? number
---@field url? string
---@field focal_x? number
---@field focal_y? number
---@field thumbnail_url? string
---@field thumbnail_width? number
---@field thumbnail_height? number
---@field thumbnail_webp_url? string
---@field thumbnail_avif_url? string
---@field card_url? string
---@field card_width? number
---@field card_height? number
---@field card_webp_url? string
---@field card_avif_url? string
---@field hero_url? string
---@field hero_width? number
---@field hero_height? number
---@field hero_webp_url? string
---@field hero_avif_url? string
---@field og_url? string
---@field og_width? number
---@field og_height? number
---@field og_webp_url? string
---@field og_avif_url? string
---@field alt? string
---@field caption? string
---@field credit? string

---@class crap.doc.Media : crap.Document
---@field id string
---@field filename string
---@field mime_type? string
---@field filesize? number
---@field width? number
---@field height? number
---@field url? string
---@field focal_x? number
---@field focal_y? number
---@field thumbnail_url? string
---@field thumbnail_width? number
---@field thumbnail_height? number
---@field thumbnail_webp_url? string
---@field thumbnail_avif_url? string
---@field card_url? string
---@field card_width? number
---@field card_height? number
---@field card_webp_url? string
---@field card_avif_url? string
---@field hero_url? string
---@field hero_width? number
---@field hero_height? number
---@field hero_webp_url? string
---@field hero_avif_url? string
---@field og_url? string
---@field og_width? number
---@field og_height? number
---@field og_webp_url? string
---@field og_avif_url? string
---@field alt string
---@field caption? string
---@field credit? string
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Media
---@field collection "media"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Media
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Media : crap.FindResult
---@field documents crap.doc.Media[]

---@alias crap.hook_fn.Media fun(ctx: crap.hook.Media): crap.hook.Media

---@class crap.field_hook.Media
---@field field_name string
---@field collection "media"
---@field operation string
---@field data crap.data.Media
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Media
---@field id? crap.FilterValue
---@field filename? crap.FilterValue
---@field mime_type? crap.FilterValue
---@field filesize? crap.FilterValue
---@field width? crap.FilterValue
---@field height? crap.FilterValue
---@field url? crap.FilterValue
---@field focal_x? crap.FilterValue
---@field focal_y? crap.FilterValue
---@field thumbnail_url? crap.FilterValue
---@field thumbnail_width? crap.FilterValue
---@field thumbnail_height? crap.FilterValue
---@field thumbnail_webp_url? crap.FilterValue
---@field thumbnail_avif_url? crap.FilterValue
---@field card_url? crap.FilterValue
---@field card_width? crap.FilterValue
---@field card_height? crap.FilterValue
---@field card_webp_url? crap.FilterValue
---@field card_avif_url? crap.FilterValue
---@field hero_url? crap.FilterValue
---@field hero_width? crap.FilterValue
---@field hero_height? crap.FilterValue
---@field hero_webp_url? crap.FilterValue
---@field hero_avif_url? crap.FilterValue
---@field og_url? crap.FilterValue
---@field og_width? crap.FilterValue
---@field og_height? crap.FilterValue
---@field og_webp_url? crap.FilterValue
---@field og_avif_url? crap.FilterValue
---@field alt? crap.FilterValue
---@field caption? crap.FilterValue
---@field credit? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Media : crap.FindQuery
---@field where? crap.where.Media
---@field order_by? "id"|"-id"|"filename"|"-filename"|"mime_type"|"-mime_type"|"filesize"|"-filesize"|"width"|"-width"|"height"|"-height"|"url"|"-url"|"focal_x"|"-focal_x"|"focal_y"|"-focal_y"|"thumbnail_url"|"-thumbnail_url"|"thumbnail_width"|"-thumbnail_width"|"thumbnail_height"|"-thumbnail_height"|"thumbnail_webp_url"|"-thumbnail_webp_url"|"thumbnail_avif_url"|"-thumbnail_avif_url"|"card_url"|"-card_url"|"card_width"|"-card_width"|"card_height"|"-card_height"|"card_webp_url"|"-card_webp_url"|"card_avif_url"|"-card_avif_url"|"hero_url"|"-hero_url"|"hero_width"|"-hero_width"|"hero_height"|"-hero_height"|"hero_webp_url"|"-hero_webp_url"|"hero_avif_url"|"-hero_avif_url"|"og_url"|"-og_url"|"og_width"|"-og_width"|"og_height"|"-og_height"|"og_webp_url"|"-og_webp_url"|"og_avif_url"|"-og_avif_url"|"alt"|"-alt"|"caption"|"-caption"|"credit"|"-credit"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Media
local _coll_media = {}

---@param query? crap.query.Media
---@return crap.find_result.Media
function _coll_media.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Media?
function _coll_media.find_by_id(id, opts) end

---@param data crap.data.Media
---@param opts? crap.CreateOptions
---@return crap.doc.Media
function _coll_media.create(data, opts) end

---@param id string
---@param data crap.partial.Media
---@param opts? crap.UpdateOptions
---@return crap.doc.Media
function _coll_media.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_media.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Media
function _coll_media.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_media.undelete(id, opts) end

---@param data crap.data.Media
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_media.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_media.count(query) end

---@param items crap.data.Media[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_media.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Media
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_media.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_media.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_media.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Media
function _coll_media.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_media.ref_count(id) end

crap.collections.media = _coll_media

---@class crap.data.Pages
---@field id? string
---@field title string
---@field slug string
---@field content? table[]
---@field parent? string
---@field template? "default" | "full_width" | "landing" | "sidebar"
---@field show_in_nav? boolean
---@field nav_order? number
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Pages
---@field title? string
---@field slug? string
---@field content? table[]
---@field parent? string
---@field template? "default" | "full_width" | "landing" | "sidebar"
---@field show_in_nav? boolean
---@field nav_order? number

---@class crap.doc.Pages : crap.Document
---@field id string
---@field title string
---@field slug string
---@field content? table[]
---@field parent? string
---@field template? "default" | "full_width" | "landing" | "sidebar"
---@field show_in_nav? boolean
---@field nav_order? number
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Pages
---@field collection "pages"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Pages
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Pages : crap.FindResult
---@field documents crap.doc.Pages[]

---@alias crap.hook_fn.Pages fun(ctx: crap.hook.Pages): crap.hook.Pages

---@class crap.field_hook.Pages
---@field field_name string
---@field collection "pages"
---@field operation string
---@field data crap.data.Pages
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Pages
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field parent? crap.FilterValue
---@field template? crap.FilterValue
---@field show_in_nav? crap.FilterValue
---@field nav_order? crap.FilterValue
---@field _status? crap.FilterValue
---@field _deleted_at? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Pages : crap.FindQuery
---@field where? crap.where.Pages
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"parent"|"-parent"|"template"|"-template"|"show_in_nav"|"-show_in_nav"|"nav_order"|"-nav_order"|"_status"|"-_status"|"_deleted_at"|"-_deleted_at"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Pages
local _coll_pages = {}

---@param query? crap.query.Pages
---@return crap.find_result.Pages
function _coll_pages.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Pages?
function _coll_pages.find_by_id(id, opts) end

---@param data crap.data.Pages
---@param opts? crap.CreateOptions
---@return crap.doc.Pages
function _coll_pages.create(data, opts) end

---@param id string
---@param data crap.partial.Pages
---@param opts? crap.UpdateOptions
---@return crap.doc.Pages
function _coll_pages.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_pages.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Pages
function _coll_pages.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_pages.undelete(id, opts) end

---@param data crap.data.Pages
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_pages.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_pages.count(query) end

---@param items crap.data.Pages[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_pages.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Pages
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_pages.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_pages.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_pages.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Pages
function _coll_pages.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_pages.ref_count(id) end

crap.collections.pages = _coll_pages

---@class crap.group.PostsSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.Posts
---@field id? string
---@field title string
---@field slug string
---@field excerpt? string
---@field post_type "article" | "case_study" | "link" | "video"
---@field published_at? string
---@field external_url? string
---@field author string
---@field hero_image? string
---@field categories? string[]
---@field tags? string[]
---@field content? string
---@field reading_time? string
---@field related_content? string[]
---@field featured? boolean
---@field pinned? boolean
---@field seo? crap.group.PostsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Posts
---@field title? string
---@field slug? string
---@field excerpt? string
---@field post_type? "article" | "case_study" | "link" | "video"
---@field published_at? string
---@field external_url? string
---@field author? string
---@field hero_image? string
---@field categories? string[]
---@field tags? string[]
---@field content? string
---@field reading_time? string
---@field related_content? string[]
---@field featured? boolean
---@field pinned? boolean
---@field seo? crap.group.PostsSeo

---@class crap.doc.Posts : crap.Document
---@field id string
---@field title string
---@field slug string
---@field excerpt? string
---@field post_type "article" | "case_study" | "link" | "video"
---@field published_at? string
---@field external_url? string
---@field author string
---@field hero_image? string
---@field categories? string[]
---@field tags? string[]
---@field content? string
---@field reading_time? string
---@field related_content? string[]
---@field featured? boolean
---@field pinned? boolean
---@field seo? crap.group.PostsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Posts
---@field collection "posts"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Posts
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Posts : crap.FindResult
---@field documents crap.doc.Posts[]

---@alias crap.hook_fn.Posts fun(ctx: crap.hook.Posts): crap.hook.Posts

---@class crap.field_hook.Posts
---@field field_name string
---@field collection "posts"
---@field operation string
---@field data crap.data.Posts
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Posts
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field excerpt? crap.FilterValue
---@field post_type? crap.FilterValue
---@field published_at? crap.FilterValue
---@field external_url? crap.FilterValue
---@field author? crap.FilterValue
---@field hero_image? crap.FilterValue
---@field content? crap.FilterValue
---@field reading_time? crap.FilterValue
---@field featured? crap.FilterValue
---@field pinned? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field _status? crap.FilterValue
---@field _deleted_at? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Posts : crap.FindQuery
---@field where? crap.where.Posts
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"excerpt"|"-excerpt"|"post_type"|"-post_type"|"published_at"|"-published_at"|"external_url"|"-external_url"|"author"|"-author"|"hero_image"|"-hero_image"|"content"|"-content"|"reading_time"|"-reading_time"|"featured"|"-featured"|"pinned"|"-pinned"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"_status"|"-_status"|"_deleted_at"|"-_deleted_at"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Posts
local _coll_posts = {}

---@param query? crap.query.Posts
---@return crap.find_result.Posts
function _coll_posts.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Posts?
function _coll_posts.find_by_id(id, opts) end

---@param data crap.data.Posts
---@param opts? crap.CreateOptions
---@return crap.doc.Posts
function _coll_posts.create(data, opts) end

---@param id string
---@param data crap.partial.Posts
---@param opts? crap.UpdateOptions
---@return crap.doc.Posts
function _coll_posts.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_posts.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Posts
function _coll_posts.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_posts.undelete(id, opts) end

---@param data crap.data.Posts
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_posts.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_posts.count(query) end

---@param items crap.data.Posts[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_posts.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Posts
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_posts.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_posts.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_posts.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Posts
function _coll_posts.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_posts.ref_count(id) end

crap.collections.posts = _coll_posts

---@class crap.array_row.ProjectsDeliverables
---@field title string
---@field completed? boolean

---@class crap.group.ProjectsSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.Projects
---@field id? string
---@field title string
---@field slug string
---@field excerpt? string
---@field status "planning" | "in_progress" | "review" | "completed" | "archived"
---@field priority? "low" | "normal" | "high" | "urgent"
---@field featured? boolean
---@field start_date? string
---@field end_date? string
---@field hero_image? string
---@field client? string
---@field team? string[]
---@field categories? string[]
---@field tags? string[]
---@field budget? number
---@field deliverables? crap.array_row.ProjectsDeliverables[]
---@field content? table[]
---@field published_at? string
---@field external_url? string
---@field seo? crap.group.ProjectsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Projects
---@field title? string
---@field slug? string
---@field excerpt? string
---@field status? "planning" | "in_progress" | "review" | "completed" | "archived"
---@field priority? "low" | "normal" | "high" | "urgent"
---@field featured? boolean
---@field start_date? string
---@field end_date? string
---@field hero_image? string
---@field client? string
---@field team? string[]
---@field categories? string[]
---@field tags? string[]
---@field budget? number
---@field deliverables? crap.array_row.ProjectsDeliverables[]
---@field content? table[]
---@field published_at? string
---@field external_url? string
---@field seo? crap.group.ProjectsSeo

---@class crap.doc.Projects : crap.Document
---@field id string
---@field title string
---@field slug string
---@field excerpt? string
---@field status "planning" | "in_progress" | "review" | "completed" | "archived"
---@field priority? "low" | "normal" | "high" | "urgent"
---@field featured? boolean
---@field start_date? string
---@field end_date? string
---@field hero_image? string
---@field client? string
---@field team? string[]
---@field categories? string[]
---@field tags? string[]
---@field budget? number
---@field deliverables? crap.array_row.ProjectsDeliverables[]
---@field content? table[]
---@field published_at? string
---@field external_url? string
---@field seo? crap.group.ProjectsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Projects
---@field collection "projects"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Projects
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Projects : crap.FindResult
---@field documents crap.doc.Projects[]

---@alias crap.hook_fn.Projects fun(ctx: crap.hook.Projects): crap.hook.Projects

---@class crap.field_hook.Projects
---@field field_name string
---@field collection "projects"
---@field operation string
---@field data crap.data.Projects
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Projects
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field excerpt? crap.FilterValue
---@field status? crap.FilterValue
---@field priority? crap.FilterValue
---@field featured? crap.FilterValue
---@field start_date? crap.FilterValue
---@field end_date? crap.FilterValue
---@field hero_image? crap.FilterValue
---@field client? crap.FilterValue
---@field budget? crap.FilterValue
---@field published_at? crap.FilterValue
---@field external_url? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field _status? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Projects : crap.FindQuery
---@field where? crap.where.Projects
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"excerpt"|"-excerpt"|"status"|"-status"|"priority"|"-priority"|"featured"|"-featured"|"start_date"|"-start_date"|"end_date"|"-end_date"|"hero_image"|"-hero_image"|"client"|"-client"|"budget"|"-budget"|"published_at"|"-published_at"|"external_url"|"-external_url"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"_status"|"-_status"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Projects
local _coll_projects = {}

---@param query? crap.query.Projects
---@return crap.find_result.Projects
function _coll_projects.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Projects?
function _coll_projects.find_by_id(id, opts) end

---@param data crap.data.Projects
---@param opts? crap.CreateOptions
---@return crap.doc.Projects
function _coll_projects.create(data, opts) end

---@param id string
---@param data crap.partial.Projects
---@param opts? crap.UpdateOptions
---@return crap.doc.Projects
function _coll_projects.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_projects.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Projects
function _coll_projects.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_projects.undelete(id, opts) end

---@param data crap.data.Projects
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_projects.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_projects.count(query) end

---@param items crap.data.Projects[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_projects.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Projects
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_projects.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_projects.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_projects.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Projects
function _coll_projects.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_projects.ref_count(id) end

crap.collections.projects = _coll_projects

---@class crap.group.ServicesPriceRange
---@field min_price? number
---@field max_price? number
---@field currency? "USD" | "EUR" | "GBP"

---@class crap.array_row.ServicesFeatures
---@field title string
---@field included? boolean

---@class crap.group.ServicesSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.Services
---@field id? string
---@field title string
---@field slug string
---@field description? string
---@field icon? string
---@field active? boolean
---@field sort_order? number
---@field pricing_type "fixed" | "hourly" | "custom"
---@field price_range? crap.group.ServicesPriceRange
---@field features? crap.array_row.ServicesFeatures[]
---@field hero_image? string
---@field seo? crap.group.ServicesSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Services
---@field title? string
---@field slug? string
---@field description? string
---@field icon? string
---@field active? boolean
---@field sort_order? number
---@field pricing_type? "fixed" | "hourly" | "custom"
---@field price_range? crap.group.ServicesPriceRange
---@field features? crap.array_row.ServicesFeatures[]
---@field hero_image? string
---@field seo? crap.group.ServicesSeo

---@class crap.doc.Services : crap.Document
---@field id string
---@field title string
---@field slug string
---@field description? string
---@field icon? string
---@field active? boolean
---@field sort_order? number
---@field pricing_type "fixed" | "hourly" | "custom"
---@field price_range? crap.group.ServicesPriceRange
---@field features? crap.array_row.ServicesFeatures[]
---@field hero_image? string
---@field seo? crap.group.ServicesSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Services
---@field collection "services"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Services
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Services : crap.FindResult
---@field documents crap.doc.Services[]

---@alias crap.hook_fn.Services fun(ctx: crap.hook.Services): crap.hook.Services

---@class crap.field_hook.Services
---@field field_name string
---@field collection "services"
---@field operation string
---@field data crap.data.Services
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Services
---@field id? crap.FilterValue
---@field title? crap.FilterValue
---@field slug? crap.FilterValue
---@field description? crap.FilterValue
---@field icon? crap.FilterValue
---@field active? crap.FilterValue
---@field sort_order? crap.FilterValue
---@field pricing_type? crap.FilterValue
---@field price_range__min_price? crap.FilterValue
---@field price_range__max_price? crap.FilterValue
---@field price_range__currency? crap.FilterValue
---@field hero_image? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Services : crap.FindQuery
---@field where? crap.where.Services
---@field order_by? "id"|"-id"|"title"|"-title"|"slug"|"-slug"|"description"|"-description"|"icon"|"-icon"|"active"|"-active"|"sort_order"|"-sort_order"|"pricing_type"|"-pricing_type"|"price_range__min_price"|"-price_range__min_price"|"price_range__max_price"|"-price_range__max_price"|"price_range__currency"|"-price_range__currency"|"hero_image"|"-hero_image"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Services
local _coll_services = {}

---@param query? crap.query.Services
---@return crap.find_result.Services
function _coll_services.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Services?
function _coll_services.find_by_id(id, opts) end

---@param data crap.data.Services
---@param opts? crap.CreateOptions
---@return crap.doc.Services
function _coll_services.create(data, opts) end

---@param id string
---@param data crap.partial.Services
---@param opts? crap.UpdateOptions
---@return crap.doc.Services
function _coll_services.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_services.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Services
function _coll_services.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_services.undelete(id, opts) end

---@param data crap.data.Services
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_services.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_services.count(query) end

---@param items crap.data.Services[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_services.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Services
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_services.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_services.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_services.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Services
function _coll_services.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_services.ref_count(id) end

crap.collections.services = _coll_services

---@class crap.group.TagsSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.Tags
---@field id? string
---@field name string
---@field slug string
---@field tag_type "topic" | "technology" | "industry" | "skill"
---@field seo? crap.group.TagsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Tags
---@field name? string
---@field slug? string
---@field tag_type? "topic" | "technology" | "industry" | "skill"
---@field seo? crap.group.TagsSeo

---@class crap.doc.Tags : crap.Document
---@field id string
---@field name string
---@field slug string
---@field tag_type "topic" | "technology" | "industry" | "skill"
---@field seo? crap.group.TagsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Tags
---@field collection "tags"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Tags
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Tags : crap.FindResult
---@field documents crap.doc.Tags[]

---@alias crap.hook_fn.Tags fun(ctx: crap.hook.Tags): crap.hook.Tags

---@class crap.field_hook.Tags
---@field field_name string
---@field collection "tags"
---@field operation string
---@field data crap.data.Tags
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Tags
---@field id? crap.FilterValue
---@field name? crap.FilterValue
---@field slug? crap.FilterValue
---@field tag_type? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Tags : crap.FindQuery
---@field where? crap.where.Tags
---@field order_by? "id"|"-id"|"name"|"-name"|"slug"|"-slug"|"tag_type"|"-tag_type"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Tags
local _coll_tags = {}

---@param query? crap.query.Tags
---@return crap.find_result.Tags
function _coll_tags.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Tags?
function _coll_tags.find_by_id(id, opts) end

---@param data crap.data.Tags
---@param opts? crap.CreateOptions
---@return crap.doc.Tags
function _coll_tags.create(data, opts) end

---@param id string
---@param data crap.partial.Tags
---@param opts? crap.UpdateOptions
---@return crap.doc.Tags
function _coll_tags.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_tags.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Tags
function _coll_tags.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_tags.undelete(id, opts) end

---@param data crap.data.Tags
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_tags.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_tags.count(query) end

---@param items crap.data.Tags[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_tags.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Tags
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_tags.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_tags.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_tags.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Tags
function _coll_tags.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_tags.ref_count(id) end

crap.collections.tags = _coll_tags

---@class crap.array_row.TestNestingTabbedItems
---@field title string
---@field description? string
---@field color? "red" | "blue" | "green"
---@field featured? boolean

---@class crap.array_row.TestNestingCoordinates
---@field x number
---@field y number
---@field z? number
---@field label? string

---@class crap.array_row.TestNestingFaqItems
---@field question string
---@field answer? string
---@field source_url? string

---@class crap.array_row.TestNestingTeamMembers
---@field first_name string
---@field last_name string
---@field email? string
---@field job_title? string
---@field linkedin? string
---@field github? string

---@class crap.group.TestNestingSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.TestNesting
---@field id? string
---@field name string
---@field tabbed_items? crap.array_row.TestNestingTabbedItems[]
---@field coordinates? crap.array_row.TestNestingCoordinates[]
---@field faq_items? crap.array_row.TestNestingFaqItems[]
---@field team_members? crap.array_row.TestNestingTeamMembers[]
---@field sections? table[]
---@field theme? "light" | "dark"
---@field layout? "grid" | "list"
---@field custom_config? any
---@field custom_css? string
---@field seo? crap.group.TestNestingSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.TestNesting
---@field name? string
---@field tabbed_items? crap.array_row.TestNestingTabbedItems[]
---@field coordinates? crap.array_row.TestNestingCoordinates[]
---@field faq_items? crap.array_row.TestNestingFaqItems[]
---@field team_members? crap.array_row.TestNestingTeamMembers[]
---@field sections? table[]
---@field theme? "light" | "dark"
---@field layout? "grid" | "list"
---@field custom_config? any
---@field custom_css? string
---@field seo? crap.group.TestNestingSeo

---@class crap.doc.TestNesting : crap.Document
---@field id string
---@field name string
---@field tabbed_items? crap.array_row.TestNestingTabbedItems[]
---@field coordinates? crap.array_row.TestNestingCoordinates[]
---@field faq_items? crap.array_row.TestNestingFaqItems[]
---@field team_members? crap.array_row.TestNestingTeamMembers[]
---@field sections? table[]
---@field theme? "light" | "dark"
---@field layout? "grid" | "list"
---@field custom_config? any
---@field custom_css? string
---@field seo? crap.group.TestNestingSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.TestNesting
---@field collection "test_nesting"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.TestNesting
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.TestNesting : crap.FindResult
---@field documents crap.doc.TestNesting[]

---@alias crap.hook_fn.TestNesting fun(ctx: crap.hook.TestNesting): crap.hook.TestNesting

---@class crap.field_hook.TestNesting
---@field field_name string
---@field collection "test_nesting"
---@field operation string
---@field data crap.data.TestNesting
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.TestNesting
---@field id? crap.FilterValue
---@field name? crap.FilterValue
---@field theme? crap.FilterValue
---@field layout? crap.FilterValue
---@field custom_config? crap.FilterValue
---@field custom_css? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.TestNesting : crap.FindQuery
---@field where? crap.where.TestNesting
---@field order_by? "id"|"-id"|"name"|"-name"|"theme"|"-theme"|"layout"|"-layout"|"custom_config"|"-custom_config"|"custom_css"|"-custom_css"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.TestNesting
local _coll_test_nesting = {}

---@param query? crap.query.TestNesting
---@return crap.find_result.TestNesting
function _coll_test_nesting.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.TestNesting?
function _coll_test_nesting.find_by_id(id, opts) end

---@param data crap.data.TestNesting
---@param opts? crap.CreateOptions
---@return crap.doc.TestNesting
function _coll_test_nesting.create(data, opts) end

---@param id string
---@param data crap.partial.TestNesting
---@param opts? crap.UpdateOptions
---@return crap.doc.TestNesting
function _coll_test_nesting.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_test_nesting.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.TestNesting
function _coll_test_nesting.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_test_nesting.undelete(id, opts) end

---@param data crap.data.TestNesting
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_test_nesting.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_test_nesting.count(query) end

---@param items crap.data.TestNesting[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_test_nesting.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.TestNesting
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_test_nesting.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_test_nesting.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_test_nesting.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.TestNesting
function _coll_test_nesting.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_test_nesting.ref_count(id) end

crap.collections.test_nesting = _coll_test_nesting

---@class crap.group.TestimonialsSeo
---@field meta_title? string
---@field meta_description? string
---@field no_index? boolean

---@class crap.data.Testimonials
---@field id? string
---@field author_name string
---@field author_title? string
---@field company? string
---@field author_photo? string
---@field quote string
---@field rating number
---@field project? string
---@field featured? boolean
---@field seo? crap.group.TestimonialsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Testimonials
---@field author_name? string
---@field author_title? string
---@field company? string
---@field author_photo? string
---@field quote? string
---@field rating? number
---@field project? string
---@field featured? boolean
---@field seo? crap.group.TestimonialsSeo

---@class crap.doc.Testimonials : crap.Document
---@field id string
---@field author_name string
---@field author_title? string
---@field company? string
---@field author_photo? string
---@field quote string
---@field rating number
---@field project? string
---@field featured? boolean
---@field seo? crap.group.TestimonialsSeo
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Testimonials
---@field collection "testimonials"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Testimonials
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Testimonials : crap.FindResult
---@field documents crap.doc.Testimonials[]

---@alias crap.hook_fn.Testimonials fun(ctx: crap.hook.Testimonials): crap.hook.Testimonials

---@class crap.field_hook.Testimonials
---@field field_name string
---@field collection "testimonials"
---@field operation string
---@field data crap.data.Testimonials
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Testimonials
---@field id? crap.FilterValue
---@field author_name? crap.FilterValue
---@field author_title? crap.FilterValue
---@field company? crap.FilterValue
---@field author_photo? crap.FilterValue
---@field quote? crap.FilterValue
---@field rating? crap.FilterValue
---@field project? crap.FilterValue
---@field featured? crap.FilterValue
---@field seo__meta_title? crap.FilterValue
---@field seo__meta_description? crap.FilterValue
---@field seo__no_index? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Testimonials : crap.FindQuery
---@field where? crap.where.Testimonials
---@field order_by? "id"|"-id"|"author_name"|"-author_name"|"author_title"|"-author_title"|"company"|"-company"|"author_photo"|"-author_photo"|"quote"|"-quote"|"rating"|"-rating"|"project"|"-project"|"featured"|"-featured"|"seo__meta_title"|"-seo__meta_title"|"seo__meta_description"|"-seo__meta_description"|"seo__no_index"|"-seo__no_index"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Testimonials
local _coll_testimonials = {}

---@param query? crap.query.Testimonials
---@return crap.find_result.Testimonials
function _coll_testimonials.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Testimonials?
function _coll_testimonials.find_by_id(id, opts) end

---@param data crap.data.Testimonials
---@param opts? crap.CreateOptions
---@return crap.doc.Testimonials
function _coll_testimonials.create(data, opts) end

---@param id string
---@param data crap.partial.Testimonials
---@param opts? crap.UpdateOptions
---@return crap.doc.Testimonials
function _coll_testimonials.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_testimonials.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Testimonials
function _coll_testimonials.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_testimonials.undelete(id, opts) end

---@param data crap.data.Testimonials
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_testimonials.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_testimonials.count(query) end

---@param items crap.data.Testimonials[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_testimonials.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Testimonials
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_testimonials.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_testimonials.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_testimonials.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Testimonials
function _coll_testimonials.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_testimonials.ref_count(id) end

crap.collections.testimonials = _coll_testimonials

---@class crap.data.Users
---@field id? string
---@field email string
---@field name string
---@field role "admin" | "director" | "editor" | "author"
---@field skills? ("design" | "development" | "strategy" | "motion" | "photography" | "copywriting" | "3d"|string)[]
---@field avatar? string
---@field bio? string
---@field authored_posts? table[]
---@field created_at? string
---@field updated_at? string

---@class crap.partial.Users
---@field email? string
---@field name? string
---@field role? "admin" | "director" | "editor" | "author"
---@field skills? ("design" | "development" | "strategy" | "motion" | "photography" | "copywriting" | "3d"|string)[]
---@field avatar? string
---@field bio? string
---@field authored_posts? table[]

---@class crap.doc.Users : crap.Document
---@field id string
---@field email string
---@field name string
---@field role "admin" | "director" | "editor" | "author"
---@field skills? ("design" | "development" | "strategy" | "motion" | "photography" | "copywriting" | "3d"|string)[]
---@field avatar? string
---@field bio? string
---@field authored_posts? table[]
---@field created_at? string
---@field updated_at? string

---@class crap.hook.Users
---@field collection "users"
---@field operation "create" | "update" | "find" | "find_by_id"
---@field data crap.data.Users
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.find_result.Users : crap.FindResult
---@field documents crap.doc.Users[]

---@alias crap.hook_fn.Users fun(ctx: crap.hook.Users): crap.hook.Users

---@class crap.field_hook.Users
---@field field_name string
---@field collection "users"
---@field operation string
---@field data crap.data.Users
---@field user? table
---@field ui_locale? string

---@class (exact) crap.where.Users
---@field id? crap.FilterValue
---@field email? crap.FilterValue
---@field name? crap.FilterValue
---@field role? crap.FilterValue
---@field skills? crap.FilterValue
---@field avatar? crap.FilterValue
---@field bio? crap.FilterValue
---@field created_at? crap.FilterValue
---@field updated_at? crap.FilterValue

---@class (exact) crap.query.Users : crap.FindQuery
---@field where? crap.where.Users
---@field order_by? "id"|"-id"|"email"|"-email"|"name"|"-name"|"role"|"-role"|"skills"|"-skills"|"avatar"|"-avatar"|"bio"|"-bio"|"created_at"|"-created_at"|"updated_at"|"-updated_at"
---@field limit? integer
---@field offset? integer
---@field locale? string

---@class crap.collections.Users
local _coll_users = {}

---@param query? crap.query.Users
---@return crap.find_result.Users
function _coll_users.find(query) end

---@param id string
---@param opts? crap.FindByIdOptions
---@return crap.doc.Users?
function _coll_users.find_by_id(id, opts) end

---@param data crap.data.Users
---@param opts? crap.CreateOptions
---@return crap.doc.Users
function _coll_users.create(data, opts) end

---@param id string
---@param data crap.partial.Users
---@param opts? crap.UpdateOptions
---@return crap.doc.Users
function _coll_users.update(id, data, opts) end

---@param id string
---@param opts? crap.DeleteOptions
---@return boolean
function _coll_users.delete(id, opts) end

---@param id string
---@param opts? crap.UnpublishOptions
---@return crap.doc.Users
function _coll_users.unpublish(id, opts) end

---@param id string
---@param opts? crap.UndeleteOptions
---@return boolean
function _coll_users.undelete(id, opts) end

---@param data crap.data.Users
---@param opts? crap.ValidateOptions
---@return crap.ValidateResult
function _coll_users.validate(data, opts) end

---@param query? crap.CountQuery
---@return integer
function _coll_users.count(query) end

---@param items crap.data.Users[]
---@param opts? crap.CreateOptions
---@return crap.CreateManyResult
function _coll_users.create_many(items, opts) end

---@param query crap.UpdateManyQuery
---@param data crap.partial.Users
---@param opts? crap.UpdateOptions
---@return crap.UpdateManyResult
function _coll_users.update_many(query, data, opts) end

---@param query crap.DeleteManyQuery
---@param opts? crap.DeleteOptions
---@return crap.DeleteManyResult
function _coll_users.delete_many(query, opts) end

---@param id string
---@param opts? crap.ListVersionsOptions
---@return crap.ListVersionsResult
function _coll_users.list_versions(id, opts) end

---@param id string
---@param version_id string
---@param opts? crap.RestoreVersionOptions
---@return crap.doc.Users
function _coll_users.restore_version(id, version_id, opts) end

---@param id string
---@return integer
function _coll_users.ref_count(id) end

crap.collections.users = _coll_users

---@class crap.array_row.FooterPartnerLogos
---@field name string
---@field logo? string
---@field url? string

---@class crap.global_data.Footer
---@field id? string
---@field copyright_text? string
---@field show_social_links? boolean
---@field partner_logos? crap.array_row.FooterPartnerLogos[]
---@field created_at? string
---@field updated_at? string

---@class crap.global_partial.Footer
---@field copyright_text? string
---@field show_social_links? boolean
---@field partner_logos? crap.array_row.FooterPartnerLogos[]

---@class crap.global_doc.Footer : crap.Document
---@field id string
---@field copyright_text? string
---@field show_social_links? boolean
---@field partner_logos? crap.array_row.FooterPartnerLogos[]
---@field created_at? string
---@field updated_at? string

---@class crap.hook.global_footer
---@field collection "footer"
---@field operation "update" | "get_global"
---@field data crap.global_data.Footer
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.field_hook.global_footer
---@field field_name string
---@field collection "footer"
---@field operation string
---@field data crap.global_data.Footer
---@field user? table
---@field ui_locale? string

---@class crap.globals.Footer
local _glob_footer = {}

---@param opts? crap.GlobalGetOptions
---@return crap.global_doc.Footer
function _glob_footer.get(opts) end

---@param data crap.global_partial.Footer
---@param opts? crap.GlobalUpdateOptions
---@return crap.global_doc.Footer
function _glob_footer.update(data, opts) end

crap.globals.footer = _glob_footer

---@class crap.array_row.NavigationMainNav
---@field label string
---@field url string
---@field open_in_new_tab? boolean
---@field children? crap.array_row.NavigationMainNavChildren[]

---@class crap.array_row.NavigationMainNavChildren
---@field label string
---@field url string

---@class crap.global_data.Navigation
---@field id? string
---@field main_nav? crap.array_row.NavigationMainNav[]
---@field created_at? string
---@field updated_at? string

---@class crap.global_partial.Navigation
---@field main_nav? crap.array_row.NavigationMainNav[]

---@class crap.global_doc.Navigation : crap.Document
---@field id string
---@field main_nav? crap.array_row.NavigationMainNav[]
---@field created_at? string
---@field updated_at? string

---@class crap.hook.global_navigation
---@field collection "navigation"
---@field operation "update" | "get_global"
---@field data crap.global_data.Navigation
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.field_hook.global_navigation
---@field field_name string
---@field collection "navigation"
---@field operation string
---@field data crap.global_data.Navigation
---@field user? table
---@field ui_locale? string

---@class crap.globals.Navigation
local _glob_navigation = {}

---@param opts? crap.GlobalGetOptions
---@return crap.global_doc.Navigation
function _glob_navigation.get(opts) end

---@param data crap.global_partial.Navigation
---@param opts? crap.GlobalUpdateOptions
---@return crap.global_doc.Navigation
function _glob_navigation.update(data, opts) end

crap.globals.navigation = _glob_navigation

---@class crap.group.SiteSettingsSocial
---@field github? string
---@field twitter? string
---@field linkedin? string
---@field instagram? string
---@field youtube? string

---@class crap.global_data.SiteSettings
---@field id? string
---@field site_name string
---@field tagline? string
---@field contact_email? string
---@field phone? string
---@field address? string
---@field logo? string
---@field favicon? string
---@field primary_color? string
---@field secondary_color? string
---@field social? crap.group.SiteSettingsSocial
---@field created_at? string
---@field updated_at? string

---@class crap.global_partial.SiteSettings
---@field site_name? string
---@field tagline? string
---@field contact_email? string
---@field phone? string
---@field address? string
---@field logo? string
---@field favicon? string
---@field primary_color? string
---@field secondary_color? string
---@field social? crap.group.SiteSettingsSocial

---@class crap.global_doc.SiteSettings : crap.Document
---@field id string
---@field site_name string
---@field tagline? string
---@field contact_email? string
---@field phone? string
---@field address? string
---@field logo? string
---@field favicon? string
---@field primary_color? string
---@field secondary_color? string
---@field social? crap.group.SiteSettingsSocial
---@field created_at? string
---@field updated_at? string

---@class crap.hook.global_site_settings
---@field collection "site_settings"
---@field operation "update" | "get_global"
---@field data crap.global_data.SiteSettings
---@field context table<string, any>
---@field hook_depth integer
---@field locale? string
---@field draft? boolean
---@field user? table
---@field ui_locale? string

---@class crap.field_hook.global_site_settings
---@field field_name string
---@field collection "site_settings"
---@field operation string
---@field data crap.global_data.SiteSettings
---@field user? table
---@field ui_locale? string

---@class crap.globals.SiteSettings
local _glob_site_settings = {}

---@param opts? crap.GlobalGetOptions
---@return crap.global_doc.SiteSettings
function _glob_site_settings.get(opts) end

---@param data crap.global_partial.SiteSettings
---@param opts? crap.GlobalUpdateOptions
---@return crap.global_doc.SiteSettings
function _glob_site_settings.update(data, opts) end

crap.globals.site_settings = _glob_site_settings

---@overload fun(collection: "categories", query?: crap.FindQuery): crap.find_result.Categories
---@overload fun(collection: "clients", query?: crap.FindQuery): crap.find_result.Clients
---@overload fun(collection: "events", query?: crap.FindQuery): crap.find_result.Events
---@overload fun(collection: "inquiries", query?: crap.FindQuery): crap.find_result.Inquiries
---@overload fun(collection: "media", query?: crap.FindQuery): crap.find_result.Media
---@overload fun(collection: "pages", query?: crap.FindQuery): crap.find_result.Pages
---@overload fun(collection: "posts", query?: crap.FindQuery): crap.find_result.Posts
---@overload fun(collection: "projects", query?: crap.FindQuery): crap.find_result.Projects
---@overload fun(collection: "services", query?: crap.FindQuery): crap.find_result.Services
---@overload fun(collection: "tags", query?: crap.FindQuery): crap.find_result.Tags
---@overload fun(collection: "test_nesting", query?: crap.FindQuery): crap.find_result.TestNesting
---@overload fun(collection: "testimonials", query?: crap.FindQuery): crap.find_result.Testimonials
---@overload fun(collection: "users", query?: crap.FindQuery): crap.find_result.Users
---@overload fun(collection: string, query?: crap.FindQuery): crap.FindResult
function crap.collections.find(collection, query) end

---@overload fun(collection: "categories", id: string, opts?: crap.FindByIdOptions): crap.doc.Categories?
---@overload fun(collection: "clients", id: string, opts?: crap.FindByIdOptions): crap.doc.Clients?
---@overload fun(collection: "events", id: string, opts?: crap.FindByIdOptions): crap.doc.Events?
---@overload fun(collection: "inquiries", id: string, opts?: crap.FindByIdOptions): crap.doc.Inquiries?
---@overload fun(collection: "media", id: string, opts?: crap.FindByIdOptions): crap.doc.Media?
---@overload fun(collection: "pages", id: string, opts?: crap.FindByIdOptions): crap.doc.Pages?
---@overload fun(collection: "posts", id: string, opts?: crap.FindByIdOptions): crap.doc.Posts?
---@overload fun(collection: "projects", id: string, opts?: crap.FindByIdOptions): crap.doc.Projects?
---@overload fun(collection: "services", id: string, opts?: crap.FindByIdOptions): crap.doc.Services?
---@overload fun(collection: "tags", id: string, opts?: crap.FindByIdOptions): crap.doc.Tags?
---@overload fun(collection: "test_nesting", id: string, opts?: crap.FindByIdOptions): crap.doc.TestNesting?
---@overload fun(collection: "testimonials", id: string, opts?: crap.FindByIdOptions): crap.doc.Testimonials?
---@overload fun(collection: "users", id: string, opts?: crap.FindByIdOptions): crap.doc.Users?
---@overload fun(collection: string, id: string, opts?: crap.FindByIdOptions): crap.Document?
function crap.collections.find_by_id(collection, id, opts) end

-- ─── Template data context (for `crap.template_data.register`) ───

--- Metadata about the running crap-cms process and current request.
--- @class crap.template.crap_meta
--- @field version string Crate version (Cargo.toml `version`).
--- @field build_hash string Build hash (set by build script from git).
--- @field dev_mode boolean Whether admin dev-mode is enabled (per-request template reload, etc.).
--- @field auth_enabled boolean Whether the system has any auth-enabled collections.
--- @field csp_nonce string Per-request CSP nonce (empty string outside request scope).
--- @field site_name string Branding string shown in the admin header wordmark and `<title>` tags. Defaults to `"Crap CMS"`; configurable via `[admin] site_name = "..."` in `crap.toml`.

--- Identifying data about the currently authenticated user.
--- @class crap.template.user
--- @field email string
--- @field id string
--- @field collection string

--- A breadcrumb entry with a label and optional URL.
--- @class crap.template.breadcrumb
--- @field label string The text label to display for the breadcrumb.
--- @field url? string The optional URL to link to. If None, the breadcrumb is the current page.
--- @field label_name? string Optional interpolation param for `{{t label name=label_name}}`.

--- The `page` object every admin template receives. Carries the page-type
--- discriminant, the page title (already-translated label or translation key),
--- optional title interpolation parameter, and breadcrumb trail.
--- @class crap.template.page
--- @field page_type "dashboard" | "collection_list" | "collection_items" | "collection_edit" | "collection_create" | "collection_delete" | "collection_versions" | "global_edit" | "global_versions" | "auth_login" | "auth_forgot" | "auth_reset" | "auth_mfa" | "error_403" | "error_404" | "error_500" | "auth_required" | "admin_denied" | "custom_page" Page-type discriminant. Serialized as a `snake_case` string literal so templates can branch with `{{#if (eq page.type "collection_edit")}}`.
--- @field title string Page title or translation key.
--- @field title_name? string Optional interpolation param for `{{t page.title name=page.title_name}}`.
--- @field breadcrumbs? crap.template.breadcrumb[] Breadcrumb trail rendered by `partials/breadcrumb.hbs`.

--- One sidebar entry for a collection.
--- @class crap.template.nav_collection
--- @field slug string
--- @field display_name string
--- @field is_auth boolean
--- @field is_upload boolean

--- One sidebar entry for a global.
--- @class crap.template.nav_global
--- @field slug string
--- @field display_name string

--- Sidebar metadata declared from Lua via `crap.pages.register`.
--- @class crap.template.custom_page
--- @field slug string Slug — the URL segment and the filename stem.
--- @field section? string Sidebar section heading. `None` → page is registered but not grouped (renders ungrouped at the bottom).
--- @field label? string Sidebar label. `None` → page is registered but not shown in nav.
--- @field icon? string Optional Material Symbols icon name.
--- @field access? string Optional Lua function-ref name for access control. When set, the named function is called with the page context before the route handler renders; returning `false` produces a 403, and the page is hidden from the sidebar nav for users who can't read it. Mirrors `access.read` on collections / globals — register the function once via `crap.access.register("name", fn)`, then refer to it by name here.

--- Top-level nav data exposed at `{{nav.*}}`.
--- @class crap.template.nav
--- @field collections crap.template.nav_collection[]
--- @field globals crap.template.nav_global[]
--- @field custom_pages? crap.template.custom_page[] Filesystem-routed custom admin pages registered via `crap.pages.register`. Only entries with a `label` set appear here.

--- Admin-presentation metadata for a field (label, description, layout hints).
--- @class crap.template.field_admin_meta
--- @field label? string
--- @field hidden boolean
--- @field readonly boolean
--- @field width? string
--- @field description? string
--- @field placeholder? string

--- Metadata about a single field as it appears to templates.
--- @class crap.template.field_meta
--- @field name string
--- @field field_type string
--- @field required boolean
--- @field unique boolean
--- @field localized boolean
--- @field admin crap.template.field_admin_meta

--- Admin-presentation metadata pulled from `def.admin`.
--- @class crap.template.admin_meta
--- @field use_as_title? string
--- @field default_sort? string
--- @field hidden boolean
--- @field list_searchable_fields string[]

--- Upload-collection metadata. Only present when `def.upload` is set.
--- @class crap.template.upload_meta
--- @field enabled boolean
--- @field mime_types string[]
--- @field max_file_size? integer
--- @field admin_thumbnail? string

--- Versioning metadata. Only present when `def.versions` is set.
--- @class crap.template.versions_meta
--- @field drafts boolean
--- @field max_versions integer

--- Auth-collection metadata. Only present when `def.auth` is set.
--- @class crap.template.auth_meta
--- @field enabled boolean
--- @field disable_local boolean
--- @field verify_email boolean

--- Top-level collection metadata exposed to templates.
---
--- Capability bits (`is_auth`, `is_upload`, `has_versions`, `has_drafts`)
--- are intentionally NOT separate fields — templates derive them from the
--- presence of the corresponding `Option<*Meta>` sub-struct (and the
--- `drafts` flag inside `versions`). Single source of truth: if `auth`
--- is `None`, the collection isn't auth-enabled; if `versions.drafts` is
--- false, drafts aren't on.
--- @class crap.template.collection
--- @field slug string
--- @field display_name string
--- @field singular_name string
--- @field title_field? string
--- @field timestamps boolean
--- @field soft_delete boolean
--- @field admin crap.template.admin_meta
--- @field upload? crap.template.upload_meta
--- @field versions? crap.template.versions_meta
--- @field auth? crap.template.auth_meta
--- @field fields_meta crap.template.field_meta[]

--- Top-level global metadata exposed to templates.
--- @class crap.template.global
--- @field slug string
--- @field display_name string
--- @field has_drafts boolean
--- @field has_versions boolean
--- @field versions? crap.template.versions_meta
--- @field fields_meta crap.template.field_meta[]

--- A document reference exposed at `{{document.*}}`. The `data` map carries the
--- document's field values (untyped — typing field values is part of 1.C.2).
--- @class crap.template.document
--- @field id string
--- @field created_at? string
--- @field updated_at? string
--- @field status? string
--- @field data? table

--- One row in the editor-locale picker dropdown.
--- @class crap.template.editor_locale_option
--- @field value string
--- @field label string
--- @field selected boolean

---@class crap.template_ctx
---@field crap crap.template.crap_meta
---@field _locale string
---@field available_locales string[]
---@field title string
---@field page crap.template.page
---@field nav crap.template.nav
---@field breadcrumbs? crap.template.breadcrumb[]
---@field user? crap.template.user
---@field collection? crap.template.collection
---@field global? crap.template.global
---@field document? crap.template.document
---@field has_editor_locales? boolean
---@field editor_locale? string
---@field editor_locales? crap.template.editor_locale_option[]
-- For page-specific fields beyond the bases (e.g. `collection_cards`, `versions`),
-- see docs/src/admin-ui/template-context.md or the generated reference.

---@alias crap.template_data_fn fun(ctx: crap.template_ctx): any

