//! The generated auth secret in a backup.
//!
//! When `[auth] secret` is empty, the secret is generated once into
//! `data/.jwt_secret`. Sessions, sealed TOTP secrets, `crap.crypto` ciphertext
//! and signed upload URLs in the database are keyed by it, so a backup carries
//! it as `jwt_secret` and a restore writes it back — owner-only both ways.

use std::{
    fs,
    path::{Path, PathBuf},
};

use anyhow::{Context as _, Result};
use chrono::Utc;

use crate::{cli, config::write_new_owner_only};

/// File name of the secret inside a backup directory.
const BACKUP_SECRET: &str = "jwt_secret";

/// File name prefix a replaced secret is kept under.
const PREVIOUS_SECRET_PREFIX: &str = ".jwt_secret.pre-restore-";

fn live_secret(config_dir: &Path) -> PathBuf {
    config_dir.join("data").join(".jwt_secret")
}

/// Whether the project has a generated auth secret: a readable, non-empty
/// secret file. An empty one a crash left behind holds no secret.
pub(super) fn has_generated_secret(config_dir: &Path) -> bool {
    fs::read_to_string(live_secret(config_dir)).is_ok_and(|s| !s.trim().is_empty())
}

/// Copy the generated auth secret into the backup. Returns whether there was
/// one to copy.
///
/// # Errors
///
/// Returns an error if the secret can't be read or written.
pub(super) fn backup_secret(config_dir: &Path, backup_dir: &Path) -> Result<bool> {
    if !has_generated_secret(config_dir) {
        return Ok(false);
    }
    let source = live_secret(config_dir);

    let contents = fs::read(&source).context("Failed to read the auth secret")?;
    let target = backup_dir.join(BACKUP_SECRET);

    write_new_owner_only(&target, &contents)
        .with_context(|| format!("Failed to write {}", target.display()))?;

    Ok(true)
}

/// Whether a configured secret — `resolved`, the one the loaded config uses —
/// overrides the generated secret the backup carries, so the restored one goes
/// unused.
pub(super) fn configured_secret_overrides(backup_dir: &Path, resolved: &str) -> bool {
    fs::read_to_string(backup_dir.join(BACKUP_SECRET)).is_ok_and(|backed_up| {
        let backed_up = backed_up.trim();
        !backed_up.is_empty() && backed_up != resolved
    })
}

/// Write the backed-up secret back. A different secret it replaces is kept
/// beside it as `.jwt_secret.pre-restore-<timestamp>`, a name no later restore
/// reuses — unless `keep_replaced` is off, for a secret generated by this very
/// run, which nothing is keyed by yet.
///
/// # Errors
///
/// Returns an error if a secret can't be read, kept or written.
pub(super) fn restore_secret(
    config_dir: &Path,
    backup_dir: &Path,
    keep_replaced: bool,
) -> Result<()> {
    let source = backup_dir.join(BACKUP_SECRET);
    if !source.is_file() {
        return Ok(());
    }

    let target = live_secret(config_dir);
    let backed_up = fs::read(&source).context("Failed to read the backed-up auth secret")?;

    if fs::read(&target).is_ok_and(|current| current == backed_up) {
        return Ok(());
    }

    if keep_replaced {
        keep_previous_secret(&target)?;
    }
    replace_secret(&target, &backed_up)?;
    cli::success("Auth secret restored");

    Ok(())
}

/// Copy the secret a restore replaces beside it, owner-only.
fn keep_previous_secret(target: &Path) -> Result<()> {
    if !target.exists() {
        return Ok(());
    }

    let previous =
        fs::read(target).with_context(|| format!("Failed to read {}", target.display()))?;
    let aside = unused_previous_secret_path(target);

    write_new_owner_only(&aside, &previous).with_context(|| {
        format!(
            "Failed to keep the previous auth secret at {}",
            aside.display()
        )
    })?;
    cli::info(&format!("Previous auth secret kept at {}", aside.display()));

    Ok(())
}

/// A timestamped name beside `target` that no file uses yet.
fn unused_previous_secret_path(target: &Path) -> PathBuf {
    let base = format!(
        "{PREVIOUS_SECRET_PREFIX}{}",
        Utc::now().format("%Y%m%dT%H%M%SZ")
    );

    let mut candidate = target.with_file_name(&base);
    let mut n = 1;

    while candidate.exists() {
        candidate = target.with_file_name(format!("{base}-{n}"));
        n += 1;
    }

    candidate
}

/// Stage the new secret beside the live one and rename it into place, so a
/// failure midway never leaves the project without a secret.
fn replace_secret(target: &Path, contents: &[u8]) -> Result<()> {
    if let Some(parent) = target.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("Failed to create directory: {}", parent.display()))?;
    }

    let staged = target.with_file_name(".jwt_secret.restoring");
    if staged.exists() {
        fs::remove_file(&staged)
            .with_context(|| format!("Failed to remove {}", staged.display()))?;
    }

    write_new_owner_only(&staged, contents)
        .with_context(|| format!("Failed to write {}", staged.display()))?;

    fs::rename(&staged, target).with_context(|| {
        format!(
            "Failed to move the restored auth secret into {}",
            target.display()
        )
    })
}

#[cfg(test)]
mod tests {
    #[cfg(unix)]
    use std::os::unix::fs::PermissionsExt as _;

    use super::*;

    fn config_with_secret(secret: &str) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        fs::create_dir_all(dir.path().join("data")).unwrap();
        fs::write(live_secret(dir.path()), secret).unwrap();
        dir
    }

    fn backup_with_secret(secret: &str) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join(BACKUP_SECRET), secret).unwrap();
        dir
    }

    /// The contents of every kept previous secret, sorted.
    fn previous_secrets(config_dir: &Path) -> Vec<String> {
        let mut secrets: Vec<String> = fs::read_dir(config_dir.join("data"))
            .unwrap()
            .filter_map(Result::ok)
            .filter(|e| {
                e.file_name()
                    .to_string_lossy()
                    .starts_with(PREVIOUS_SECRET_PREFIX)
            })
            .map(|e| fs::read_to_string(e.path()).unwrap())
            .collect();
        secrets.sort();
        secrets
    }

    #[test]
    fn backup_copies_the_secret_owner_only() {
        let config = config_with_secret("generated");
        let backup = tempfile::tempdir().unwrap();

        assert!(backup_secret(config.path(), backup.path()).unwrap());

        let copied = backup.path().join(BACKUP_SECRET);
        assert_eq!(fs::read_to_string(&copied).unwrap(), "generated");

        #[cfg(unix)]
        assert_eq!(
            fs::metadata(&copied).unwrap().permissions().mode() & 0o777,
            0o600
        );
    }

    /// Regression: a backup carried an empty secret file, and a restore then
    /// warned about a secret that doesn't exist.
    #[test]
    fn backup_skips_an_empty_secret_file() {
        let config = config_with_secret("");
        let backup = tempfile::tempdir().unwrap();

        assert!(!backup_secret(config.path(), backup.path()).unwrap());
        assert!(!backup.path().join(BACKUP_SECRET).exists());
    }

    #[test]
    fn backup_without_a_generated_secret_copies_nothing() {
        let config = tempfile::tempdir().unwrap();
        let backup = tempfile::tempdir().unwrap();

        assert!(!backup_secret(config.path(), backup.path()).unwrap());
        assert!(!backup.path().join(BACKUP_SECRET).exists());
    }

    #[test]
    fn restore_keeps_a_different_secret_aside() {
        let config = config_with_secret("new-host");
        let backup = backup_with_secret("backed-up");

        restore_secret(config.path(), backup.path(), true).unwrap();

        let live = live_secret(config.path());
        assert_eq!(fs::read_to_string(&live).unwrap(), "backed-up");
        assert_eq!(previous_secrets(config.path()), vec!["new-host"]);

        #[cfg(unix)]
        assert_eq!(
            fs::metadata(&live).unwrap().permissions().mode() & 0o777,
            0o600
        );
    }

    /// Regression: every restore kept the replaced secret under the same name,
    /// so a second restore overwrote the host's original secret.
    #[test]
    fn a_second_restore_keeps_every_previous_secret() {
        let config = config_with_secret("original");

        restore_secret(config.path(), backup_with_secret("first").path(), true).unwrap();
        restore_secret(config.path(), backup_with_secret("second").path(), true).unwrap();

        assert_eq!(
            fs::read_to_string(live_secret(config.path())).unwrap(),
            "second"
        );
        assert_eq!(previous_secrets(config.path()), vec!["first", "original"]);
    }

    #[test]
    fn restore_without_a_live_secret_writes_it() {
        let config = tempfile::tempdir().unwrap();

        restore_secret(config.path(), backup_with_secret("backed-up").path(), true).unwrap();

        assert_eq!(
            fs::read_to_string(live_secret(config.path())).unwrap(),
            "backed-up"
        );
        assert!(previous_secrets(config.path()).is_empty());
    }

    /// A configured secret takes precedence over the generated one a restore
    /// writes back, so the restore warns unless the two are the same.
    #[test]
    fn a_configured_secret_overrides_the_restored_one() {
        let backup = backup_with_secret("backed-up");
        let empty_backup = tempfile::tempdir().unwrap();

        assert!(!configured_secret_overrides(backup.path(), "backed-up"));
        assert!(configured_secret_overrides(backup.path(), "from-crap-toml"));
        assert!(!configured_secret_overrides(
            empty_backup.path(),
            "from-crap-toml"
        ));
    }

    /// Regression: a restore into a project without a secret kept the one its
    /// own config load had just generated beside the restored secret, as if it
    /// were a host secret worth keeping.
    #[test]
    fn restore_does_not_keep_a_secret_generated_by_the_run() {
        let config = config_with_secret("generated-by-this-run");

        restore_secret(config.path(), backup_with_secret("backed-up").path(), false).unwrap();

        assert_eq!(
            fs::read_to_string(live_secret(config.path())).unwrap(),
            "backed-up"
        );
        assert!(previous_secrets(config.path()).is_empty());
    }
}
