# Auto-generated by crap-cms. Do not edit.

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, Any, Literal

@dataclass
class N2fa:
    id: str = ""
    type: Optional[str] = None
    n2fa: Optional[str] = None  # wire: 2fa
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class Media:
    id: str = ""
    filename: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class PostsSeo:
    meta_title: Optional[str] = None
    meta_desc: Optional[str] = None

@dataclass
class PostsItems:
    id: Optional[str] = None
    label: Optional[str] = None
    meta: Optional[PostsItemsMeta] = None

@dataclass
class PostsItemsMeta:
    key: Optional[str] = None

@dataclass
class Posts:
    """Select fields — status: 'draft', 'published'"""
    id: str = ""
    title: Optional[str] = None
    summary: Optional[str] = None
    published_at: Optional[str] = None
    published_at_tz: Optional[str] = None
    status: Optional[Literal["draft", "published"]] = None
    author: Optional[str | Users] = None
    tags: Optional[list[str | Tags]] = None
    cover: Optional[str | Media] = None
    # Polymorphic relationship — targets: users, tags
    related: Optional[list[str | Users | Tags]] = None
    seo: Optional[PostsSeo] = None
    items: Optional[list[PostsItems]] = None
    content: Optional[list[dict]] = None
    scores: Optional[list[float]] = None
    active: Optional[bool] = None
    data: Optional[Any] = None
    _status: Optional[str] = None
    _deleted_at: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class PostsSeoLocalized:
    meta_title: Optional[dict[str, Optional[str]]] = None
    meta_desc: Optional[dict[str, Optional[str]]] = None

@dataclass
class PostsLocalized:
    """Read with locale=all: localized fields hold one value per locale."""
    id: str = ""
    title: Optional[str] = None
    summary: Optional[dict[str, Optional[str]]] = None
    published_at: Optional[str] = None
    published_at_tz: Optional[str] = None
    status: Optional[Literal["draft", "published"]] = None
    author: Optional[str | Users] = None
    tags: Optional[list[str | Tags]] = None
    cover: Optional[str | Media] = None
    # Polymorphic relationship — targets: users, tags
    related: Optional[list[str | Users | Tags]] = None
    seo: Optional[PostsSeoLocalized] = None
    items: Optional[list[PostsItems]] = None
    content: Optional[list[dict]] = None
    scores: Optional[list[float]] = None
    active: Optional[bool] = None
    data: Optional[Any] = None
    _status: Optional[str] = None
    _deleted_at: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class Tags:
    id: str = ""
    name: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class Users:
    id: str = ""
    name: Optional[str] = None
    email: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

@dataclass
class SettingsNav:
    id: Optional[str] = None
    label: Optional[str] = None
    url: Optional[str] = None

@dataclass
class Settings:
    id: str = ""
    site_name: Optional[str] = None
    nav: Optional[list[SettingsNav]] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None

# All collection slugs.
CollectionSlug = Literal["2fa", "media", "posts", "tags", "users"]
