//! Spec emitted by `#[lua_fn]` describing a Lua API function for typegen.
//!
//! Each Rust fn annotated with `#[lua_fn(path = "...")]` generates a
//! `const FN_SPEC: LuaFnSpec` holding its path, doc-comments, ordered
//! parameter list, and return type. The static-file assembler walks
//! these specs to emit `function crap.X.Y(...) end` Lua declarations
//! with their `--- @param` / `--- @return` annotations above.
//!
//! Why const data, not a method on a trait: keeps the spec available
//! at compile time, allows static composition into Lua type files via
//! `cargo xtask gen-lua-types` without instantiating anything. The
//! companion `_register` fn (also generated by `#[lua_fn]`) handles
//! runtime wiring into the Lua VM.

/// Compile-time metadata for one Lua API function. Generated by
/// `#[lua_fn(path = "...")]`.
pub struct LuaFnSpec {
    /// Full dotted Lua path (e.g. `"crap.util.slugify"`).
    pub path: &'static str,

    /// Doc-comment lines from the fn's `///` comments, one entry per
    /// line. Empty slice if the fn has no docs. Each entry is the raw
    /// line content (with the leading `///` and one space stripped).
    pub doc: &'static [&'static str],

    /// Ordered parameter list. Skips `&Lua` and `&State`; only Lua-facing
    /// arguments appear here.
    pub params: &'static [LuaParam],

    /// Return value spec. `None` for `()`-returning fns (no `--- @return`
    /// emitted).
    pub returns: Option<LuaReturn>,
}

/// One Lua-facing parameter on a `#[lua_fn]`.
pub struct LuaParam {
    /// Parameter name as it appears in the Lua signature.
    pub name: &'static str,

    /// `LuaLS` type string (e.g. `"string"`, `"crap.CollectionConfig"`,
    /// `"integer?"`).
    pub ty: &'static str,

    /// Trailing prose description (taken from a `#[lua(doc = "...")]`
    /// override on the param, or empty if not set). Lua emits this
    /// after the type on the `--- @param` line.
    pub doc: &'static str,
}

/// Return value spec for a `#[lua_fn]`.
pub struct LuaReturn {
    /// `LuaLS` type string for the return.
    pub ty: &'static str,

    /// Trailing prose description (from `#[lua_fn(returns_doc = "...")]`).
    pub doc: &'static str,
}

impl LuaFnSpec {
    /// The final segment of the dotted path — what the function is
    /// registered as on its containing table.
    ///
    /// For `"crap.util.slugify"` this is `"slugify"`.
    #[must_use]
    pub fn last_segment(&self) -> &'static str {
        match self.path.rfind('.') {
            Some(i) => &self.path[i + 1..],
            None => self.path,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const FIXTURE_SPEC: LuaFnSpec = LuaFnSpec {
        path: "crap.util.slugify",
        doc: &["Generate a URL-safe slug from a string."],
        params: &[LuaParam {
            name: "s",
            ty: "string",
            doc: "",
        }],
        returns: Some(LuaReturn {
            ty: "string",
            doc: "",
        }),
    };

    #[test]
    fn last_segment_extracts_trailing_name() {
        assert_eq!(FIXTURE_SPEC.last_segment(), "slugify");
    }

    #[test]
    fn last_segment_returns_whole_path_when_no_dot() {
        let spec = LuaFnSpec {
            path: "crap",
            doc: &[],
            params: &[],
            returns: None,
        };
        assert_eq!(spec.last_segment(), "crap");
    }
}
