//! Top-level Lua render entry point + per-collection / per-global /
//! find-overload / template-data renderers.

use crate::{
    admin::context::{AdminMeta, AuthMeta, UploadMeta, VersionsMeta},
    admin::{
        context::{
            BasePageContext, CollectionContext, CrapMeta, DocumentRef, EditorLocaleOption,
            FieldAdminMeta, FieldMeta, GlobalContext, NavCollection, NavData, NavGlobal, PageMeta,
            UserContext, page::Breadcrumb,
        },
        custom_pages::CustomPage,
    },
    core::{CollectionDefinition, FieldType, Registry, Slug, collection::GlobalDefinition},
    db::query::get_column_names,
    hooks::lifecycle::RenderInfo,
    typegen::{
        helpers::{SubTypeKind, collect_sub_type_fields, to_pascal_case, w, wraw},
        lua::LuaAnnotation,
    },
};

use super::field::{field_to_lua_type, write_field, write_field_partial};

/// Field types that get a per-field `field_hook` overload in the generated Lua:
/// the leaf/scalar fields — everything that isn't a repeatable composite
/// (`Array`/`Blocks`), a layout wrapper (`Row`/`Collapsible`/`Tabs`), a `Group`,
/// or the virtual `Join`. Shared by the collection and global hook renderers so
/// the two can't drift on which fields are hookable.
fn takes_field_hook(ft: &FieldType) -> bool {
    !ft.has_rows() && !ft.is_layout_wrapper() && !matches!(ft, FieldType::Group | FieldType::Join)
}

/// Render all Lua type definitions.
pub(in crate::typegen) fn render(registry: &Registry) -> String {
    let mut out = String::from("---@meta\n-- Auto-generated by crap-cms. Do not edit.\n\n");

    let mut slugs: Vec<&Slug> = registry.collections.keys().collect();
    slugs.sort();
    for slug in slugs {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    let mut global_slugs: Vec<&Slug> = registry.globals.keys().collect();
    global_slugs.sort();
    for slug in global_slugs {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    render_find_overloads(&mut out, registry);
    render_template_data_types(&mut out);

    out
}

/// Render `crap.template.*` typed shapes and `crap.template_ctx` /
/// `crap.template_data_fn` aliases.
///
/// The template-data context is the same JSON shape every admin page
/// renders. Each Rust typed-context block in `src/admin/context/` has a
/// matching `crap.template.*` class so Lua editors give autocomplete on
/// every level (`ctx.user.email`, `ctx.collection.versions.max_versions`,
/// `ctx.nav.custom_pages[1].icon`, …).
///
/// Per-page extra fields (`collection_cards`, `versions`, …) are not
/// enumerated here — they vary per page and aren't part of the base
/// context. Full per-page shapes live in
/// `docs/src/admin-ui/template-context.md`.
fn render_template_data_types(out: &mut String) {
    out.push_str("-- ─── Template data context (for `crap.template_data.register`) ───\n\n");

    // The annotation for each Rust struct is defined as
    // `impl LuaAnnotation for X` next to the struct itself — see
    // `src/admin/context/*.rs`. Adding a new struct here is one line;
    // changing a field updates the source-of-truth alongside the type.
    CrapMeta::render_lua_annotation(out);
    UserContext::render_lua_annotation(out);
    Breadcrumb::render_lua_annotation(out);
    PageMeta::render_lua_annotation(out);
    NavCollection::render_lua_annotation(out);
    NavGlobal::render_lua_annotation(out);
    CustomPage::render_lua_annotation(out);
    NavData::render_lua_annotation(out);
    FieldAdminMeta::render_lua_annotation(out);
    FieldMeta::render_lua_annotation(out);
    AdminMeta::render_lua_annotation(out);
    UploadMeta::render_lua_annotation(out);
    VersionsMeta::render_lua_annotation(out);
    AuthMeta::render_lua_annotation(out);
    CollectionContext::render_lua_annotation(out);
    GlobalContext::render_lua_annotation(out);
    DocumentRef::render_lua_annotation(out);
    EditorLocaleOption::render_lua_annotation(out);
    BasePageContext::render_lua_annotation(out);
    RenderInfo::render_lua_annotation(out);

    out.push_str("---@alias crap.template_data_fn fun(ctx: crap.template_ctx): any\n\n");
}

/// Render type definitions for a single collection.
fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Sub-type classes (Array rows and Group shapes)
    for stf in collect_sub_type_fields(&col.fields, &pascal) {
        let sub_pascal = format!("{}{}", stf.parent_pascal, to_pascal_case(&stf.field.name));
        let namespace = match stf.kind {
            SubTypeKind::Array => "array_row",
            SubTypeKind::Group => "group",
        };
        w!(out, "---@class crap.{namespace}.{sub_pascal}");
        for sf in &stf.field.fields {
            write_field(out, sf, &sub_pascal);
        }
        out.push('\n');
    }

    // crap.data.* — hook ctx.data (mutable input). `id` and timestamps
    // are emitted as OPTIONAL because the table is reused across hooks
    // where they may or may not be populated (e.g. `before_validate`
    // on create has no id yet; `after_change` does). Optional types
    // let user code reach for `data.id` without LuaLS complaining,
    // while still flagging unconditional dereferences without a nil
    // check.
    w!(out, "---@class crap.data.{pascal}");
    w!(out, "---@field id? string");
    for f in &col.fields {
        write_field(out, f, &pascal);
    }
    if col.timestamps {
        w!(out, "---@field created_at? string");
        w!(out, "---@field updated_at? string");
    }
    out.push('\n');

    // crap.partial.* — partial-update payload (every field optional).
    // Used by `update` / `update_many`, which take only the fields
    // the caller wants to change. `crap.data.X` keeps required
    // fields required for the `create` path; this separate class
    // strips the requireds so partial updates don't trip the
    // `missing-fields` diagnostic.
    w!(out, "---@class crap.partial.{pascal}");
    for f in &col.fields {
        write_field_partial(out, f, &pascal);
    }
    out.push('\n');

    // crap.doc.* — returned document (id + timestamps). Inherits
    // from crap.Document so functions annotated `@return crap.Document`
    // (e.g. crap.collections.find_by_id, custom auth strategies)
    // accept the per-collection types without union-mismatch
    // diagnostics from lua-language-server.
    w!(out, "---@class crap.doc.{pascal} : crap.Document");
    w!(out, "---@field id string");
    for f in &col.fields {
        write_field(out, f, &pascal);
    }
    if col.timestamps {
        w!(out, "---@field created_at? string");
        w!(out, "---@field updated_at? string");
    }
    out.push('\n');

    // crap.hook.* — typed HookContext
    w!(out, "---@class crap.hook.{pascal}");
    w!(out, "---@field collection \"{}\"", col.slug);
    w!(
        out,
        "---@field operation \"create\" | \"update\" | \"find\" | \"find_by_id\""
    );
    w!(out, "---@field data crap.data.{pascal}");
    w!(out, "---@field context table<string, any>");
    w!(out, "---@field hook_depth integer");
    w!(out, "---@field locale? string");
    w!(out, "---@field draft? boolean");
    w!(out, "---@field user? table");
    w!(out, "---@field ui_locale? string");
    out.push('\n');

    // crap.find_result.* — MUST extend `crap.FindResult` (mirrors
    // `crap.doc.X : crap.Document`). Empirically, LuaLS narrows
    // `---@overload` returns reliably when every variant shares a
    // common parent — `find_by_id` narrows because every variant
    // returns `crap.doc.X : crap.Document`; `find` only narrows once
    // every variant returns `crap.find_result.X : crap.FindResult`.
    // Without inheritance, LuaLS treats the variants as ad-hoc
    // siblings and unions them at the call site.
    w!(out, "---@class crap.find_result.{pascal} : crap.FindResult");
    w!(out, "---@field documents crap.doc.{pascal}[]");
    out.push('\n');

    // hook function alias — one-liner `---@type` for collection hooks.
    w!(
        out,
        "---@alias crap.hook_fn.{pascal} fun(ctx: crap.hook.{pascal}): crap.hook.{pascal}"
    );

    // Field-hook function alias — typed per-collection so field hooks
    // can replace `@param value any` + `@param context …` + `@return`
    // with a single `---@type crap.field_hook_fn.<Pascal>` cast.
    w!(
        out,
        "---@alias crap.field_hook_fn.{pascal} fun(value: any, context: crap.field_hook.{pascal}): any"
    );

    // Display-condition function alias — returns either a boolean
    // (server-evaluated) or a condition table (client-evaluated).
    // See `docs/src/admin-ui/guides/display-conditions.md`.
    w!(
        out,
        "---@alias crap.display_condition_fn.{pascal} fun(data: crap.data.{pascal}, ctx: crap.ConditionContext): boolean | table"
    );
    out.push('\n');

    // crap.field_hook.* — typed FieldHookContext (data = full document)
    w!(out, "---@class crap.field_hook.{pascal}");
    w!(out, "---@field field_name string");
    w!(out, "---@field collection \"{}\"", col.slug);
    w!(out, "---@field operation string");
    w!(out, "---@field data crap.data.{pascal}");
    w!(out, "---@field user? table");
    w!(out, "---@field ui_locale? string");
    out.push('\n');

    // crap.where.* — typed filter keys. `(exact)` makes the class
    // closed so an unknown column name in a `where` table (e.g.
    // `where = { not_a_column = "x" }`) is flagged instead of being
    // silently accepted via Lua's default open-class shape. The
    // columns are the authoritative DB schema — anything outside the
    // list is a typo.
    let columns = get_column_names(col);
    w!(out, "---@class (exact) crap.where.{pascal}");
    for col_name in &columns {
        w!(out, "---@field {col_name}? crap.FilterValue");
    }
    out.push('\n');

    // crap.query.* — typed query options. Extends `crap.FindQuery` so
    // a `---@type crap.query.X` variable can be passed to the
    // `query?: crap.FindQuery` overload slot on `find` (LuaLS doesn't
    // duck-type class params, so inheritance is mandatory for the
    // assignment to type-check).
    //
    // Note on `(exact)`: even with `Lua.type.checkTableShape = true`,
    // LuaLS doesn't enforce exact-class validation on inline table
    // literals when the exact class is the parent of a non-exact one
    // or is reached via inheritance (LuaLS issue #2288). The
    // narrowing on `where` / `order_by` still drives autocomplete.
    // For strict where-key validation, users have to extract the
    // where table into a `---@type crap.where.X` local first.
    let order_by_union: Vec<String> = columns
        .iter()
        .flat_map(|c| [format!("\"{c}\""), format!("\"-{c}\"")])
        .collect();
    w!(
        out,
        "---@class (exact) crap.query.{pascal} : crap.FindQuery"
    );
    w!(out, "---@field where? crap.where.{pascal}");
    w!(out, "---@field order_by? {}", order_by_union.join("|"));
    w!(out, "---@field limit? integer");
    w!(out, "---@field offset? integer");
    w!(out, "---@field locale? string");
    out.push('\n');

    render_collection_accessor(out, &col.slug, &pascal);
    render_collection_typing_factories(out, col, &pascal);
}

/// Pass-through typing factories on per-collection accessors:
///
/// - `crap.collections.<slug>.hook(fn)` — collection hook, typed ctx.
/// - `crap.collections.<slug>.field_hook(fn)` — any-field, typed ctx.
/// - `crap.collections.<slug>.field_hook(field, fn)` — per-field
///   narrowing of `value` from the field-name literal.
/// - `crap.collections.<slug>.condition(fn)` — display condition,
///   typed data.
///
/// Each is a runtime no-op (`f(fn) = fn`); the value of these
/// factories is that `LuaLS`'s `Lua.type.inferParamType` propagates
/// `value`/`ctx`/`data` types into the function literal's body.
fn render_collection_typing_factories(out: &mut String, col: &CollectionDefinition, pascal: &str) {
    let slug = &col.slug;

    // Each block consolidated into one `format!` to keep the function
    // under the `too_many_lines` clippy threshold and to make the Lua
    // output legible at the source level. Multi-line string literals
    // preserve their content verbatim, so what's written here is what
    // ends up in `hooks.lua`.

    wraw!(
        out,
        "--- Define a lifecycle hook for the `{slug}` collection (`before_create`,
--- `after_update`, `before_delete`, etc. — registered via `crap.hooks.on(...)`).
--- The wrapper is a runtime no-op; its purpose is to narrow `ctx` to
--- `crap.hook.{pascal}` so `ctx.data.<field>` autocompletes.
---@param fn crap.hook_fn.{pascal}
---@return crap.hook_fn.{pascal}
function crap.collections.{slug}.hook(fn) end

"
    );

    // field_hook(field, fn) — per-field overloads + any-field + dynamic-slug fallback.
    for f in &col.fields {
        if !takes_field_hook(&f.field_type) {
            continue;
        }
        let value_type = field_to_lua_type(f, pascal);
        w!(
            out,
            "---@overload fun(field: \"{field}\", fn: fun(value: {value_type}, ctx: crap.field_hook.{pascal}): {value_type}?)",
            field = f.name,
        );
    }
    // Doc-prose comment lives below the overloads — LuaLS attaches the
    // prose adjacent to the `function ... end` decl to ALL overloads.
    wraw!(
        out,
        "---@overload fun(field: string, fn: crap.field_hook_fn.{pascal})
---@overload fun(fn: crap.field_hook_fn.{pascal})
--- Define a field hook for the `{slug}` collection. Two-arg form
--- (`field_hook(\"<field>\", fn)`) narrows `value` to the typed field;
--- single-arg form (`field_hook(fn)`) leaves `value` as `any`.
--- Use for value transformation (e.g. slug normalization, computed
--- defaults). Runtime no-op; LuaLS uses the signature to infer `value`
--- and `ctx: crap.field_hook.{pascal}`.
function crap.collections.{slug}.field_hook(field, fn) end

"
    );

    wraw!(
        out,
        "--- Display condition for an admin-UI field on the `{slug}` collection.
--- Return `true`/`false` for visible/hidden, or a table
--- `{{ visible = bool, error = string? }}` for richer control. Runtime
--- no-op; LuaLS narrows `data` to `crap.data.{pascal}`.
---@param fn crap.display_condition_fn.{pascal}
---@return crap.display_condition_fn.{pascal}
function crap.collections.{slug}.condition(fn) end

"
    );

    // access(fn) / auth_strategy(fn) — discoverable aliases for
    // `crap.any.access` / `crap.any.auth_strategy`. Context types are
    // uniform across collections so no per-collection narrowing is
    // possible, but surfacing them on the collection accessor makes
    // them findable via `crap.collections.<slug>.<TAB>` instead of
    // requiring users to know about the `crap.any` namespace upfront.
    wraw!(
        out,
        "--- Access-control function for `{slug}` operations. Return `true`/`false`
--- for global allow/deny, or a filter table to constrain results.
--- Runtime no-op; context type (`crap.AccessContext`) is uniform across
--- collections, so this is just a discoverable alias for `crap.any.access`.
---@param fn crap.access_fn
---@return crap.access_fn
function crap.collections.{slug}.access(fn) end

--- Custom auth-strategy `authenticate` callback for the `{slug}` collection.
--- Receives request headers + the slug; returns a user document on
--- success or `nil` to fall through. Runtime no-op; discoverable alias
--- for `crap.any.auth_strategy`.
---@param fn crap.auth_strategy_fn
---@return crap.auth_strategy_fn
function crap.collections.{slug}.auth_strategy(fn) end

--- Compute a display label for an array/blocks row on the `{slug}`
--- collection. Receives the row table and returns a string (or `nil`
--- to fall back to `label_field`). Runtime no-op; discoverable alias
--- for `crap.any.row_label`.
---@param fn crap.row_label_fn
---@return crap.row_label_fn
function crap.collections.{slug}.row_label(fn) end

"
    );
}

/// Render the per-collection accessor at `crap.collections.<slug>`.
/// Each method has the slug closed over at runtime (registered in
/// `hooks/init.rs`), so user code calls `crap.collections.inquiries
/// .find({...})` instead of `crap.collections.find("inquiries", {...})`.
/// The single-collection signature also avoids the `---@overload`
/// narrowing limitation that forced the parent API to take a
/// uniform `crap.FindQuery` — here the per-collection `crap.query.X`
/// can be the parameter type directly, so inline `where = { ... }`
/// tables get per-column autocomplete.
fn render_collection_accessor(out: &mut String, slug: &str, pascal: &str) {
    let local = format!("_coll_{slug}");
    w!(out, "---@class crap.collections.{pascal}");
    w!(out, "local {local} = {{}}");
    out.push('\n');

    // find
    w!(out, "---@param query? crap.query.{pascal}");
    w!(out, "---@return crap.find_result.{pascal}");
    w!(out, "function {local}.find(query) end");
    out.push('\n');

    // find_by_id
    w!(out, "---@param id string");
    w!(out, "---@param opts? crap.FindByIdOptions");
    w!(out, "---@return crap.doc.{pascal}?");
    w!(out, "function {local}.find_by_id(id, opts) end");
    out.push('\n');

    // create
    w!(out, "---@param data crap.data.{pascal}");
    w!(out, "---@param opts? crap.CreateOptions");
    w!(out, "---@return crap.doc.{pascal}");
    w!(out, "function {local}.create(data, opts) end");
    out.push('\n');

    // update — partial payload (only the fields being changed)
    w!(out, "---@param id string");
    w!(out, "---@param data crap.partial.{pascal}");
    w!(out, "---@param opts? crap.UpdateOptions");
    w!(out, "---@return crap.doc.{pascal}");
    w!(out, "function {local}.update(id, data, opts) end");
    out.push('\n');

    // delete
    w!(out, "---@param id string");
    w!(out, "---@param opts? crap.DeleteOptions");
    w!(out, "---@return boolean");
    w!(out, "function {local}.delete(id, opts) end");
    out.push('\n');

    // unpublish
    w!(out, "---@param id string");
    w!(out, "---@param opts? crap.UnpublishOptions");
    w!(out, "---@return crap.doc.{pascal}");
    w!(out, "function {local}.unpublish(id, opts) end");
    out.push('\n');

    // undelete
    w!(out, "---@param id string");
    w!(out, "---@param opts? crap.UndeleteOptions");
    w!(out, "---@return boolean");
    w!(out, "function {local}.undelete(id, opts) end");
    out.push('\n');

    // validate
    w!(out, "---@param data crap.data.{pascal}");
    w!(out, "---@param opts? crap.ValidateOptions");
    w!(out, "---@return crap.ValidateResult");
    w!(out, "function {local}.validate(data, opts) end");
    out.push('\n');

    // count
    w!(out, "---@param query? crap.CountQuery");
    w!(out, "---@return integer");
    w!(out, "function {local}.count(query) end");
    out.push('\n');

    // create_many
    w!(out, "---@param items crap.data.{pascal}[]");
    w!(out, "---@param opts? crap.CreateOptions");
    w!(out, "---@return crap.CreateManyResult");
    w!(out, "function {local}.create_many(items, opts) end");
    out.push('\n');

    // update_many — partial payload applied to every matched doc
    w!(out, "---@param query crap.UpdateManyQuery");
    w!(out, "---@param data crap.partial.{pascal}");
    w!(out, "---@param opts? crap.UpdateOptions");
    w!(out, "---@return crap.UpdateManyResult");
    w!(out, "function {local}.update_many(query, data, opts) end");
    out.push('\n');

    // delete_many
    w!(out, "---@param query crap.DeleteManyQuery");
    w!(out, "---@param opts? crap.DeleteOptions");
    w!(out, "---@return crap.DeleteManyResult");
    w!(out, "function {local}.delete_many(query, opts) end");
    out.push('\n');

    // list_versions
    w!(out, "---@param id string");
    w!(out, "---@param opts? crap.ListVersionsOptions");
    w!(out, "---@return crap.ListVersionsResult");
    w!(out, "function {local}.list_versions(id, opts) end");
    out.push('\n');

    // restore_version
    w!(out, "---@param id string");
    w!(out, "---@param version_id string");
    w!(out, "---@param opts? crap.RestoreVersionOptions");
    w!(out, "---@return crap.doc.{pascal}");
    w!(
        out,
        "function {local}.restore_version(id, version_id, opts) end"
    );
    out.push('\n');

    // ref_count
    w!(out, "---@param id string");
    w!(out, "---@return integer");
    w!(out, "function {local}.ref_count(id) end");
    out.push('\n');

    w!(
        out,
        "{} = {local}",
        crate::typegen::idents::lua_index("crap.collections", slug)
    );
    out.push('\n');
}

/// Render type definitions for a single global.
fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    // Sub-type classes (Array rows and Group shapes)
    for stf in collect_sub_type_fields(&global.fields, &pascal) {
        let sub_pascal = format!("{}{}", stf.parent_pascal, to_pascal_case(&stf.field.name));
        let namespace = match stf.kind {
            SubTypeKind::Array => "array_row",
            SubTypeKind::Group => "group",
        };
        w!(out, "---@class crap.{namespace}.{sub_pascal}");
        for sf in &stf.field.fields {
            write_field(out, sf, &sub_pascal);
        }
        out.push('\n');
    }

    // crap.global_data.* — hook ctx.data for globals. `id` and
    // timestamps are emitted optional for the same reason as
    // `crap.data.X`; see comment above.
    w!(out, "---@class crap.global_data.{pascal}");
    w!(out, "---@field id? string");
    for f in &global.fields {
        write_field(out, f, &pascal);
    }
    w!(out, "---@field created_at? string");
    w!(out, "---@field updated_at? string");
    out.push('\n');

    // crap.global_partial.* — partial-update payload for `update`.
    w!(out, "---@class crap.global_partial.{pascal}");
    for f in &global.fields {
        write_field_partial(out, f, &pascal);
    }
    out.push('\n');

    // crap.global_doc.* — always has timestamps. Same subclass
    // reasoning as `crap.doc.{pascal}` above.
    w!(out, "---@class crap.global_doc.{pascal} : crap.Document");
    w!(out, "---@field id string");
    for f in &global.fields {
        write_field(out, f, &pascal);
    }
    w!(out, "---@field created_at? string");
    w!(out, "---@field updated_at? string");
    out.push('\n');

    // crap.hook.global_*
    w!(out, "---@class crap.hook.global_{}", global.slug);
    w!(out, "---@field collection \"{}\"", global.slug);
    w!(out, "---@field operation \"update\" | \"get_global\"");
    w!(out, "---@field data crap.global_data.{pascal}");
    w!(out, "---@field context table<string, any>");
    w!(out, "---@field hook_depth integer");
    w!(out, "---@field locale? string");
    w!(out, "---@field draft? boolean");
    w!(out, "---@field user? table");
    w!(out, "---@field ui_locale? string");
    out.push('\n');

    // crap.field_hook.global_* — typed FieldHookContext for globals
    w!(out, "---@class crap.field_hook.global_{}", global.slug);
    w!(out, "---@field field_name string");
    w!(out, "---@field collection \"{}\"", global.slug);
    w!(out, "---@field operation string");
    w!(out, "---@field data crap.global_data.{pascal}");
    w!(out, "---@field user? table");
    w!(out, "---@field ui_locale? string");
    out.push('\n');

    // Function-type aliases for global hooks — same pattern as
    // collections: a `---@type` cast replaces 3+ annotation lines.
    w!(
        out,
        "---@alias crap.hook_fn.global_{slug} fun(ctx: crap.hook.global_{slug}): crap.hook.global_{slug}",
        slug = global.slug
    );
    w!(
        out,
        "---@alias crap.field_hook_fn.global_{slug} fun(value: any, context: crap.field_hook.global_{slug}): any",
        slug = global.slug
    );
    w!(
        out,
        "---@alias crap.display_condition_fn.global_{slug} fun(data: crap.global_data.{pascal}, ctx: crap.ConditionContext): boolean | table",
        slug = global.slug
    );
    out.push('\n');

    render_global_accessor(out, &global.slug, &pascal);
    render_global_typing_factories(out, global, &pascal);
}

/// Pass-through typing factories on per-global accessors. Mirrors
/// the per-collection variant — `hook`, `field_hook(field?, fn)`,
/// `condition` — all runtime no-ops, all giving `LuaLS` a typed
/// parameter slot for inference.
fn render_global_typing_factories(out: &mut String, global: &GlobalDefinition, pascal: &str) {
    let slug = &global.slug;

    // Same consolidation as the per-collection variant — see
    // `render_collection_typing_factories` for the rationale.

    wraw!(
        out,
        "--- Define a lifecycle hook for the `{slug}` global (`before_update`,
--- `after_update`, `before_read`, …). Runtime no-op; LuaLS narrows
--- `ctx` to `crap.hook.global_{slug}` so `ctx.data.<field>` autocompletes.
---@param fn crap.hook_fn.global_{slug}
---@return crap.hook_fn.global_{slug}
function crap.globals.{slug}.hook(fn) end

"
    );

    // field_hook(field, fn) — per-field overloads + any-field form.
    for f in &global.fields {
        if !takes_field_hook(&f.field_type) {
            continue;
        }
        let value_type = field_to_lua_type(f, pascal);
        w!(
            out,
            "---@overload fun(field: \"{field}\", fn: fun(value: {value_type}, ctx: crap.field_hook.global_{slug}): {value_type}?)",
            field = f.name,
        );
    }
    wraw!(
        out,
        "---@overload fun(field: string, fn: crap.field_hook_fn.global_{slug})
---@overload fun(fn: crap.field_hook_fn.global_{slug})
--- Define a field hook for the `{slug}` global. Two-arg form narrows
--- `value` to the typed field; single-arg form leaves it as `any`.
--- Runtime no-op; LuaLS uses the signature to infer `value` and
--- `ctx: crap.field_hook.global_{slug}`.
function crap.globals.{slug}.field_hook(field, fn) end

--- Display condition for an admin-UI field on the `{slug}` global.
--- Return `true`/`false`, or a `{{ visible, error }}` table. Runtime
--- no-op; LuaLS narrows `data` to `crap.global_data.{pascal}`.
---@param fn crap.display_condition_fn.global_{slug}
---@return crap.display_condition_fn.global_{slug}
function crap.globals.{slug}.condition(fn) end

--- Access-control function for `{slug}` global operations. Return
--- `true`/`false` or a filter table. Runtime no-op; discoverable alias
--- for `crap.any.access`.
---@param fn crap.access_fn
---@return crap.access_fn
function crap.globals.{slug}.access(fn) end

--- Compute a display label for an array/blocks row on the `{slug}`
--- global. Returns a string (or `nil` to fall back to `label_field`).
--- Runtime no-op; discoverable alias for `crap.any.row_label`.
---@param fn crap.row_label_fn
---@return crap.row_label_fn
function crap.globals.{slug}.row_label(fn) end

"
    );
}

/// Per-global accessor at `crap.globals.<slug>`. Slug-less
/// `get(opts?)` / `update(data, opts?)` / `unpublish(opts?)` /
/// `validate(data, opts?)` with typed returns — no overload
/// narrowing concerns. Runtime-registered in `hooks/init.rs` to
/// dispatch to the slug-keyed `crap.globals.*` functions.
fn render_global_accessor(out: &mut String, slug: &str, pascal: &str) {
    let local = format!("_glob_{slug}");
    w!(out, "---@class crap.globals.{pascal}");
    w!(out, "local {local} = {{}}");
    out.push('\n');

    // get
    w!(out, "---@param opts? crap.GlobalGetOptions");
    w!(out, "---@return crap.global_doc.{pascal}");
    w!(out, "function {local}.get(opts) end");
    out.push('\n');

    // update — partial payload
    w!(out, "---@param data crap.global_partial.{pascal}");
    w!(out, "---@param opts? crap.GlobalUpdateOptions");
    w!(out, "---@return crap.global_doc.{pascal}");
    w!(out, "function {local}.update(data, opts) end");
    out.push('\n');

    // unpublish — versioned globals only (runtime-errors otherwise)
    w!(out, "---@param opts? crap.GlobalUnpublishOptions");
    w!(out, "---@return crap.global_doc.{pascal}");
    w!(out, "function {local}.unpublish(opts) end");
    out.push('\n');

    // validate — dry-run against the singleton row
    w!(out, "---@param data crap.global_partial.{pascal}");
    w!(out, "---@param opts? crap.GlobalValidateOptions");
    w!(out, "---@return crap.ValidateResult");
    w!(out, "function {local}.validate(data, opts) end");
    out.push('\n');

    w!(out, "crap.globals.{slug} = {local}");
    out.push('\n');
}

/// Render typed overload annotations for find/findById/create/update.
fn render_find_overloads(out: &mut String, registry: &Registry) {
    let mut slugs: Vec<&Slug> = registry.collections.keys().collect();
    slugs.sort();

    if slugs.is_empty() {
        return;
    }

    // find() / find_by_id() — emitted as `---@overload`-only blocks
    // with NO `---@param`/`---@return` between overloads. This is
    // the exact shape PR #2838 in lua-language-server targets: when a
    // function has only `@overload`s and no explicit param/return,
    // LuaLS ignores the auto-inferred baseline (nil) and dispatches
    // to the matching overload's return for literal-typed args.
    //
    // Reference test case from the PR:
    //   ---@overload fun(a: 1): string
    //   ---@overload fun(a: 2): number
    //   local function f(a) end
    //   local r = f(1)  -- now narrows to `string`
    //
    // The final `string` overload is the dynamic-slug fallback.
    // Use uniform `crap.FindQuery` as the query type for every
    // overload. LuaLS only narrows `---@overload` reliably when
    // exactly one parameter type varies across the overload set.
    // When `find` had both `collection` (literal `"slug"`) AND
    // `query` (per-collection `crap.query.X`) varying, LuaLS unioned
    // every overload's return at the call site and `result.documents`
    // dissolved into `crap.Document | crap.doc.<every>[]`. Fixing
    // `query` to the base type leaves only the literal `collection`
    // varying — same shape as `find_by_id` — and narrowing kicks in.
    //
    // Users who want per-collection `where` / `order_by` autocomplete
    // can still construct a typed query:
    //   ---@type crap.query.Inquiries
    //   local q = { where = { status = "archived" } }
    //   local r = crap.collections.find("inquiries", q)
    // `crap.query.X` extends `crap.FindQuery`, so the typed variable
    // satisfies the uniform overload slot AND narrows on field
    // access. The result still narrows to `crap.find_result.X`.
    for slug in &slugs {
        let pascal = to_pascal_case(slug);
        w!(
            out,
            "---@overload fun(collection: \"{slug}\", query?: crap.FindQuery): crap.find_result.{pascal}"
        );
    }
    w!(
        out,
        "---@overload fun(collection: string, query?: crap.FindQuery): crap.FindResult"
    );
    w!(out, "function crap.collections.find(collection, query) end");
    out.push('\n');

    for slug in &slugs {
        let pascal = to_pascal_case(slug);
        w!(
            out,
            "---@overload fun(collection: \"{slug}\", id: string, opts?: crap.FindByIdOptions): crap.doc.{pascal}?"
        );
    }
    w!(
        out,
        "---@overload fun(collection: string, id: string, opts?: crap.FindByIdOptions): crap.Document?"
    );
    w!(
        out,
        "function crap.collections.find_by_id(collection, id, opts) end"
    );
    out.push('\n');
}

#[cfg(test)]
mod tests {
    use super::super::test_helpers::{checkbox_field, select_field, text_field};
    use super::*;
    use crate::core::{FieldDefinition, FieldTab, FieldType, RelationshipConfig};

    #[test]
    fn render_collection_output() {
        let mut col = CollectionDefinition::new("posts");
        col.timestamps = true;
        col.fields = vec![
            text_field("title", true),
            text_field("content", false),
            select_field("status", true, &["draft", "published"]),
            checkbox_field("active"),
        ];

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("---@class crap.data.Posts"));
        assert!(out.contains("---@field title string"));
        assert!(out.contains("---@field content? string"));
        assert!(out.contains("---@field status \"draft\" | \"published\""));
        assert!(out.contains("---@field active? boolean"));
        assert!(out.contains("---@class crap.doc.Posts : crap.Document"));
        assert!(out.contains("---@field id string"));
        assert!(out.contains("---@field created_at? string"));
        assert!(out.contains("---@field updated_at? string"));
        assert!(out.contains("---@class crap.hook.Posts"));
        assert!(out.contains("---@field collection \"posts\""));
        assert!(out.contains("---@field data crap.data.Posts"));
        assert!(
            out.contains("---@field hook_depth integer"),
            "hook context should have hook_depth"
        );
        assert!(
            out.contains("---@field draft? boolean"),
            "hook context should have draft"
        );
        assert!(
            out.contains("---@field context table<string, any>"),
            "hook context should have context"
        );
        assert!(out.contains("---@class crap.find_result.Posts"));
        assert!(out.contains("---@field documents crap.doc.Posts[]"));
        assert!(out.contains("---@alias crap.hook_fn.Posts"));
        assert!(out.contains("---@class crap.field_hook.Posts"));
        assert!(out.contains("---@field data crap.data.Posts"));
        assert!(out.contains("---@field field_name string"));
        assert!(out.contains("---@class (exact) crap.where.Posts"));
        assert!(out.contains("---@class (exact) crap.query.Posts : crap.FindQuery"));
    }

    #[test]
    fn render_collection_no_timestamps() {
        let mut col = CollectionDefinition::new("tags");
        col.timestamps = false;
        col.fields = vec![text_field("name", true)];

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("---@class crap.doc.Tags : crap.Document"));
        assert!(!out.contains("created_at"));
    }

    #[test]
    fn render_global_output() {
        let mut global = GlobalDefinition::new("site_settings");
        global.fields = vec![text_field("site_name", true), text_field("tagline", false)];

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(out.contains("---@class crap.global_data.SiteSettings"));
        assert!(out.contains("---@field site_name string"));
        assert!(out.contains("---@field tagline? string"));
        assert!(out.contains("---@class crap.global_doc.SiteSettings : crap.Document"));
        assert!(out.contains("---@class crap.hook.global_site_settings"));
        assert!(out.contains("---@class crap.field_hook.global_site_settings"));

        // Accessor binds all four CRUD-ish methods, matching the runtime
        // GLOBAL_METHODS list (get/update/unpublish/validate).
        assert!(out.contains("function _glob_site_settings.get(opts) end"));
        assert!(out.contains("function _glob_site_settings.update(data, opts) end"));
        assert!(out.contains("function _glob_site_settings.unpublish(opts) end"));
        assert!(out.contains("function _glob_site_settings.validate(data, opts) end"));
    }

    #[test]
    fn hook_context_has_user_and_ui_locale() {
        let mut col = CollectionDefinition::new("posts");
        col.fields = vec![text_field("title", true)];

        let mut out = String::new();
        render_collection(&mut out, &col);

        // crap.hook.* must include user and ui_locale (set at runtime)
        assert!(out.contains("---@class crap.hook.Posts"));
        assert!(
            out.contains("---@field user? table"),
            "hook context missing user field:\n{out}"
        );
        assert!(
            out.contains("---@field ui_locale? string"),
            "hook context missing ui_locale field:\n{out}"
        );

        // crap.field_hook.* must also include them
        assert!(out.contains("---@class crap.field_hook.Posts"));
        // Count to verify both hook and field_hook have user/ui_locale
        assert_eq!(
            out.matches("---@field user? table").count(),
            2,
            "both hook and field_hook need user"
        );
        assert_eq!(
            out.matches("---@field ui_locale? string").count(),
            2,
            "both hook and field_hook need ui_locale"
        );
    }

    #[test]
    fn global_hook_context_uses_collection_field() {
        let mut global = GlobalDefinition::new("site_settings");
        global.fields = vec![text_field("site_name", true)];

        let mut out = String::new();
        render_global(&mut out, &global);

        // Runtime sets "collection" not "global" — verify generated types match
        assert!(out.contains("---@class crap.hook.global_site_settings"));
        assert!(
            out.contains("---@field collection \"site_settings\""),
            "global hook context must use 'collection' field (matching runtime), got:\n{out}"
        );
        assert!(
            !out.contains("---@field global"),
            "global hook context must NOT use 'global' field"
        );

        // user and ui_locale must be present
        assert!(out.contains("---@field user? table"));
        assert!(out.contains("---@field ui_locale? string"));
    }

    #[test]
    fn render_global_array_row() {
        let mut global = GlobalDefinition::new("navigation");
        global.fields = vec![
            FieldDefinition::builder("main_nav", FieldType::Array)
                .fields(vec![text_field("label", true), text_field("url", true)])
                .build(),
        ];

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(
            out.contains("---@class crap.array_row.NavigationMainNav"),
            "global array should emit prefixed sub-type class, got:\n{out}"
        );
        assert!(out.contains("---@field label string"));
    }

    /// Regression: a nested array inside an array row must reference
    /// the inner sub-type by its compound parent path (e.g.
    /// `NavigationMainNavChildren`) AND emit a matching declaration at
    /// the same name. Previously the declaration used only the outer
    /// global's `PascalCase` (e.g. `NavigationChildren`), leaving the
    /// reference dangling with an "`Undefined` type" `LuaLS` warning.
    #[test]
    fn render_global_nested_array_row_name_matches_reference() {
        let mut global = GlobalDefinition::new("navigation");
        global.fields = vec![
            FieldDefinition::builder("main_nav", FieldType::Array)
                .fields(vec![
                    text_field("label", true),
                    FieldDefinition::builder("children", FieldType::Array)
                        .fields(vec![text_field("url", true)])
                        .build(),
                ])
                .build(),
        ];

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(
            out.contains("---@class crap.array_row.NavigationMainNav"),
            "outer array sub-type class missing, got:\n{out}"
        );
        assert!(
            out.contains("---@class crap.array_row.NavigationMainNavChildren"),
            "nested array sub-type class must carry the compound parent path, got:\n{out}"
        );
        assert!(
            out.contains("---@field children? crap.array_row.NavigationMainNavChildren[]"),
            "outer row must reference the inner sub-type by its compound name, got:\n{out}"
        );
        assert!(
            !out.contains("---@class crap.array_row.NavigationChildren\n"),
            "must not emit the bare (un-compounded) inner sub-type name, got:\n{out}"
        );
    }

    #[test]
    fn render_global_hook_context_fields() {
        let mut global = GlobalDefinition::new("footer");
        global.fields = vec![text_field("copyright", true)];

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(
            out.contains("---@field hook_depth integer"),
            "global hook context should have hook_depth"
        );
        assert!(
            out.contains("---@field draft? boolean"),
            "global hook context should have draft"
        );
        assert!(
            out.contains("---@field context table<string, any>"),
            "global hook context should have context"
        );
    }

    #[test]
    fn render_sorted_output() {
        let mut registry = Registry::new();
        let mut zebras = CollectionDefinition::new("zebras");
        zebras.timestamps = true;
        registry.register_collection(zebras);
        let mut apples = CollectionDefinition::new("apples");
        apples.timestamps = true;
        registry.register_collection(apples);

        let output = render(&registry);
        let apples_pos = output.find("crap.data.Apples").expect("write to String");
        let zebras_pos = output.find("crap.data.Zebras").expect("write to String");
        assert!(apples_pos < zebras_pos);
    }

    #[test]
    fn render_find_overloads_output() {
        let mut registry = Registry::new();
        let mut posts = CollectionDefinition::new("posts");
        posts.timestamps = true;
        posts.fields = vec![text_field("title", true)];
        registry.register_collection(posts);
        let mut pages = CollectionDefinition::new("pages");
        pages.timestamps = true;
        pages.fields = vec![text_field("body", false)];
        registry.register_collection(pages);

        let output = render(&registry);
        assert!(output.contains("---@overload fun(collection: \"pages\""));
        assert!(output.contains("---@overload fun(collection: \"posts\""));
        assert!(output.contains("function crap.collections.find(collection, query) end"));
        // find_by_id overloads
        assert!(output.contains(
            "fun(collection: \"posts\", id: string, opts?: crap.FindByIdOptions): crap.doc.Posts?"
        ));
        assert!(output.contains("function crap.collections.find_by_id(collection, id, opts) end"));
    }

    #[test]
    fn render_find_overloads_empty_registry() {
        let registry = Registry::new();
        let output = render(&registry);
        assert!(!output.contains("crap.collections.find"));
    }

    #[test]
    fn lua_polymorphic_comment_emitted() {
        let mut rc = RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".into(), "pages".into()];
        let mut col = CollectionDefinition::new("comments");
        col.fields = vec![
            FieldDefinition::builder("subject", FieldType::Relationship)
                .required(true)
                .relationship(rc)
                .build(),
        ];
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("Polymorphic relationship"),
            "should have polymorphic comment: {out}"
        );
        assert!(
            out.contains("posts"),
            "comment should list target collections: {out}"
        );
        assert!(
            out.contains("pages"),
            "comment should list target collections: {out}"
        );
    }

    #[test]
    fn render_collection_with_array_subtype() {
        let mut col = CollectionDefinition::new("posts");
        col.fields = vec![
            FieldDefinition::builder("items", FieldType::Array)
                .fields(vec![text_field("label", true), text_field("desc", false)])
                .build(),
        ];
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("---@class crap.array_row.PostsItems"));
        assert!(out.contains("---@field label string"));
        assert!(out.contains("---@field desc? string"));
    }

    #[test]
    fn lua_row_collapsible_tabs_promote_subfields() {
        let mut col = CollectionDefinition::new("items");
        col.fields = vec![
            FieldDefinition::builder("layout_row", FieldType::Row)
                .fields(vec![
                    text_field("first_name", true),
                    text_field("last_name", false),
                ])
                .build(),
            FieldDefinition::builder("details", FieldType::Collapsible)
                .fields(vec![text_field("bio", false)])
                .build(),
            FieldDefinition::builder("sections", FieldType::Tabs)
                .tabs(vec![FieldTab::new(
                    "Tab1",
                    vec![text_field("tab_field", true)],
                )])
                .build(),
        ];
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Row sub-fields promoted — "layout_row" should not appear as a @field
        assert!(
            !out.contains("@field layout_row"),
            "row field name should not appear: {out}"
        );
        assert!(
            out.contains("---@field first_name string"),
            "row required sub-field promoted: {out}"
        );
        assert!(
            out.contains("---@field last_name? string"),
            "row optional sub-field promoted: {out}"
        );
        // Collapsible sub-fields promoted
        assert!(
            !out.contains("@field details"),
            "collapsible field name should not appear: {out}"
        );
        assert!(
            out.contains("---@field bio? string"),
            "collapsible sub-field promoted: {out}"
        );
        // Tabs sub-fields promoted
        assert!(
            !out.contains("@field sections"),
            "tabs field name should not appear: {out}"
        );
        assert!(
            out.contains("---@field tab_field string"),
            "tabs sub-field promoted: {out}"
        );
    }

    #[test]
    fn lua_group_subtype_emitted_in_collection() {
        let mut col = CollectionDefinition::new("posts");
        col.fields = vec![
            FieldDefinition::builder("seo", FieldType::Group)
                .fields(vec![
                    text_field("title", true),
                    text_field("description", false),
                ])
                .build(),
        ];
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("---@class crap.group.PostsSeo"),
            "group sub-type class should be emitted with collection prefix: {out}"
        );
        assert!(
            out.contains("---@field title string"),
            "group sub-field: {out}"
        );
        assert!(
            out.contains("---@field description? string"),
            "group sub-field optional: {out}"
        );
    }

    /// Regression: two collections with identically-named array fields must
    /// produce distinct sub-type class names (prefixed with the collection's
    /// `PascalCase` name) so they don't collide.
    #[test]
    fn array_subtype_names_prefixed_with_collection_name() {
        let mut posts = CollectionDefinition::new("posts");
        posts.fields = vec![
            FieldDefinition::builder("items", FieldType::Array)
                .fields(vec![text_field("label", true)])
                .build(),
        ];

        let mut pages = CollectionDefinition::new("pages");
        pages.fields = vec![
            FieldDefinition::builder("items", FieldType::Array)
                .fields(vec![text_field("url", true)])
                .build(),
        ];

        let mut posts_out = String::new();
        render_collection(&mut posts_out, &posts);

        let mut pages_out = String::new();
        render_collection(&mut pages_out, &pages);

        // Each collection should produce a uniquely-prefixed class name
        assert!(
            posts_out.contains("---@class crap.array_row.PostsItems"),
            "posts sub-type should be PostsItems, got:\n{posts_out}"
        );
        assert!(
            pages_out.contains("---@class crap.array_row.PagesItems"),
            "pages sub-type should be PagesItems, got:\n{pages_out}"
        );

        // The two class names must be different
        assert!(
            posts_out.contains("PostsItems"),
            "posts class name must exist"
        );
        assert!(
            pages_out.contains("PagesItems"),
            "pages class name must exist"
        );
    }

    #[test]
    fn lua_group_subtype_emitted_in_global() {
        let mut global = GlobalDefinition::new("settings");
        global.fields = vec![
            FieldDefinition::builder("seo", FieldType::Group)
                .fields(vec![text_field("title", true)])
                .build(),
        ];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(
            out.contains("---@class crap.group.SettingsSeo"),
            "global group sub-type should be prefixed: {out}"
        );
    }

    #[test]
    fn lua_array_nested_in_row_emits_subtype() {
        let mut col = CollectionDefinition::new("posts");
        col.fields = vec![
            FieldDefinition::builder("layout", FieldType::Row)
                .fields(vec![
                    FieldDefinition::builder("items", FieldType::Array)
                        .fields(vec![text_field("val", true)])
                        .build(),
                ])
                .build(),
            FieldDefinition::builder("tabs", FieldType::Tabs)
                .tabs(vec![FieldTab::new(
                    "T",
                    vec![
                        FieldDefinition::builder("tab_items", FieldType::Array)
                            .fields(vec![text_field("name", true)])
                            .build(),
                    ],
                )])
                .build(),
        ];
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("---@class crap.array_row.PostsItems"),
            "array inside Row should emit sub-type with collection prefix: {out}"
        );
        assert!(
            out.contains("---@class crap.array_row.PostsTabItems"),
            "array inside Tabs should emit sub-type with collection prefix: {out}"
        );
    }
}
