//! The TypeScript printer: documents, their `…Data` inputs, sub-types, and the
//! collection-slug union.

use crate::{
    core::Registry,
    typegen::{
        client::{ClientPrinter, Document, EnumDef, PolyDef, SubType, writer::CodeWriter},
        helpers::sorted_collection_slugs,
        idents,
    },
};

use super::types::{emit_input_field, emit_property, emit_read_field, ts_ty};

/// Emits TypeScript type definitions.
pub(in crate::typegen::client) struct TsPrinter {
    w: CodeWriter,
}

impl TsPrinter {
    pub(in crate::typegen::client) fn new() -> Self {
        Self {
            w: CodeWriter::new("  "),
        }
    }

    /// Emit a read document: `id`, every field optional and nullable, then the
    /// stored system keys, the populated `collection` tag, and timestamps.
    fn read_interface(&mut self, name: &str, def: &Document) {
        let (fields, system, tag) = (&def.fields, &def.system, &def.collection_tag);
        let timestamps = def.timestamps;

        self.interface(name, |w| {
            w.line("id: string;");
            for f in fields.iter().chain(system) {
                emit_read_field(w, f);
            }
            if let Some(tag) = tag {
                w.line("/** Set when the document is embedded as a populated relationship */");
                emit_property(w, tag, true, &ts_ty(&tag.ty));
            }
            if timestamps {
                w.line("created_at?: string;");
                w.line("updated_at?: string;");
            }
        });
    }

    /// Emit `export interface NAME { <body> }` followed by a blank line.
    fn interface(&mut self, name: &str, body: impl FnOnce(&mut CodeWriter)) {
        self.w
            .block(&format!("export interface {name} {{"), "}", body);
        self.w.blank();
    }
}

impl ClientPrinter for TsPrinter {
    fn prelude(&mut self) {
        self.w.line("// Auto-generated by crap-cms. Do not edit.");
        self.w.blank();
        self.w.line(
            "/** A localized field read with `locale = \"all\"`: one value per locale code, `null` where a locale has none. */",
        );
        self.w
            .line("export type Localized<T> = { [locale: string]: T | null };");
        self.w.blank();
    }

    /// A write-shape sub-type is its input variant (`…Data`, required fields
    /// kept, references as ids); a read sub-type makes every field optional
    /// and nullable.
    fn sub_type(&mut self, def: &SubType) {
        let name = idents::ts_type(&def.name);
        let fields = &def.fields;

        if def.input {
            self.interface(&format!("{name}Data"), |w| {
                for f in fields {
                    emit_input_field(w, f);
                }
            });
            return;
        }

        self.interface(&name, |w| {
            for f in fields {
                emit_read_field(w, f);
            }
        });
    }

    fn document(&mut self, def: &Document) {
        let pascal = idents::ts_type(&def.name);

        if def.localized {
            self.w.line(&format!(
                "/** {pascal} read with `locale = \"all\"`: localized fields hold one value per locale */"
            ));
            self.read_interface(&format!("{pascal}LocalizedDocument"), def);
            return;
        }

        let data_doc = if def.is_global {
            format!("/** Input data for the {pascal} global; an update accepts any subset */")
        } else {
            format!(
                "/** Input data for creating a {pascal}; an update accepts any subset (`Partial<{pascal}Data>`) */"
            )
        };
        self.w.line(&data_doc);
        let fields = &def.input;
        self.interface(&format!("{pascal}Data"), |w| {
            for f in fields {
                emit_input_field(w, f);
            }
        });

        let doc_doc = if def.is_global {
            format!("/** {pascal} global document */")
        } else {
            format!("/** {pascal} document returned from the API */")
        };
        self.w.line(&doc_doc);
        self.read_interface(&format!("{pascal}Document"), def);
    }

    // Select/radio narrowing and polymorphic unions are inlined at each use site.
    fn enum_types(&mut self, _defs: &[EnumDef]) {}

    fn poly_types(&mut self, _defs: &[PolyDef]) {}

    fn epilogue(&mut self, registry: &Registry) {
        let slugs = sorted_collection_slugs(registry);
        if slugs.is_empty() {
            return;
        }
        let union = slugs
            .iter()
            .map(|s| format!("\"{s}\""))
            .collect::<Vec<_>>()
            .join(" | ");
        self.w.line("/** All collection slugs */");
        self.w
            .line(&format!("export type CollectionSlug = {union};"));
    }

    fn finish(self: Box<Self>) -> String {
        self.w.finish()
    }
}

#[cfg(test)]
mod tests {
    use super::super::test_helpers::{
        code_with_languages, interface_block, make_col, render, render_collection, render_global,
        select_field, text_field,
    };
    use super::*;
    use crate::core::{FieldDefinition, FieldTab, FieldType, GlobalDefinition, VersionsConfig};

    /// A read document may lack any field — a draft may miss required values,
    /// and field read access and `select` leave keys out — so every field of
    /// the document, and of its sub-types, is optional. The create input keeps
    /// its required fields, nested ones included: its sub-types are the `…Data`
    /// variants.
    #[test]
    fn typescript_read_document_fields_are_optional() {
        let col = make_col(
            "posts",
            vec![
                text_field("title", true),
                FieldDefinition::builder("seo", FieldType::Group)
                    .fields(vec![text_field("meta_title", true)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        let doc = interface_block(&out, "export interface PostsDocument {");
        assert!(doc.contains("  title?: string | null;"), "{doc}");
        assert!(doc.contains("  seo?: PostsSeo | null;"), "{doc}");

        let seo = interface_block(&out, "export interface PostsSeo {");
        assert!(seo.contains("  meta_title?: string | null;"), "{seo}");

        let data = interface_block(&out, "export interface PostsData {");
        assert!(data.contains("  title: string;"), "{data}");
        assert!(data.contains("  seo?: PostsSeoData;"), "{data}");
        assert!(out.contains("/** Input data for creating a Posts"), "{out}");

        let seo_input = interface_block(&out, "export interface PostsSeoData {");
        assert!(seo_input.contains("  meta_title: string;"), "{seo_input}");
    }

    /// A read document carries the stored system keys its collection has, and
    /// a timezone date's `<name>_tz` companion (also accepted as input).
    #[test]
    fn typescript_read_document_has_system_keys() {
        let mut col = make_col(
            "events",
            vec![
                FieldDefinition::builder("starts", FieldType::Date)
                    .timezone(true)
                    .build(),
            ],
        );
        col.soft_delete = true;
        col.versions = Some(VersionsConfig::new(true, 10));
        let mut out = String::new();
        render_collection(&mut out, &col);

        let doc = interface_block(&out, "export interface EventsDocument {");
        assert!(
            doc.contains("  _status?: \"draft\" | \"published\" | null;"),
            "{doc}"
        );
        assert!(doc.contains("  _deleted_at?: string | null;"), "{doc}");
        assert!(doc.contains("  starts_tz?: string | null;"), "{doc}");

        let data = interface_block(&out, "export interface EventsData {");
        assert!(data.contains("  starts_tz?: string;"), "{data}");
        assert!(!data.contains("_status"), "{data}");
    }

    /// Under `locale = "all"` a localized code field's language pick is a
    /// per-locale map, like its value.
    #[test]
    fn typescript_localized_code_language_companion_is_per_locale() {
        let mut snippet = code_with_languages("snippet");
        snippet.localized = true;
        let col = make_col("snippets", vec![snippet]);
        let mut out = String::new();
        render_collection(&mut out, &col);

        let doc = interface_block(&out, "export interface SnippetsLocalizedDocument {");
        assert!(
            doc.contains("  snippet_lang?: Localized<string> | null;"),
            "{doc}"
        );
    }

    /// A `locale = "all"` read returns each localized field as a per-locale
    /// map; the localized document types it so, through localized groups too.
    #[test]
    fn typescript_localized_document_wraps_localized_fields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("title", FieldType::Text)
                    .localized(true)
                    .build(),
                text_field("slug", true),
                FieldDefinition::builder("seo", FieldType::Group)
                    .localized(true)
                    .fields(vec![text_field("meta_title", true)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(
            out.contains("export type Localized<T> = { [locale: string]: T | null };"),
            "{out}"
        );

        let doc = interface_block(&out, "export interface PostsLocalizedDocument {");
        assert!(doc.contains("  title?: Localized<string> | null;"), "{doc}");
        assert!(doc.contains("  slug?: string | null;"), "{doc}");
        assert!(doc.contains("  seo?: PostsSeoLocalized | null;"), "{doc}");

        let seo = interface_block(&out, "export interface PostsSeoLocalized {");
        assert!(
            seo.contains("  meta_title?: Localized<string> | null;"),
            "{seo}"
        );
    }

    #[test]
    fn typescript_no_localized_document_without_localized_fields() {
        let col = make_col("posts", vec![text_field("title", true)]);
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(!out.contains("LocalizedDocument"), "{out}");
    }

    #[test]
    fn typescript_collection_output() {
        let col = make_col(
            "posts",
            vec![
                text_field("title", true),
                text_field("content", false),
                select_field("status", &["draft", "published"]),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("export interface PostsData {"));
        assert!(out.contains("  title: string;"));
        assert!(out.contains("  content?: string;"));
        assert!(out.contains("  status: \"draft\" | \"published\";"));
        assert!(out.contains("export interface PostsDocument {"));
        assert!(out.contains("  id: string;"));
        assert!(out.contains("  created_at?: string;"));
        assert!(out.contains("  updated_at?: string;"));
    }

    #[test]
    fn typescript_global_output() {
        let mut global = GlobalDefinition::new("site_settings");
        global.fields = vec![text_field("site_name", true)];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(out.contains("export interface SiteSettingsData {"));
        assert!(out.contains("export interface SiteSettingsDocument {"));
    }

    #[test]
    fn typescript_array_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![text_field("label", true), text_field("value", false)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("export interface PostsItems {"));
        assert!(out.contains("  label?: string | null;"));
        assert!(out.contains("  value?: string | null;"));
        assert!(out.contains("PostsItems[]"));
    }

    /// A relational array's rows carry their junction `id` — read it, and send
    /// it back so an update keeps the row — while a row nested in another row is
    /// JSON without one.
    #[test]
    fn typescript_array_rows_carry_their_id() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![
                        text_field("label", true),
                        FieldDefinition::builder("notes", FieldType::Array)
                            .fields(vec![text_field("body", false)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        let row = interface_block(&out, "export interface PostsItems {");
        assert!(row.contains("  id?: string | null;"), "{row}");
        let input = interface_block(&out, "export interface PostsItemsData {");
        assert!(input.contains("  id?: string;"), "{input}");
        let nested = interface_block(&out, "export interface PostsItemsNotes {");
        assert!(!nested.contains("id?"), "{nested}");
    }

    #[test]
    fn typescript_nested_group_in_array_uses_compound_pascal() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![
                        FieldDefinition::builder("meta", FieldType::Group)
                            .fields(vec![text_field("title", true)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("export interface PostsItemsMeta {"),
            "nested group compound pascal: {out}"
        );
        assert!(
            out.contains("PostsItemsMeta | null;"),
            "body references it: {out}"
        );
        assert!(!out.contains("PostsMeta"), "no wrong name: {out}");
    }

    #[test]
    fn typescript_array_without_subfields() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("data", FieldType::Array).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Record<string, unknown>[]"));
    }

    #[test]
    fn typescript_group_field_empty() {
        let col = make_col(
            "items",
            vec![FieldDefinition::builder("seo", FieldType::Group).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Record<string, unknown>"));
    }

    #[test]
    fn typescript_group_field_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("seo", FieldType::Group)
                    .fields(vec![
                        text_field("title", true),
                        text_field("description", false),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("export interface PostsSeo {"),
            "sub-type: {out}"
        );
        assert!(out.contains("  title?: string | null;"), "sub-field: {out}");
        assert!(
            out.contains("  description?: string | null;"),
            "optional sub: {out}"
        );
        assert!(out.contains("PostsSeo"), "reference: {out}");
    }

    #[test]
    fn typescript_collection_slug_type() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        registry.register_collection(make_col("pages", vec![text_field("body", true)]));
        let out = render(&registry);
        assert!(out.contains("export type CollectionSlug = \"pages\" | \"posts\";"));
    }

    #[test]
    fn typescript_collection_slug_type_empty() {
        let registry = Registry::new();
        let out = render(&registry);
        assert!(!out.contains("CollectionSlug"));
    }

    #[test]
    fn typescript_no_timestamps() {
        let mut col = make_col("tags", vec![text_field("name", true)]);
        col.timestamps = false;
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(!out.contains("created_at"));
        assert!(!out.contains("updated_at"));
    }

    #[test]
    fn typescript_row_collapsible_tabs_promote_subfields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("layout_row", FieldType::Row)
                    .fields(vec![
                        text_field("first_name", true),
                        text_field("last_name", false),
                    ])
                    .build(),
                FieldDefinition::builder("details", FieldType::Collapsible)
                    .fields(vec![text_field("bio", false)])
                    .build(),
                FieldDefinition::builder("sections", FieldType::Tabs)
                    .tabs(vec![FieldTab::new(
                        "Tab1",
                        vec![text_field("tab_field", true)],
                    )])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(!out.contains("layout_row:"), "row name not a key: {out}");
        assert!(
            out.contains("  first_name: string;"),
            "row sub promoted: {out}"
        );
        assert!(
            out.contains("  last_name?: string;"),
            "row optional sub: {out}"
        );
        assert!(
            !out.contains("details:"),
            "collapsible name not a key: {out}"
        );
        assert!(out.contains("  bio?: string;"), "collapsible sub: {out}");
        assert!(!out.contains("sections:"), "tabs name not a key: {out}");
        assert!(out.contains("  tab_field: string;"), "tabs sub: {out}");
    }

    #[test]
    fn typescript_array_nested_in_row() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("layout", FieldType::Row)
                    .fields(vec![
                        FieldDefinition::builder("items", FieldType::Array)
                            .fields(vec![text_field("label", true)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("export interface PostsItems {"),
            "sub-type: {out}"
        );
        assert!(out.contains("PostsItems[]"), "reference: {out}");
    }

    #[test]
    fn typescript_global_with_subtypes() {
        let mut global = GlobalDefinition::new("settings");
        global.fields = vec![
            FieldDefinition::builder("nav", FieldType::Array)
                .fields(vec![text_field("label", true), text_field("url", true)])
                .build(),
            FieldDefinition::builder("seo", FieldType::Group)
                .fields(vec![text_field("title", true)])
                .build(),
        ];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(
            out.contains("export interface SettingsNav {"),
            "array sub: {out}"
        );
        assert!(
            out.contains("export interface SettingsSeo {"),
            "group sub: {out}"
        );
    }

    #[test]
    fn typescript_full_render_with_globals() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        let mut settings = GlobalDefinition::new("settings");
        settings.fields = vec![text_field("name", true)];
        registry.register_global(settings);
        let out = render(&registry);
        assert!(out.contains("Auto-generated"));
        assert!(out.contains("export interface PostsData {"));
        assert!(out.contains("export interface SettingsData {"));
        assert!(out.contains("export interface SettingsDocument {"));
        assert!(out.contains("export type CollectionSlug = \"posts\";"));
    }
}
