//! Go type definition generator — structs with json tags for gRPC clients.

use std::fmt::Write;

use crate::core::collection::{CollectionDefinition, GlobalDefinition};
use crate::core::field::{FieldDefinition, FieldType};
use crate::core::Registry;

use super::{
    is_optional, rel_has_many, sorted_collection_slugs, sorted_global_slugs, to_pascal_case,
};

pub(super) fn render(registry: &Registry) -> String {
    let mut out = String::from("// Auto-generated by crap-cms. Do not edit.\n\npackage types\n\n");

    for slug in sorted_collection_slugs(registry) {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    for slug in sorted_global_slugs(registry) {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    out
}

fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Array sub-types
    for f in &col.fields {
        if f.field_type == FieldType::Array && !f.fields.is_empty() {
            let sub_pascal = format!("{}{}", pascal, to_pascal_case(&f.name));
            writeln!(
                out,
                "// {} represents a row in the {} array field.",
                sub_pascal, f.name
            )
            .expect("write to String");
            writeln!(out, "type {} struct {{", sub_pascal).expect("write to String");
            for sf in &f.fields {
                write_field(out, sf);
            }
            writeln!(out, "}}\n").expect("write to String");
        }
    }

    // Document struct (includes id, fields, and timestamps)
    writeln!(out, "// {} represents a {} document.", pascal, col.slug).expect("write to String");
    writeln!(out, "type {} struct {{", pascal).expect("write to String");
    writeln!(out, "\tID        string  `json:\"id\"`").expect("write to String");
    for f in &col.fields {
        write_field_with_context(out, f, &pascal);
    }
    if col.timestamps {
        writeln!(out, "\tCreatedAt *string `json:\"created_at,omitempty\"`")
            .expect("write to String");
        writeln!(out, "\tUpdatedAt *string `json:\"updated_at,omitempty\"`")
            .expect("write to String");
    }
    writeln!(out, "}}\n").expect("write to String");
}

fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    writeln!(out, "// {} represents the {} global.", pascal, global.slug).expect("write to String");
    writeln!(out, "type {} struct {{", pascal).expect("write to String");
    writeln!(out, "\tID        string  `json:\"id\"`").expect("write to String");
    for f in &global.fields {
        write_field(out, f);
    }
    writeln!(out, "\tCreatedAt *string `json:\"created_at,omitempty\"`").expect("write to String");
    writeln!(out, "\tUpdatedAt *string `json:\"updated_at,omitempty\"`").expect("write to String");
    writeln!(out, "}}\n").expect("write to String");
}

fn write_field(out: &mut String, field: &FieldDefinition) {
    write_field_with_context(out, field, "");
}

fn write_field_with_context(out: &mut String, field: &FieldDefinition, parent_pascal: &str) {
    // Row is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Row {
        for sub in &field.fields {
            write_field_with_context(out, sub, parent_pascal);
        }
        return;
    }
    // Collapsible is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Collapsible {
        for sub in &field.fields {
            write_field_with_context(out, sub, parent_pascal);
        }
        return;
    }
    // Tabs is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Tabs {
        for tab in &field.tabs {
            for sub in &tab.fields {
                write_field_with_context(out, sub, parent_pascal);
            }
        }
        return;
    }
    // Emit a comment for polymorphic relationships listing target collections
    if field.field_type == FieldType::Relationship {
        if let Some(rc) = &field.relationship {
            if rc.is_polymorphic() {
                let targets = rc.all_collections().join(", ");
                writeln!(out, "\t// Polymorphic relationship — targets: {}", targets)
                    .expect("write to String");
            }
        }
    }
    let go_name = to_pascal_case(&field.name);
    let (go_type, omitempty) = field_to_go(field, parent_pascal);
    let tag = if omitempty {
        format!("`json:\"{},omitempty\"`", field.name)
    } else {
        format!("`json:\"{}\"`", field.name)
    };
    writeln!(out, "\t{:<9} {} {}", go_name, go_type, tag).expect("write to String");
}

fn field_to_go(field: &FieldDefinition, parent_pascal: &str) -> (String, bool) {
    let optional = is_optional(field);
    match &field.field_type {
        FieldType::Text => {
            if field.has_many {
                ("[]string".to_string(), true)
            } else if optional {
                ("*string".to_string(), true)
            } else {
                ("string".to_string(), false)
            }
        }
        FieldType::Textarea
        | FieldType::Email
        | FieldType::Date
        | FieldType::Richtext
        | FieldType::Code => {
            if optional {
                ("*string".to_string(), true)
            } else {
                ("string".to_string(), false)
            }
        }
        FieldType::Select | FieldType::Radio => {
            if field.has_many {
                ("[]string".to_string(), true)
            } else if optional {
                ("*string".to_string(), true)
            } else {
                ("string".to_string(), false)
            }
        }
        FieldType::Number => {
            if field.has_many {
                ("[]float64".to_string(), true)
            } else if optional {
                ("*float64".to_string(), true)
            } else {
                ("float64".to_string(), false)
            }
        }
        FieldType::Checkbox => ("bool".to_string(), true),
        FieldType::Json => ("interface{}".to_string(), true),
        FieldType::Relationship => match &field.relationship {
            Some(rc) if rc.is_polymorphic() && rc.has_many => ("[]string".to_string(), true),
            Some(rc) if rc.is_polymorphic() => {
                if optional {
                    ("*string".to_string(), true)
                } else {
                    ("string".to_string(), false)
                }
            }
            Some(rc) if rc.has_many => ("[]string".to_string(), true),
            _ if optional => ("*string".to_string(), true),
            _ => ("string".to_string(), false),
        },
        FieldType::Array => {
            if field.fields.is_empty() {
                ("[]map[string]interface{}".to_string(), true)
            } else {
                let sub = format!("[]{}{}", parent_pascal, to_pascal_case(&field.name));
                (sub, true)
            }
        }
        FieldType::Group => ("map[string]interface{}".to_string(), true),
        FieldType::Row => ("map[string]interface{}".to_string(), true), // layout-only; sub-fields are promoted
        FieldType::Collapsible => ("map[string]interface{}".to_string(), true), // layout-only; sub-fields are promoted
        FieldType::Tabs => ("map[string]interface{}".to_string(), true), // layout-only; sub-fields are promoted
        FieldType::Upload => {
            if rel_has_many(field) {
                ("[]string".to_string(), true)
            } else if optional {
                ("*string".to_string(), true)
            } else {
                ("string".to_string(), false)
            }
        }
        FieldType::Blocks => ("[]map[string]interface{}".to_string(), true),
        FieldType::Join => ("[]map[string]interface{}".to_string(), true),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::field::{BlockDefinition, LocalizedString, RelationshipConfig, SelectOption};

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Text)
            .required(required)
            .build()
    }

    fn make_col(slug: &str, fields: Vec<FieldDefinition>) -> CollectionDefinition {
        let mut def = CollectionDefinition::new(slug);
        def.timestamps = true;
        def.fields = fields;
        def
    }

    #[test]
    fn go_collection_output() {
        let col = make_col(
            "posts",
            vec![text_field("title", true), text_field("content", false)],
        );

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("type Posts struct {"));
        assert!(out.contains("ID        string  `json:\"id\"`"));
        assert!(out.contains("Title     string `json:\"title\"`"));
        assert!(out.contains("Content   *string `json:\"content,omitempty\"`"));
        assert!(out.contains("CreatedAt *string `json:\"created_at,omitempty\"`"));
    }

    #[test]
    fn go_relationship_field_has_one() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("author", FieldType::Relationship)
                .required(true)
                .relationship(RelationshipConfig::new("users", false))
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Author    string `json:\"author\"`"));
    }

    #[test]
    fn go_polymorphic_has_one() {
        let mut rc = RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".to_string(), "pages".to_string()];
        let col = make_col(
            "comments",
            vec![FieldDefinition::builder("subject", FieldType::Relationship)
                .required(true)
                .relationship(rc)
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Polymorphic has-one = string (stores "collection/id" composite)
        assert!(
            out.contains("Subject   string `json:\"subject\"`"),
            "polymorphic has-one should be string: {}",
            out
        );
        assert!(
            out.contains("Polymorphic relationship"),
            "should have polymorphic comment: {}",
            out
        );
        assert!(
            out.contains("posts"),
            "comment should list target collections: {}",
            out
        );
        assert!(
            out.contains("pages"),
            "comment should list target collections: {}",
            out
        );
    }

    #[test]
    fn go_polymorphic_has_many() {
        let mut rc = RelationshipConfig::new("articles", true);
        rc.polymorphic = vec!["articles".to_string(), "videos".to_string()];
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("related", FieldType::Relationship)
                .relationship(rc)
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Polymorphic has-many = []string (array of "collection/id" composites)
        assert!(
            out.contains("[]string"),
            "polymorphic has-many should be []string: {}",
            out
        );
        assert!(
            out.contains("Polymorphic relationship"),
            "should have polymorphic comment: {}",
            out
        );
        assert!(
            out.contains("articles"),
            "comment should list target collections: {}",
            out
        );
        assert!(
            out.contains("videos"),
            "comment should list target collections: {}",
            out
        );
    }

    #[test]
    fn go_relationship_field_has_many() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("tags", FieldType::Relationship)
                .relationship(RelationshipConfig::new("tags", true))
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("[]string"));
    }

    #[test]
    fn go_number_field() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("price", FieldType::Number)
                    .required(true)
                    .build(),
                FieldDefinition::builder("discount", FieldType::Number).build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Price     float64 `json:\"price\"`"));
        assert!(out.contains("*float64"));
    }

    #[test]
    fn go_checkbox_field() {
        let col = make_col(
            "items",
            vec![FieldDefinition::builder("active", FieldType::Checkbox).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("bool"));
    }

    #[test]
    fn go_json_field() {
        let col = make_col(
            "items",
            vec![FieldDefinition::builder("metadata", FieldType::Json).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("interface{}"));
    }

    #[test]
    fn go_array_field_with_subfields() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("items", FieldType::Array)
                .fields(vec![text_field("label", true), text_field("value", false)])
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Sub-type should be generated
        assert!(out.contains("type PostsItems struct {"));
        assert!(out.contains("Label     string `json:\"label\"`"));
        // Main field should reference sub-type
        assert!(out.contains("[]PostsItems"));
    }

    #[test]
    fn go_array_field_without_subfields() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("data", FieldType::Array).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("[]map[string]interface{}"));
    }

    #[test]
    fn go_group_field() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("seo", FieldType::Group).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("map[string]interface{}"));
    }

    #[test]
    fn go_blocks_field() {
        let mut bd = BlockDefinition::new("text", vec![text_field("body", true)]);
        bd.label = Some(LocalizedString::Plain("Text".to_string()));
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("content", FieldType::Blocks)
                .blocks(vec![bd])
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("[]map[string]interface{}"));
    }

    #[test]
    fn go_upload_field() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("image", FieldType::Upload)
                    .required(true)
                    .build(),
                FieldDefinition::builder("thumb", FieldType::Upload).build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Image     string `json:\"image\"`"));
        assert!(out.contains("*string"));
    }

    #[test]
    fn upload_has_many_generates_array_type() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("images", FieldType::Upload)
                .required(true)
                .relationship(RelationshipConfig::new("", true))
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("[]string"),
            "has-many upload should be []string: {}",
            out
        );
    }

    #[test]
    fn go_select_field() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("status", FieldType::Select)
                .required(true)
                .options(vec![
                    SelectOption::new(LocalizedString::Plain("Draft".into()), "draft"),
                    SelectOption::new(LocalizedString::Plain("Published".into()), "published"),
                ])
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Select in Go is just string
        assert!(out.contains("Status    string `json:\"status\"`"));
    }

    #[test]
    fn go_global_output() {
        let mut global = crate::core::collection::GlobalDefinition::new("site_settings");
        global.fields = vec![text_field("site_name", true)];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(out.contains("type SiteSettings struct {"));
        assert!(out.contains("ID        string  `json:\"id\"`"));
        assert!(out.contains("SiteName  string `json:\"site_name\"`"));
        assert!(out.contains("CreatedAt *string `json:\"created_at,omitempty\"`"));
        assert!(out.contains("UpdatedAt *string `json:\"updated_at,omitempty\"`"));
    }

    #[test]
    fn go_full_render_with_globals() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        let mut settings = crate::core::collection::GlobalDefinition::new("settings");
        settings.fields = vec![text_field("name", true)];
        registry.register_global(settings);
        let out = render(&registry);
        assert!(out.contains("package types"));
        assert!(out.contains("type Posts struct {"));
        assert!(out.contains("type Settings struct {"));
    }

    #[test]
    fn go_no_timestamps_collection() {
        let mut col = make_col("tags", vec![text_field("name", true)]);
        col.timestamps = false;
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("type Tags struct {"));
        assert!(!out.contains("CreatedAt"));
        assert!(!out.contains("UpdatedAt"));
    }

    #[test]
    fn go_text_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("tags", FieldType::Text)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("labels", FieldType::Text)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("[]string"),
            "has-many text should be []string: {}",
            out
        );
        // required has_many: no omitempty on the type itself, but array is always omitempty
        assert!(
            out.contains("Tags      []string"),
            "required has-many text field: {}",
            out
        );
        assert!(
            out.contains("Labels    []string"),
            "optional has-many text field: {}",
            out
        );
    }

    #[test]
    fn go_number_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("scores", FieldType::Number)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("weights", FieldType::Number)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("[]float64"),
            "has-many number should be []float64: {}",
            out
        );
        assert!(
            out.contains("Scores    []float64"),
            "required has-many number field: {}",
            out
        );
        assert!(
            out.contains("Weights   []float64"),
            "optional has-many number field: {}",
            out
        );
    }

    #[test]
    fn go_email_date_richtext_textarea_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("contact", FieldType::Email)
                    .required(true)
                    .build(),
                FieldDefinition::builder("published_at", FieldType::Date).build(),
                FieldDefinition::builder("body", FieldType::Richtext)
                    .required(true)
                    .build(),
                FieldDefinition::builder("notes", FieldType::Textarea).build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Contact   string `json:\"contact\"`"));
        assert!(out.contains("*string `json:\"published_at,omitempty\"`"));
        assert!(out.contains("Body      string `json:\"body\"`"));
        assert!(out.contains("*string `json:\"notes,omitempty\"`"));
    }

    #[test]
    fn go_relationship_no_config_optional() {
        // Relationship field without RelationshipConfig and not required
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("ref", FieldType::Relationship).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("*string"));
    }

    #[test]
    fn go_code_join_radio_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("snippet", FieldType::Code)
                    .required(true)
                    .build(),
                FieldDefinition::builder("refs", FieldType::Join).build(),
                FieldDefinition::builder("color", FieldType::Radio)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("Snippet   string `json:\"snippet\"`"),
            "code required field should be string: {}",
            out
        );
        assert!(
            out.contains("[]map[string]interface{}"),
            "join field should be []map[string]interface{{}}: {}",
            out
        );
        assert!(
            out.contains("Color     string `json:\"color\"`"),
            "radio required field should be string: {}",
            out
        );
    }

    #[test]
    fn go_select_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("tags", FieldType::Select)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("sizes", FieldType::Radio)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("Tags      []string"),
            "required select has-many should be []string: {}",
            out
        );
        assert!(
            out.contains("Sizes     []string"),
            "optional radio has-many should be []string: {}",
            out
        );
    }

    #[test]
    fn go_polymorphic_has_one_optional() {
        // Optional polymorphic has-one should use *string
        let mut rc = RelationshipConfig::new("pages", false);
        rc.polymorphic = vec!["pages".to_string(), "posts".to_string()];
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("related", FieldType::Relationship)
                .required(false)
                .relationship(rc)
                .build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("*string"),
            "optional polymorphic has-one should be *string: {}",
            out
        );
    }

    #[test]
    fn go_row_collapsible_tabs_promote_subfields() {
        use crate::core::field::FieldTab;
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("layout_row", FieldType::Row)
                    .fields(vec![
                        text_field("first_name", true),
                        text_field("last_name", false),
                    ])
                    .build(),
                FieldDefinition::builder("details", FieldType::Collapsible)
                    .fields(vec![text_field("bio", false)])
                    .build(),
                FieldDefinition::builder("sections", FieldType::Tabs)
                    .tabs(vec![FieldTab::new(
                        "Tab1",
                        vec![text_field("tab_field", true)],
                    )])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Row sub-fields promoted — "LayoutRow" should not appear as a struct field
        assert!(
            !out.contains("LayoutRow"),
            "row field name should not appear as a struct field: {}",
            out
        );
        assert!(
            out.contains("FirstName string"),
            "row required sub-field promoted: {}",
            out
        );
        assert!(
            out.contains("LastName  *string"),
            "row optional sub-field promoted: {}",
            out
        );
        // Collapsible sub-fields promoted
        assert!(
            !out.contains("Details"),
            "collapsible field name should not appear: {}",
            out
        );
        assert!(
            out.contains("Bio       *string"),
            "collapsible sub-field promoted: {}",
            out
        );
        // Tabs sub-fields promoted
        assert!(
            !out.contains("Sections"),
            "tabs field name should not appear: {}",
            out
        );
        assert!(
            out.contains("TabField  string"),
            "tabs sub-field promoted: {}",
            out
        );
    }
}
