//! LuaLS type definition generator for IDE support in hooks and init.lua.

use std::fmt::Write;

use crate::core::Registry;
use crate::core::collection::{CollectionDefinition, GlobalDefinition};
use crate::core::field::{FieldDefinition, FieldType};
use crate::db::query::get_column_names;

use super::{is_optional, rel_has_many, to_pascal_case};

/// Render all Lua type definitions.
pub(super) fn render(registry: &Registry) -> String {
    let mut out = String::from("-- Auto-generated by crap-cms. Do not edit.\n\n");

    let mut slugs: Vec<&String> = registry.collections.keys().collect();
    slugs.sort();
    for slug in slugs {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    let mut global_slugs: Vec<&String> = registry.globals.keys().collect();
    global_slugs.sort();
    for slug in global_slugs {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    render_find_overloads(&mut out, registry);

    out
}

/// Recursively collect all array fields (including those inside layout wrappers).
fn collect_array_fields(fields: &[FieldDefinition]) -> Vec<&FieldDefinition> {
    let mut result = Vec::new();
    for f in fields {
        if f.field_type == FieldType::Array && !f.fields.is_empty() {
            result.push(f);
            // Also recurse into the array's own sub-fields (nested arrays)
            result.extend(collect_array_fields(&f.fields));
        } else if matches!(
            f.field_type,
            FieldType::Row | FieldType::Collapsible | FieldType::Group
        ) {
            result.extend(collect_array_fields(&f.fields));
        } else if f.field_type == FieldType::Tabs {
            for tab in &f.tabs {
                result.extend(collect_array_fields(&tab.fields));
            }
        }
    }
    result
}

fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Array sub-type classes (emitted before the collection class that references them)
    for f in collect_array_fields(&col.fields) {
        let sub_pascal = to_pascal_case(&f.name);
        writeln!(out, "---@class crap.array_row.{sub_pascal}").expect("write to String");
        for sf in &f.fields {
            write_field(out, sf);
        }
        out.push('\n');
    }

    // crap.data.* — hook ctx.data (mutable input)
    writeln!(out, "---@class crap.data.{pascal}").expect("write to String");
    for f in &col.fields {
        write_field(out, f);
    }
    out.push('\n');

    // crap.doc.* — returned document (id + timestamps)
    writeln!(out, "---@class crap.doc.{pascal}").expect("write to String");
    writeln!(out, "---@field id string").expect("write to String");
    for f in &col.fields {
        write_field(out, f);
    }
    if col.timestamps {
        writeln!(out, "---@field created_at? string").expect("write to String");
        writeln!(out, "---@field updated_at? string").expect("write to String");
    }
    out.push('\n');

    // crap.hook.* — typed HookContext
    writeln!(out, "---@class crap.hook.{pascal}").expect("write to String");
    writeln!(out, "---@field collection \"{}\"", col.slug).expect("write to String");
    writeln!(
        out,
        "---@field operation \"create\" | \"update\" | \"find\" | \"find_by_id\""
    )
    .expect("write to String");
    writeln!(out, "---@field data crap.data.{pascal}").expect("write to String");
    writeln!(out, "---@field context table<string, any>").expect("write to String");
    writeln!(out, "---@field hook_depth integer").expect("write to String");
    writeln!(out, "---@field locale? string").expect("write to String");
    writeln!(out, "---@field draft? boolean").expect("write to String");
    out.push('\n');

    // crap.find_result.*
    writeln!(out, "---@class crap.find_result.{pascal}").expect("write to String");
    writeln!(out, "---@field documents crap.doc.{pascal}[]").expect("write to String");
    writeln!(out, "---@field total integer").expect("write to String");
    out.push('\n');

    // hook function alias
    writeln!(
        out,
        "---@alias crap.hook_fn.{pascal} fun(ctx: crap.hook.{pascal}): crap.hook.{pascal}"
    )
    .expect("write to String");
    out.push('\n');

    // crap.field_hook.* — typed FieldHookContext (data = full document)
    writeln!(out, "---@class crap.field_hook.{pascal}").expect("write to String");
    writeln!(out, "---@field field_name string").expect("write to String");
    writeln!(out, "---@field collection \"{}\"", col.slug).expect("write to String");
    writeln!(out, "---@field operation string").expect("write to String");
    writeln!(out, "---@field data crap.data.{pascal}").expect("write to String");
    out.push('\n');

    // crap.where.* — typed filter keys
    let columns = get_column_names(col);
    writeln!(out, "---@class crap.where.{pascal}").expect("write to String");
    for col_name in &columns {
        writeln!(out, "---@field {col_name}? crap.FilterValue").expect("write to String");
    }
    out.push('\n');

    // crap.query.* — typed query options
    writeln!(out, "---@class crap.query.{pascal}").expect("write to String");
    writeln!(out, "---@field where? crap.where.{pascal}").expect("write to String");
    let order_by_union: Vec<String> = columns
        .iter()
        .flat_map(|c| [format!("\"{c}\""), format!("\"-{c}\"")])
        .collect();
    writeln!(out, "---@field order_by? {}", order_by_union.join("|")).expect("write to String");
    writeln!(out, "---@field limit? integer").expect("write to String");
    writeln!(out, "---@field offset? integer").expect("write to String");
    writeln!(out, "---@field locale? string").expect("write to String");
    out.push('\n');
}

fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    // Array sub-type classes (same as collections — recurse into layout wrappers)
    for f in collect_array_fields(&global.fields) {
        let sub_pascal = to_pascal_case(&f.name);
        writeln!(out, "---@class crap.array_row.{sub_pascal}").expect("write to String");
        for sf in &f.fields {
            write_field(out, sf);
        }
        out.push('\n');
    }

    // crap.global_data.*
    writeln!(out, "---@class crap.global_data.{pascal}").expect("write to String");
    for f in &global.fields {
        write_field(out, f);
    }
    out.push('\n');

    // crap.global_doc.* — always has timestamps
    writeln!(out, "---@class crap.global_doc.{pascal}").expect("write to String");
    writeln!(out, "---@field id string").expect("write to String");
    for f in &global.fields {
        write_field(out, f);
    }
    writeln!(out, "---@field created_at? string").expect("write to String");
    writeln!(out, "---@field updated_at? string").expect("write to String");
    out.push('\n');

    // crap.hook.global_*
    writeln!(out, "---@class crap.hook.global_{}", global.slug).expect("write to String");
    writeln!(out, "---@field global \"{}\"", global.slug).expect("write to String");
    writeln!(out, "---@field operation \"update\" | \"get_global\"").expect("write to String");
    writeln!(out, "---@field data crap.global_data.{pascal}").expect("write to String");
    writeln!(out, "---@field context table<string, any>").expect("write to String");
    writeln!(out, "---@field hook_depth integer").expect("write to String");
    writeln!(out, "---@field locale? string").expect("write to String");
    writeln!(out, "---@field draft? boolean").expect("write to String");
    out.push('\n');

    // crap.field_hook.global_* — typed FieldHookContext for globals
    writeln!(out, "---@class crap.field_hook.global_{}", global.slug).expect("write to String");
    writeln!(out, "---@field field_name string").expect("write to String");
    writeln!(out, "---@field global \"{}\"", global.slug).expect("write to String");
    writeln!(out, "---@field operation string").expect("write to String");
    writeln!(out, "---@field data crap.global_data.{pascal}").expect("write to String");
    out.push('\n');
}

fn render_find_overloads(out: &mut String, registry: &Registry) {
    let mut slugs: Vec<&String> = registry.collections.keys().collect();
    slugs.sort();

    if slugs.is_empty() {
        return;
    }

    // find() overloads
    for slug in &slugs {
        let pascal = to_pascal_case(slug);
        writeln!(
            out,
            "---@overload fun(collection: \"{slug}\", query?: crap.query.{pascal}): crap.find_result.{pascal}"
        )
        .expect("write to String");
    }
    writeln!(out, "---@param collection string").expect("write to String");
    writeln!(out, "---@param query? crap.FindQuery").expect("write to String");
    writeln!(out, "---@return crap.FindResult").expect("write to String");
    writeln!(out, "function crap.collections.find(collection, query) end")
        .expect("write to String");
    out.push('\n');

    // find_by_id() overloads
    for slug in &slugs {
        let pascal = to_pascal_case(slug);
        writeln!(
            out,
            "---@overload fun(collection: \"{slug}\", id: string, opts?: crap.FindByIdOptions): crap.doc.{pascal}?"
        )
        .expect("write to String");
    }
    writeln!(out, "---@param collection string").expect("write to String");
    writeln!(out, "---@param id string").expect("write to String");
    writeln!(out, "---@param opts? crap.FindByIdOptions").expect("write to String");
    writeln!(out, "---@return crap.Document?").expect("write to String");
    writeln!(
        out,
        "function crap.collections.find_by_id(collection, id, opts) end"
    )
    .expect("write to String");
    out.push('\n');
}

fn write_field(out: &mut String, field: &FieldDefinition) {
    // Row is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Row {
        for sub in &field.fields {
            write_field(out, sub);
        }
        return;
    }
    // Collapsible is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Collapsible {
        for sub in &field.fields {
            write_field(out, sub);
        }
        return;
    }
    // Tabs is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Tabs {
        for tab in &field.tabs {
            for sub in &tab.fields {
                write_field(out, sub);
            }
        }
        return;
    }
    // Emit a comment for polymorphic relationships listing target collections
    if field.field_type == FieldType::Relationship {
        if let Some(rc) = &field.relationship {
            if rc.is_polymorphic() {
                let targets = rc.all_collections().join(", ");
                writeln!(out, "--- Polymorphic relationship — targets: {}", targets)
                    .expect("write to String");
            }
        }
    }
    let lua_type = field_to_lua_type(field);
    let opt = if is_optional(field) { "?" } else { "" };
    writeln!(out, "---@field {}{opt} {lua_type}", field.name).expect("write to String");
}

fn field_to_lua_type(field: &FieldDefinition) -> String {
    match &field.field_type {
        FieldType::Text => {
            if field.has_many {
                "string[]".to_string()
            } else {
                "string".to_string()
            }
        }
        FieldType::Textarea
        | FieldType::Email
        | FieldType::Date
        | FieldType::Richtext
        | FieldType::Code => "string".to_string(),
        FieldType::Number => {
            if field.has_many {
                "number[]".to_string()
            } else {
                "number".to_string()
            }
        }
        FieldType::Checkbox => "boolean".to_string(),
        FieldType::Json => "any".to_string(),
        FieldType::Select | FieldType::Radio => {
            let base = if field.options.is_empty() {
                "string".to_string()
            } else {
                field
                    .options
                    .iter()
                    .map(|o| format!("\"{}\"", o.value))
                    .collect::<Vec<_>>()
                    .join(" | ")
            };
            if field.has_many {
                if field.options.is_empty() {
                    "string[]".to_string()
                } else {
                    format!("({}|string)[]", base)
                }
            } else {
                base
            }
        }
        FieldType::Relationship => match &field.relationship {
            Some(rc) if rc.is_polymorphic() && rc.has_many => "string[]".to_string(),
            Some(rc) if rc.is_polymorphic() => "string".to_string(),
            Some(rc) if rc.has_many => "string[]".to_string(),
            _ => "string".to_string(),
        },
        FieldType::Array => {
            let pascal = to_pascal_case(&field.name);
            format!("crap.array_row.{}[]", pascal)
        }
        FieldType::Group => "table".to_string(),
        FieldType::Row => "table".to_string(), // layout-only; sub-fields are promoted
        FieldType::Collapsible => "table".to_string(), // layout-only; sub-fields are promoted
        FieldType::Tabs => "table".to_string(), // layout-only; sub-fields are promoted
        FieldType::Upload => {
            if rel_has_many(field) {
                "string[]".to_string()
            } else {
                "string".to_string()
            }
        }
        FieldType::Blocks => "table[]".to_string(),
        FieldType::Join => "table[]".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::field::{LocalizedString, SelectOption};

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Text)
            .required(required)
            .build()
    }

    fn select_field(name: &str, required: bool, opts: &[&str]) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Select)
            .required(required)
            .options(
                opts.iter()
                    .map(|v| SelectOption::new(LocalizedString::Plain(v.to_string()), *v))
                    .collect(),
            )
            .build()
    }

    fn checkbox_field(name: &str) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Checkbox).build()
    }

    #[test]
    fn to_pascal_case_basic() {
        assert_eq!(to_pascal_case("posts"), "Posts");
        assert_eq!(to_pascal_case("site_settings"), "SiteSettings");
        assert_eq!(to_pascal_case("a_b_c"), "ABC");
    }

    #[test]
    fn field_type_mapping() {
        let f = text_field("x", true);
        assert_eq!(field_to_lua_type(&f), "string");

        let mut f = text_field("x", true);
        f.field_type = FieldType::Number;
        assert_eq!(field_to_lua_type(&f), "number");

        let f = checkbox_field("x");
        assert_eq!(field_to_lua_type(&f), "boolean");

        let mut f = text_field("x", true);
        f.field_type = FieldType::Json;
        assert_eq!(field_to_lua_type(&f), "any");
    }

    #[test]
    fn select_with_options() {
        let f = select_field("status", true, &["draft", "published"]);
        assert_eq!(field_to_lua_type(&f), "\"draft\" | \"published\"");
    }

    #[test]
    fn select_without_options() {
        let f = select_field("status", true, &[]);
        assert_eq!(field_to_lua_type(&f), "string");
    }

    #[test]
    fn optional_logic() {
        assert!(!is_optional(&text_field("x", true)));
        assert!(is_optional(&text_field("x", false)));
        let mut cb = checkbox_field("x");
        cb.required = true;
        assert!(is_optional(&cb));
    }

    #[test]
    fn render_collection_output() {
        let mut col = CollectionDefinition::new("posts");
        col.timestamps = true;
        col.fields = vec![
            text_field("title", true),
            text_field("content", false),
            select_field("status", true, &["draft", "published"]),
            checkbox_field("active"),
        ];

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("---@class crap.data.Posts"));
        assert!(out.contains("---@field title string"));
        assert!(out.contains("---@field content? string"));
        assert!(out.contains("---@field status \"draft\" | \"published\""));
        assert!(out.contains("---@field active? boolean"));
        assert!(out.contains("---@class crap.doc.Posts"));
        assert!(out.contains("---@field id string"));
        assert!(out.contains("---@field created_at? string"));
        assert!(out.contains("---@field updated_at? string"));
        assert!(out.contains("---@class crap.hook.Posts"));
        assert!(out.contains("---@field collection \"posts\""));
        assert!(out.contains("---@field data crap.data.Posts"));
        assert!(
            out.contains("---@field hook_depth integer"),
            "hook context should have hook_depth"
        );
        assert!(
            out.contains("---@field draft? boolean"),
            "hook context should have draft"
        );
        assert!(
            out.contains("---@field context table<string, any>"),
            "hook context should have context"
        );
        assert!(out.contains("---@class crap.find_result.Posts"));
        assert!(out.contains("---@field documents crap.doc.Posts[]"));
        assert!(out.contains("---@alias crap.hook_fn.Posts"));
        assert!(out.contains("---@class crap.field_hook.Posts"));
        assert!(out.contains("---@field data crap.data.Posts"));
        assert!(out.contains("---@field field_name string"));
        assert!(out.contains("---@class crap.where.Posts"));
        assert!(out.contains("---@class crap.query.Posts"));
    }

    #[test]
    fn render_collection_no_timestamps() {
        let mut col = CollectionDefinition::new("tags");
        col.timestamps = false;
        col.fields = vec![text_field("name", true)];

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("---@class crap.doc.Tags"));
        assert!(!out.contains("created_at"));
    }

    #[test]
    fn render_global_output() {
        let mut global = GlobalDefinition::new("site_settings");
        global.fields = vec![text_field("site_name", true), text_field("tagline", false)];

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(out.contains("---@class crap.global_data.SiteSettings"));
        assert!(out.contains("---@field site_name string"));
        assert!(out.contains("---@field tagline? string"));
        assert!(out.contains("---@class crap.global_doc.SiteSettings"));
        assert!(out.contains("---@class crap.hook.global_site_settings"));
        assert!(out.contains("---@class crap.field_hook.global_site_settings"));
    }

    #[test]
    fn render_global_array_row() {
        let mut global = GlobalDefinition::new("navigation");
        global.fields = vec![
            FieldDefinition::builder("main_nav", FieldType::Array)
                .fields(vec![text_field("label", true), text_field("url", true)])
                .build(),
        ];

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(
            out.contains("---@class crap.array_row.MainNav"),
            "global array should emit sub-type class, got:\n{out}"
        );
        assert!(out.contains("---@field label string"));
    }

    #[test]
    fn render_global_hook_context_fields() {
        let mut global = GlobalDefinition::new("footer");
        global.fields = vec![text_field("copyright", true)];

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(
            out.contains("---@field hook_depth integer"),
            "global hook context should have hook_depth"
        );
        assert!(
            out.contains("---@field draft? boolean"),
            "global hook context should have draft"
        );
        assert!(
            out.contains("---@field context table<string, any>"),
            "global hook context should have context"
        );
    }

    #[test]
    fn render_sorted_output() {
        let mut registry = Registry::new();
        let mut zebras = CollectionDefinition::new("zebras");
        zebras.timestamps = true;
        registry.register_collection(zebras);
        let mut apples = CollectionDefinition::new("apples");
        apples.timestamps = true;
        registry.register_collection(apples);

        let output = render(&registry);
        let apples_pos = output.find("crap.data.Apples").expect("write to String");
        let zebras_pos = output.find("crap.data.Zebras").expect("write to String");
        assert!(apples_pos < zebras_pos);
    }

    #[test]
    fn render_find_overloads_output() {
        let mut registry = Registry::new();
        let mut posts = CollectionDefinition::new("posts");
        posts.timestamps = true;
        posts.fields = vec![text_field("title", true)];
        registry.register_collection(posts);
        let mut pages = CollectionDefinition::new("pages");
        pages.timestamps = true;
        pages.fields = vec![text_field("body", false)];
        registry.register_collection(pages);

        let output = render(&registry);
        assert!(output.contains("---@overload fun(collection: \"pages\""));
        assert!(output.contains("---@overload fun(collection: \"posts\""));
        assert!(output.contains("function crap.collections.find(collection, query) end"));
        // find_by_id overloads
        assert!(output.contains(
            "fun(collection: \"posts\", id: string, opts?: crap.FindByIdOptions): crap.doc.Posts?"
        ));
        assert!(output.contains("function crap.collections.find_by_id(collection, id, opts) end"));
    }

    #[test]
    fn render_find_overloads_empty_registry() {
        let registry = Registry::new();
        let output = render(&registry);
        assert!(!output.contains("crap.collections.find"));
    }

    #[test]
    fn lua_relationship_has_many() {
        let f = FieldDefinition::builder("tags", FieldType::Relationship)
            .relationship(crate::core::field::RelationshipConfig::new("tags", true))
            .build();
        assert_eq!(field_to_lua_type(&f), "string[]");
    }

    #[test]
    fn lua_polymorphic_has_one_type() {
        let mut rc = crate::core::field::RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".to_string(), "pages".to_string()];
        let f = FieldDefinition::builder("subject", FieldType::Relationship)
            .required(true)
            .relationship(rc)
            .build();
        // Polymorphic has-one stores "collection/id" composite as string
        assert_eq!(field_to_lua_type(&f), "string");
    }

    #[test]
    fn lua_polymorphic_has_many_type() {
        let mut rc = crate::core::field::RelationshipConfig::new("articles", true);
        rc.polymorphic = vec!["articles".to_string(), "videos".to_string()];
        let f = FieldDefinition::builder("related", FieldType::Relationship)
            .relationship(rc)
            .build();
        // Polymorphic has-many stores array of "collection/id" composites
        assert_eq!(field_to_lua_type(&f), "string[]");
    }

    #[test]
    fn lua_polymorphic_comment_emitted() {
        let mut rc = crate::core::field::RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".to_string(), "pages".to_string()];
        let mut col = CollectionDefinition::new("comments");
        col.fields = vec![
            FieldDefinition::builder("subject", FieldType::Relationship)
                .required(true)
                .relationship(rc)
                .build(),
        ];
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("Polymorphic relationship"),
            "should have polymorphic comment: {}",
            out
        );
        assert!(
            out.contains("posts"),
            "comment should list target collections: {}",
            out
        );
        assert!(
            out.contains("pages"),
            "comment should list target collections: {}",
            out
        );
    }

    #[test]
    fn lua_relationship_has_one() {
        let f = FieldDefinition::builder("author", FieldType::Relationship)
            .required(true)
            .relationship(crate::core::field::RelationshipConfig::new("users", false))
            .build();
        assert_eq!(field_to_lua_type(&f), "string");
    }

    #[test]
    fn lua_array_type() {
        let f = FieldDefinition::builder("items", FieldType::Array)
            .fields(vec![text_field("label", true)])
            .build();
        assert_eq!(field_to_lua_type(&f), "crap.array_row.Items[]");
    }

    #[test]
    fn lua_group_type() {
        let f = FieldDefinition::builder("seo", FieldType::Group).build();
        assert_eq!(field_to_lua_type(&f), "table");
    }

    #[test]
    fn lua_upload_type() {
        let f = FieldDefinition::builder("image", FieldType::Upload).build();
        assert_eq!(field_to_lua_type(&f), "string");
    }

    #[test]
    fn upload_has_many_generates_array_type() {
        let f = FieldDefinition::builder("images", FieldType::Upload)
            .relationship(crate::core::field::RelationshipConfig::new("", true))
            .build();
        assert_eq!(field_to_lua_type(&f), "string[]");
    }

    #[test]
    fn lua_blocks_type() {
        let f = FieldDefinition::builder("content", FieldType::Blocks).build();
        assert_eq!(field_to_lua_type(&f), "table[]");
    }

    #[test]
    fn lua_text_has_many() {
        let f = FieldDefinition::builder("tags", FieldType::Text)
            .has_many(true)
            .build();
        assert_eq!(field_to_lua_type(&f), "string[]");
    }

    #[test]
    fn lua_number_has_many() {
        let f = FieldDefinition::builder("scores", FieldType::Number)
            .has_many(true)
            .build();
        assert_eq!(field_to_lua_type(&f), "number[]");
    }

    #[test]
    fn lua_email_type() {
        let f = FieldDefinition::builder("email", FieldType::Email).build();
        assert_eq!(field_to_lua_type(&f), "string");
    }

    #[test]
    fn lua_date_type() {
        let f = FieldDefinition::builder("at", FieldType::Date).build();
        assert_eq!(field_to_lua_type(&f), "string");
    }

    #[test]
    fn lua_richtext_type() {
        let f = FieldDefinition::builder("body", FieldType::Richtext).build();
        assert_eq!(field_to_lua_type(&f), "string");
    }

    #[test]
    fn lua_textarea_type() {
        let f = FieldDefinition::builder("notes", FieldType::Textarea).build();
        assert_eq!(field_to_lua_type(&f), "string");
    }

    #[test]
    fn render_collection_with_array_subtype() {
        let mut col = CollectionDefinition::new("posts");
        col.fields = vec![
            FieldDefinition::builder("items", FieldType::Array)
                .fields(vec![text_field("label", true), text_field("desc", false)])
                .build(),
        ];
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("---@class crap.array_row.Items"));
        assert!(out.contains("---@field label string"));
        assert!(out.contains("---@field desc? string"));
    }

    #[test]
    fn lua_code_join_radio_fields() {
        // Code maps to string, Join maps to table[], Radio maps to string/union
        let f_code = FieldDefinition::builder("snippet", FieldType::Code).build();
        let f_join = FieldDefinition::builder("refs", FieldType::Join).build();
        let f_radio = FieldDefinition::builder("color", FieldType::Radio).build();
        assert_eq!(field_to_lua_type(&f_code), "string");
        assert_eq!(field_to_lua_type(&f_join), "table[]");
        assert_eq!(field_to_lua_type(&f_radio), "string");
    }

    #[test]
    fn lua_select_has_many_with_and_without_options() {
        use crate::core::field::SelectOption;
        // has_many with options → (opt1 | opt2|string)[]
        let f_with_opts = FieldDefinition::builder("tags", FieldType::Select)
            .has_many(true)
            .options(vec![
                SelectOption::new(LocalizedString::Plain("A".into()), "a"),
                SelectOption::new(LocalizedString::Plain("B".into()), "b"),
            ])
            .build();
        let result = field_to_lua_type(&f_with_opts);
        assert!(
            result.contains("\"a\""),
            "should include option 'a': {}",
            result
        );
        assert!(
            result.contains("\"b\""),
            "should include option 'b': {}",
            result
        );
        assert!(
            result.ends_with("[]"),
            "should be an array type: {}",
            result
        );

        // has_many without options → string[]
        let f_no_opts = FieldDefinition::builder("cats", FieldType::Select)
            .has_many(true)
            .build();
        assert_eq!(field_to_lua_type(&f_no_opts), "string[]");
    }

    #[test]
    fn lua_row_collapsible_tabs_promote_subfields() {
        use crate::core::field::FieldTab;
        let mut col = CollectionDefinition::new("items");
        col.fields = vec![
            FieldDefinition::builder("layout_row", FieldType::Row)
                .fields(vec![
                    text_field("first_name", true),
                    text_field("last_name", false),
                ])
                .build(),
            FieldDefinition::builder("details", FieldType::Collapsible)
                .fields(vec![text_field("bio", false)])
                .build(),
            FieldDefinition::builder("sections", FieldType::Tabs)
                .tabs(vec![FieldTab::new(
                    "Tab1",
                    vec![text_field("tab_field", true)],
                )])
                .build(),
        ];
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Row sub-fields promoted — "layout_row" should not appear as a @field
        assert!(
            !out.contains("@field layout_row"),
            "row field name should not appear: {}",
            out
        );
        assert!(
            out.contains("---@field first_name string"),
            "row required sub-field promoted: {}",
            out
        );
        assert!(
            out.contains("---@field last_name? string"),
            "row optional sub-field promoted: {}",
            out
        );
        // Collapsible sub-fields promoted
        assert!(
            !out.contains("@field details"),
            "collapsible field name should not appear: {}",
            out
        );
        assert!(
            out.contains("---@field bio? string"),
            "collapsible sub-field promoted: {}",
            out
        );
        // Tabs sub-fields promoted
        assert!(
            !out.contains("@field sections"),
            "tabs field name should not appear: {}",
            out
        );
        assert!(
            out.contains("---@field tab_field string"),
            "tabs sub-field promoted: {}",
            out
        );
    }

    #[test]
    fn collect_array_fields_inside_row_and_tabs() {
        use crate::core::field::FieldTab;
        // Arrays nested inside Row, Group, and Tabs containers should be discovered
        let fields = vec![
            FieldDefinition::builder("row_container", FieldType::Row)
                .fields(vec![
                    FieldDefinition::builder("row_items", FieldType::Array)
                        .fields(vec![text_field("val", true)])
                        .build(),
                ])
                .build(),
            FieldDefinition::builder("tab_container", FieldType::Tabs)
                .tabs(vec![FieldTab::new(
                    "T",
                    vec![
                        FieldDefinition::builder("tab_items", FieldType::Array)
                            .fields(vec![text_field("name", true)])
                            .build(),
                    ],
                )])
                .build(),
            // Nested array inside an array (recursion)
            FieldDefinition::builder("outer", FieldType::Array)
                .fields(vec![
                    FieldDefinition::builder("inner", FieldType::Array)
                        .fields(vec![text_field("x", true)])
                        .build(),
                ])
                .build(),
        ];
        let result = collect_array_fields(&fields);
        let names: Vec<&str> = result.iter().map(|f| f.name.as_str()).collect();
        assert!(
            names.contains(&"row_items"),
            "array inside Row should be found: {:?}",
            names
        );
        assert!(
            names.contains(&"tab_items"),
            "array inside Tabs should be found: {:?}",
            names
        );
        assert!(
            names.contains(&"outer"),
            "top-level array should be found: {:?}",
            names
        );
        assert!(
            names.contains(&"inner"),
            "nested array inside array should be found: {:?}",
            names
        );
    }
}
