//! Rust proto conversion generator — `from_document` impls over the typed
//! `FieldValue` / `DataMap` wire messages.
//!
//! Generates `proto.rs` with direct extraction from the generated proto types:
//! no JSON intermediate, no serde deserialization in the hot path.

use crate::core::{
    CollectionDefinition, FieldDefinition, Registry, collection::GlobalDefinition,
    flatten_array_sub_fields,
};

use super::client::{FieldTy, resolve_ty};
use super::helpers::{
    collect_sub_type_fields, sorted_collection_slugs, sorted_global_slugs, to_pascal_case, w, wraw,
};
use super::idents;

/// Render proto conversion code for all collections and globals.
pub(super) fn render(registry: &Registry, proto_mod: &str) -> String {
    let mut out = String::new();

    w!(out, "// Auto-generated by crap-cms. Do not edit.");
    w!(out, "//");
    w!(
        out,
        "// Proto-to-struct conversion over the typed FieldValue/DataMap messages."
    );
    w!(
        out,
        "// Import the generated structs from generated.rs alongside this file."
    );
    w!(out, "");
    w!(out, "use {}::field_value::Kind;", proto_mod);
    w!(out, "use {}::{{DataMap, Document}};", proto_mod);
    w!(out, "");
    w!(out, "use super::generated::*;");
    w!(out, "");

    render_from_document_trait(&mut out);
    render_helpers(&mut out);
    render_rel_helpers(&mut out);

    for slug in sorted_collection_slugs(registry) {
        let col = &registry.collections[slug];
        render_collection_impl(&mut out, col);
    }

    for slug in sorted_global_slugs(registry) {
        let global = &registry.globals[slug];
        render_global_impl(&mut out, global);
    }

    out
}

/// Render the numeric getters. A number field arrives as `IntValue` (integers,
/// exact) or `DoubleValue` (fractional); both collapse to `f64`.
fn render_num_helpers(out: &mut String) {
    w!(
        out,
        "fn get_num_opt(doc: &Document, name: &str) -> Option<f64> {{"
    );
    w!(out, "    doc.fields.as_ref()");
    w!(out, "        .and_then(|f| f.fields.get(name))");
    w!(out, "        .and_then(|v| match &v.kind {{");
    w!(
        out,
        "            Some(Kind::IntValue(n)) => Some(*n as f64),"
    );
    w!(out, "            Some(Kind::DoubleValue(n)) => Some(*n),");
    w!(out, "            _ => None,");
    w!(out, "        }})");
    w!(out, "}}");
    w!(out, "");
}

/// Render shared helper functions for field extraction.
fn render_helpers(out: &mut String) {
    w!(
        out,
        "// ── Extraction helpers ─────────────────────────────────────"
    );
    w!(out, "");
    w!(out, "fn get_str(doc: &Document, name: &str) -> String {{");
    w!(out, "    doc.fields.as_ref()");
    w!(out, "        .and_then(|f| f.fields.get(name))");
    w!(out, "        .and_then(|v| match &v.kind {{");
    w!(
        out,
        "            Some(Kind::StringValue(s)) => Some(s.clone()),"
    );
    w!(out, "            _ => None,");
    w!(out, "        }})");
    w!(out, "        .unwrap_or_default()");
    w!(out, "}}");
    w!(out, "");
    w!(
        out,
        "fn get_str_opt(doc: &Document, name: &str) -> Option<String> {{"
    );
    w!(out, "    let s = get_str(doc, name);");
    w!(out, "    if s.is_empty() {{ None }} else {{ Some(s) }}");
    w!(out, "}}");
    w!(out, "");
    render_num_helpers(out);

    w!(
        out,
        "fn get_bool_opt(doc: &Document, name: &str) -> Option<bool> {{"
    );
    w!(out, "    doc.fields.as_ref()");
    w!(out, "        .and_then(|f| f.fields.get(name))");
    w!(out, "        .and_then(|v| match &v.kind {{");
    w!(out, "            Some(Kind::BoolValue(b)) => Some(*b),");
    w!(out, "            _ => None,");
    w!(out, "        }})");
    w!(out, "}}");
    w!(out, "");
    w!(
        out,
        "fn get_str_list(doc: &Document, name: &str) -> Vec<String> {{"
    );
    w!(out, "    doc.fields.as_ref()");
    w!(out, "        .and_then(|f| f.fields.get(name))");
    w!(out, "        .and_then(|v| match &v.kind {{");
    w!(out, "            Some(Kind::ListValue(list)) => Some(");
    w!(out, "                list.values.iter()");
    w!(out, "                    .filter_map(|v| match &v.kind {{");
    w!(
        out,
        "                        Some(Kind::StringValue(s)) => Some(s.clone()),"
    );
    w!(out, "                        _ => None,");
    w!(out, "                    }})");
    w!(out, "                    .collect()");
    w!(out, "            ),");
    w!(out, "            _ => None,");
    w!(out, "        }})");
    w!(out, "        .unwrap_or_default()");
    w!(out, "}}");
    w!(out, "");

    // Numeric list: a `has_many` number field. Each element is `IntValue`
    // (exact) or `DoubleValue`; both collapse to `f64`, mirroring `get_num_opt`.
    w!(
        out,
        "fn get_num_list(doc: &Document, name: &str) -> Vec<f64> {{"
    );
    w!(out, "    doc.fields.as_ref()");
    w!(out, "        .and_then(|f| f.fields.get(name))");
    w!(out, "        .and_then(|v| match &v.kind {{");
    w!(out, "            Some(Kind::ListValue(list)) => Some(");
    w!(out, "                list.values.iter()");
    w!(out, "                    .filter_map(|v| match &v.kind {{");
    w!(
        out,
        "                        Some(Kind::IntValue(n)) => Some(*n as f64),"
    );
    w!(
        out,
        "                        Some(Kind::DoubleValue(n)) => Some(*n),"
    );
    w!(out, "                        _ => None,");
    w!(out, "                    }})");
    w!(out, "                    .collect()");
    w!(out, "            ),");
    w!(out, "            _ => None,");
    w!(out, "        }})");
    w!(out, "        .unwrap_or_default()");
    w!(out, "}}");
    w!(out, "");
}

/// Render the `FromDocument` trait definition.
fn render_from_document_trait(out: &mut String) {
    w!(
        out,
        "/// Trait for types that can be constructed from a proto Document."
    );
    w!(out, "pub trait FromDocument {{");
    w!(out, "    fn from_document(doc: &Document) -> Self;");
    w!(out, "}}");
    w!(out, "");
}

/// Hand-written Rust helpers (`struct_to_document` + `get_rel` + `get_rel_list`)
/// that the generated `from_document` impls call into. Emitted verbatim — they
/// have no per-collection or per-field interpolation, so a raw literal is the
/// source of truth, not a write-line-by-line chain.
const REL_HELPERS_SOURCE: &str = r#"
// ── Relationship helpers ──────────────────────────────────

fn struct_to_document(s: &DataMap) -> Document {
    let id = s.fields.get("id")
        .and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) => Some(s.clone()),
            _ => None,
        })
        .unwrap_or_default();

    Document {
        id,
        collection: String::new(),
        fields: Some(DataMap { fields: s.fields.clone() }),
        created_at: s.fields.get("created_at").and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) => Some(s.clone()),
            _ => None,
        }),
        updated_at: s.fields.get("updated_at").and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) => Some(s.clone()),
            _ => None,
        }),
    }
}

fn get_rel<T: FromDocument>(doc: &Document, name: &str) -> Option<Rel<T>> {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::StringValue(s)) if !s.is_empty() => Some(Rel::Id(s.clone())),
            Some(Kind::StructValue(s)) => {
                let inner = struct_to_document(s);
                Some(Rel::Doc(Box::new(T::from_document(&inner))))
            }
            _ => None,
        })
}

fn get_rel_list<T: FromDocument>(doc: &Document, name: &str) -> Vec<Rel<T>> {
    doc.fields.as_ref()
        .and_then(|f| f.fields.get(name))
        .and_then(|v| match &v.kind {
            Some(Kind::ListValue(list)) => Some(
                list.values.iter()
                    .filter_map(|v| match &v.kind {
                        Some(Kind::StringValue(s)) if !s.is_empty() => Some(Rel::Id(s.clone())),
                        Some(Kind::StructValue(s)) => {
                            let inner = struct_to_document(s);
                            Some(Rel::Doc(Box::new(T::from_document(&inner))))
                        }
                        _ => None,
                    })
                    .collect()
            ),
            _ => None,
        })
        .unwrap_or_default()
}
"#;

/// Render relationship helpers that use `FromDocument` + `Rel<T>`.
fn render_rel_helpers(out: &mut String) {
    out.push_str(REL_HELPERS_SOURCE);
    out.push('\n');
}

/// Render `from_document` impl for a collection.
fn render_collection_impl(out: &mut String, col: &CollectionDefinition) {
    let pascal = idents::rust_type(&to_pascal_case(&col.slug));

    // Sub-type from_struct impls for arrays
    for stf in collect_sub_type_fields(&col.fields, &pascal) {
        let sub_pascal = format!("{}{}", stf.parent_pascal, to_pascal_case(&stf.field.name));
        render_sub_type_from_struct(out, &sub_pascal, &stf.field.fields, stf.row_id);
    }

    w!(out, "impl {} {{", pascal);
    w!(out, "    pub fn from_document(doc: &Document) -> Self {{");
    w!(out, "        Self {{");
    w!(out, "            id: doc.id.clone(),");

    render_field_extractions(out, &col.fields, &pascal, "doc");
    render_system_extractions(out, col.has_drafts(), col.soft_delete);

    if col.timestamps {
        w!(out, "            created_at: doc.created_at.clone(),");
        w!(out, "            updated_at: doc.updated_at.clone(),");
    }

    w!(out, "        }}");
    w!(out, "    }}");
    w!(out, "}}");
    w!(out, "");
    w!(out, "impl FromDocument for {} {{", pascal);
    w!(out, "    fn from_document(doc: &Document) -> Self {{");
    w!(out, "        {}::from_document(doc)", pascal);
    w!(out, "    }}");
    w!(out, "}}");
    w!(out, "");
}

/// Render `from_document` impl for a global.
fn render_global_impl(out: &mut String, global: &GlobalDefinition) {
    let pascal = idents::rust_type(&to_pascal_case(&global.slug));

    for stf in collect_sub_type_fields(&global.fields, &pascal) {
        let sub_pascal = format!("{}{}", stf.parent_pascal, to_pascal_case(&stf.field.name));
        render_sub_type_from_struct(out, &sub_pascal, &stf.field.fields, stf.row_id);
    }

    w!(out, "impl {} {{", pascal);
    w!(out, "    pub fn from_document(doc: &Document) -> Self {{");
    w!(out, "        Self {{");
    w!(out, "            id: doc.id.clone(),");

    render_field_extractions(out, &global.fields, &pascal, "doc");
    render_system_extractions(out, global.has_drafts(), false);

    w!(out, "            created_at: doc.created_at.clone(),");
    w!(out, "            updated_at: doc.updated_at.clone(),");
    w!(out, "        }}");
    w!(out, "    }}");
    w!(out, "}}");
    w!(out, "");
    w!(out, "impl FromDocument for {} {{", pascal);
    w!(out, "    fn from_document(doc: &Document) -> Self {{");
    w!(out, "        {}::from_document(doc)", pascal);
    w!(out, "    }}");
    w!(out, "}}");
    w!(out, "");
}

/// Render field extraction lines for a struct's `from_document` body.
/// The canonical wrapper-flatten (`flatten_array_sub_fields`) promotes
/// Row/Collapsible/Tabs sub-fields to this level.
fn render_field_extractions(
    out: &mut String,
    fields: &[FieldDefinition],
    parent_pascal: &str,
    doc_var: &str,
) {
    for f in flatten_array_sub_fields(fields) {
        let extraction = field_extraction(f, parent_pascal, doc_var);
        w!(
            out,
            "            {}: {},",
            idents::rust_field(&f.name).ident,
            extraction
        );

        for column in f.companion_columns(&f.name) {
            let ident = idents::rust_field(&column).ident;
            w!(
                out,
                "            {ident}: get_str_opt({doc_var}, \"{column}\"),"
            );
        }
    }
}

/// Extraction lines for the stored system keys a read document carries.
fn render_system_extractions(out: &mut String, drafts: bool, soft_delete: bool) {
    for (present, key) in [(drafts, "_status"), (soft_delete, "_deleted_at")] {
        if present {
            w!(out, "            {key}: get_str_opt(doc, \"{key}\"),");
        }
    }
}

/// A list extraction, `None` when the list is empty.
fn opt_list(expr: &str, doc_var: &str, name: &str) -> String {
    format!(
        "{{ let v = {expr}({doc_var}, \"{name}\"); if v.is_empty() {{ None }} else {{ Some(v) }} }}"
    )
}

/// A scalar extraction through the `get_X_opt` getter.
fn scalar(base: &str, doc_var: &str, name: &str) -> String {
    format!("{base}_opt({doc_var}, \"{name}\")")
}

/// Build the `from_document` extraction expression for a sub-typed field,
/// calling the generated `from_struct`. `is_list` selects Array (a list of
/// structs) vs Group (a single struct).
fn sub_type_extraction(sub: &str, name: &str, doc_var: &str, is_list: bool) -> String {
    let arm = if is_list {
        format!(
            "Some(Kind::ListValue(list)) => Some(\
                list.values.iter()\
                    .filter_map(|v| match &v.kind {{\
                        Some(Kind::StructValue(s)) => Some({sub}::from_struct(s)),\
                        _ => None,\
                    }})\
                    .collect::<Vec<_>>()\
            ),"
        )
    } else {
        format!("Some(Kind::StructValue(s)) => Some({sub}::from_struct(s)),")
    };

    format!(
        "{doc_var}.fields.as_ref()\
        .and_then(|f| f.fields.get(\"{name}\"))\
        .and_then(|v| match &v.kind {{ {arm} _ => None, }})"
    )
}

/// Top-level select/radio-with-options: decode string(s) and wrap in the
/// generated enum's `From<String>` so the value matches the enum-typed field.
fn enum_extraction(enum_name: &str, doc_var: &str, name: &str, has_many: bool) -> String {
    if !has_many {
        return format!("get_str_opt({doc_var}, \"{name}\").map({enum_name}::from)");
    }

    let mapped = format!(
        "get_str_list({doc_var}, \"{name}\").into_iter().map({enum_name}::from).collect::<Vec<_>>()"
    );

    format!("{{ let v = {mapped}; if v.is_empty() {{ None }} else {{ Some(v) }} }}")
}

/// Nested (sub-field) select/radio-with-options — same as [`enum_extraction`]
/// but reading from a `DataMap` (`s`) instead of a `Document`.
fn enum_sub_extraction(enum_name: &str, name: &str, has_many: bool) -> String {
    if has_many {
        return format!(
            "s.fields.get(\"{name}\").and_then(|v| match &v.kind {{ {STR_LIST}, _ => None }})\
             .map(|l| l.into_iter().map({enum_name}::from).collect())"
        );
    }

    format!(
        "s.fields.get(\"{name}\").and_then(|v| match &v.kind {{ Some(Kind::StringValue(s)) => Some(s.clone()), _ => None }})\
         .map({enum_name}::from)"
    )
}

/// The match arms decoding a proto value into a polymorphic enum: a bare id
/// string → `Id`, a `{collection, ...}` struct → the matching document variant
/// (via the target's `from_document`). Shared by the top-level and nested paths.
fn poly_arms(poly_name: &str, targets: &[&str]) -> String {
    let mut variants = String::new();
    for t in targets {
        let variant = idents::rust_type(&to_pascal_case(t));
        let slug = idents::escape_str(t);
        wraw!(
            variants,
            "Some(\"{slug}\") => Some({poly_name}::Doc({poly_name}Ref::{variant}(Box::new({variant}::from_document(&__doc))))), "
        );
    }
    format!(
        "Some(Kind::StringValue(s)) if !s.is_empty() => Some({poly_name}::Id(s.clone())), \
         Some(Kind::StructValue(m)) => {{ \
             let __coll = m.fields.get(\"collection\").and_then(|v| match &v.kind {{ Some(Kind::StringValue(s)) => Some(s.as_str()), _ => None }}); \
             let __doc = struct_to_document(m); \
             match __coll {{ {variants}_ => None, }} \
         }},"
    )
}

/// A polymorphic-relationship extraction. `getter` is an `Option<&FieldValue>`
/// expression naming the field's value in the current context (top-level or
/// nested). Has-one is `Option<Poly>`; has-many is `Option<Vec<Poly>>`.
fn poly_extraction(poly_name: &str, targets: &[&str], getter: &str, has_many: bool) -> String {
    let arms = poly_arms(poly_name, targets);

    if has_many {
        return format!(
            "{getter}.and_then(|v| match &v.kind {{ Some(Kind::ListValue(l)) => Some(l.values.iter().filter_map(|v| match &v.kind {{ {arms} _ => None }}).collect::<Vec<_>>()), _ => None }})"
        );
    }

    format!("{getter}.and_then(|v| match &v.kind {{ {arms} _ => None }})")
}

/// Decode a top-level field, reading from a `Document` (`doc_var`). Dispatches on
/// the SHARED [`resolve_ty`] so this generator and `client/rust.rs` can never
/// disagree about a field's type — the whole class of proto↔client drift. Every
/// field decodes to an `Option`, matching the client structs: a draft may lack
/// required values, and field read access and `select` leave keys out.
fn field_extraction(field: &FieldDefinition, parent_pascal: &str, doc_var: &str) -> String {
    let name = &field.name;

    match &resolve_ty(field, parent_pascal) {
        // Strings (incl. id-string relationships: empty-collection upload / no target).
        FieldTy::Str
        | FieldTy::Rel {
            target: None,
            many: false,
        } => scalar("get_str", doc_var, name),
        FieldTy::StrList
        | FieldTy::Rel {
            target: None,
            many: true,
        } => opt_list("get_str_list", doc_var, name),
        FieldTy::Num => scalar("get_num", doc_var, name),
        FieldTy::Bool => scalar("get_bool", doc_var, name),
        FieldTy::NumList => opt_list("get_num_list", doc_var, name),
        // `resolve_ty` never produces the `locale = "all"` shape; the decoders
        // target the single-locale structs.
        FieldTy::Json | FieldTy::Map | FieldTy::JsonList | FieldTy::Localized(_) => {
            COMPLEX_FALLBACK.to_string()
        }

        // Typed relationship/upload — `get_rel(_list)` decode both the id string
        // and the populated document; `T` is inferred from the struct field type.
        FieldTy::Rel {
            target: Some(_),
            many: true,
        } => opt_list("get_rel_list", doc_var, name),
        FieldTy::Rel {
            target: Some(_),
            many: false,
        } => format!("get_rel({doc_var}, \"{name}\")"),

        FieldTy::PolyRel {
            name: pn,
            targets,
            many,
        } => poly_extraction(
            &idents::rust_type(pn),
            &targets.iter().map(String::as_str).collect::<Vec<_>>(),
            &format!("{doc_var}.fields.as_ref().and_then(|f| f.fields.get(\"{name}\"))"),
            *many,
        ),
        FieldTy::Enum { name: en, many, .. } => {
            enum_extraction(&idents::rust_type(en), doc_var, name, *many)
        }
        FieldTy::SubType { name: sn, list } => {
            sub_type_extraction(&idents::rust_type(sn), name, doc_var, *list)
        }
    }
}

/// The proto wire carries no structured JSON/blocks/join, so these decode to
/// `None`.
const COMPLEX_FALLBACK: &str = "None /* complex field */";

/// Render a `from_struct` impl for an array/group sub-type. `pascal` is the
/// sub-type's compound name (e.g. `PostsItems`), threaded into
/// [`sub_field_extraction`] so a nested group/array references the right
/// nested sub-type name. `row_id` reads the junction `id` a relational array
/// row carries.
fn render_sub_type_from_struct(
    out: &mut String,
    pascal: &str,
    fields: &[FieldDefinition],
    row_id: bool,
) {
    w!(out, "impl {} {{", pascal);
    w!(out, "    fn from_struct(s: &DataMap) -> Self {{");
    w!(out, "        Self {{");

    if row_id {
        w!(
            out,
            "            id: s.fields.get(\"id\").and_then(|v| match &v.kind {{ Some(Kind::StringValue(s)) => Some(s.clone()), _ => None }}),"
        );
    }

    // Flatten layout wrappers exactly like `render_field_extractions` and the
    // client struct-definition side — a Row/Collapsible/Tabs nested inside an
    // array/group otherwise reaches `resolve_ty` and panics.
    for f in flatten_array_sub_fields(fields) {
        let extraction = sub_field_extraction(f, pascal);
        w!(
            out,
            "            {}: {},",
            idents::rust_field(&f.name).ident,
            extraction
        );

        for column in f.companion_columns(&f.name) {
            let ident = idents::rust_field(&column).ident;
            w!(
                out,
                "            {ident}: s.fields.get(\"{column}\").and_then(|v| match &v.kind {{ Some(Kind::StringValue(s)) => Some(s.clone()), _ => None }}),"
            );
        }
    }

    w!(out, "        }}");
    w!(out, "    }}");
    w!(out, "}}");
    w!(out, "");
}

/// Match arm decoding a `ListValue` of strings into a `Vec<String>` (a
/// `has_many` scalar sub-field, an options-less select/radio, or an
/// empty-collection upload).
const STR_LIST: &str = "Some(Kind::ListValue(l)) => Some(l.values.iter().filter_map(|v| match &v.kind { Some(Kind::StringValue(s)) => Some(s.clone()), _ => None }).collect())";

/// The nested match arm decoding a typed relationship into `Rel<T>`: an id string
/// (`Rel::Id`) or a populated document (`Rel::Doc` via `struct_to_document` +
/// `from_document`). `has_many` wraps the per-element form in a list decode.
fn nested_rel_arm(t: &str, has_many: bool) -> String {
    let one = format!(
        "Some(Kind::StringValue(s)) if !s.is_empty() => Some(Rel::Id(s.clone())), Some(Kind::StructValue(m)) => Some(Rel::Doc(Box::new({t}::from_document(&struct_to_document(m)))))"
    );
    if has_many {
        format!(
            "Some(Kind::ListValue(l)) => Some(l.values.iter().filter_map(|v| match &v.kind {{ {one}, _ => None }}).collect())"
        )
    } else {
        one
    }
}

/// Extraction for a sub-type field, reading from a nested `DataMap` (`s`).
///
/// Mirrors the Rust client printer's (`super::client::rust`) type mapping so the
/// decoded value's type matches the generated struct field: `has_many` scalars →
/// `Vec`, select/radio-with-options → the generated enum via `From<String>`,
/// relationships/uploads → `Rel<T>` / `Vec<Rel<T>>`, polymorphic → the generated
/// discriminated enum, empty-collection uploads → `String` / `Vec<String>`, and a
/// nested group/array → the child sub-type via its own `from_struct`.
/// `parent_pascal` is the enclosing sub-type's compound name. Every sub-field
/// decodes to an `Option`, matching the client sub-types.
fn sub_field_extraction(field: &FieldDefinition, parent_pascal: &str) -> String {
    let name = &field.name;

    // An `Option<T>` reading `s.fields[name]` through the match arm `arm`.
    let get = |arm: &str| {
        format!("s.fields.get(\"{name}\").and_then(|v| match &v.kind {{ {arm}, _ => None }})")
    };

    match &resolve_ty(field, parent_pascal) {
        // Strings (incl. id-string relationships: empty-collection upload / no target).
        FieldTy::Str
        | FieldTy::Rel {
            target: None,
            many: false,
        } => get("Some(Kind::StringValue(s)) => Some(s.clone())"),
        FieldTy::StrList
        | FieldTy::Rel {
            target: None,
            many: true,
        } => get(STR_LIST),
        FieldTy::Num => get(
            "Some(Kind::IntValue(n)) => Some(*n as f64), Some(Kind::DoubleValue(n)) => Some(*n)",
        ),
        FieldTy::Bool => get("Some(Kind::BoolValue(b)) => Some(*b)"),
        FieldTy::NumList => get(
            "Some(Kind::ListValue(l)) => Some(l.values.iter().filter_map(|v| match &v.kind { Some(Kind::IntValue(n)) => Some(*n as f64), Some(Kind::DoubleValue(n)) => Some(*n), _ => None }).collect())",
        ),
        // `resolve_ty` never produces the `locale = "all"` shape; the decoders
        // target the single-locale structs.
        FieldTy::Json | FieldTy::Map | FieldTy::JsonList | FieldTy::Localized(_) => {
            COMPLEX_FALLBACK.to_string()
        }

        // Typed relationship — id string OR populated document. Decoding the
        // `StructValue` form is what closes the nested-populated-relationship gap.
        FieldTy::Rel {
            target: Some(t),
            many,
        } => get(&nested_rel_arm(&idents::rust_type(t), *many)),

        FieldTy::PolyRel {
            name: pn,
            targets,
            many,
        } => poly_extraction(
            &idents::rust_type(pn),
            &targets.iter().map(String::as_str).collect::<Vec<_>>(),
            &format!("s.fields.get(\"{name}\")"),
            *many,
        ),
        FieldTy::Enum { name: en, many, .. } => {
            enum_sub_extraction(&idents::rust_type(en), name, *many)
        }

        FieldTy::SubType {
            name: sn,
            list: false,
        } => {
            let sub = idents::rust_type(sn);
            get(&format!(
                "Some(Kind::StructValue(m)) => Some({sub}::from_struct(m))"
            ))
        }
        FieldTy::SubType {
            name: sn,
            list: true,
        } => {
            let sub = idents::rust_type(sn);
            get(&format!(
                "Some(Kind::ListValue(l)) => Some(l.values.iter().filter_map(|v| match &v.kind {{ Some(Kind::StructValue(m)) => Some({sub}::from_struct(m)), _ => None }}).collect())"
            ))
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::{FieldAdmin, FieldType, LocalizedString, RelationshipConfig, SelectOption};

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Text)
            .required(required)
            .build()
    }

    fn make_col(slug: &str, fields: Vec<FieldDefinition>) -> CollectionDefinition {
        let mut def = CollectionDefinition::new(slug);
        def.timestamps = true;
        def.fields = fields;
        def
    }

    /// Regression: a layout wrapper (Row/Collapsible/Tabs) nested INSIDE an
    /// array sub-type used to reach `resolve_ty` unflattened and panic with
    /// "layout wrappers are flattened before type resolution". The example
    /// project's collections hit this on `typegen proto`. The wrapped
    /// sub-field must be promoted into the sub-type's `from_struct`.
    #[test]
    fn proto_sub_type_flattens_layout_wrappers_inside_arrays() {
        let mut row = FieldDefinition::builder("stats_row", FieldType::Row).build();
        row.fields = vec![text_field("label", false)];

        let mut items = FieldDefinition::builder("items", FieldType::Array).build();
        items.fields = vec![text_field("title", true), row];

        let col = make_col("projects", vec![items]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("label: s.fields.get(\"label\")"),
            "the Row-wrapped sub-field must appear in from_struct: {out}"
        );
    }

    /// A relational array row's `from_struct` reads its junction `id`; a row
    /// nested inside another row is JSON without one.
    #[test]
    fn proto_array_rows_read_their_id() {
        let mut notes = FieldDefinition::builder("notes", FieldType::Array).build();
        notes.fields = vec![text_field("body", false)];
        let mut items = FieldDefinition::builder("items", FieldType::Array).build();
        items.fields = vec![text_field("title", true), notes];

        let col = make_col("projects", vec![items]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        let impl_of = |name: &str| {
            let start = out.find(&format!("impl {name} {{")).expect(name);
            let rest = &out[start..];
            rest[..rest.find("\n}\n").unwrap_or(rest.len())].to_string()
        };

        assert!(
            impl_of("ProjectsItems").contains("id: s.fields.get(\"id\")"),
            "{out}"
        );
        assert!(
            !impl_of("ProjectsItemsNotes").contains("id: s.fields.get(\"id\")"),
            "{out}"
        );
    }

    /// Identifier safety: the `from_document` struct-field position must be the
    /// SANITIZED ident (matching the generated struct), while the wire lookup
    /// keeps the raw key. A keyword field `type` → `r#type: get_str(doc, "type")`.
    #[test]
    fn proto_field_assignment_uses_sanitized_ident() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("type", FieldType::Text)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("r#type: get_str_opt(doc, \"type\")"),
            "struct field must be sanitized while the lookup uses the raw key: {out}"
        );
    }

    /// Regression: a timezone date's `<name>_tz` companion was assigned under
    /// its raw key, so a digit-leading field (`2fa_tz`) generated Rust that
    /// doesn't compile. The struct field is sanitized; the lookup keeps the key.
    #[test]
    fn proto_timezone_companion_uses_a_sanitized_ident() {
        let col = make_col(
            "events",
            vec![
                FieldDefinition::builder("2fa", FieldType::Date)
                    .timezone(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        let ident = idents::rust_field("2fa_tz").ident;
        assert_ne!(ident, "2fa_tz");
        assert!(
            out.contains(&format!("{ident}: get_str_opt(doc, \"2fa_tz\")")),
            "{out}"
        );
    }

    /// A code field with a language allow-list.
    fn code_with_languages(name: &str) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Code)
            .admin(
                FieldAdmin::builder()
                    .languages(vec!["python".to_string()])
                    .build(),
            )
            .build()
    }

    /// A code field's `<name>_lang` companion is decoded under a sanitized
    /// ident, the lookup keeping the raw key.
    #[test]
    fn proto_language_companion_uses_a_sanitized_ident() {
        let col = make_col("snippets", vec![code_with_languages("2fa")]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        let ident = idents::rust_field("2fa_lang").ident;
        assert_ne!(ident, "2fa_lang");
        assert!(
            out.contains(&format!("{ident}: get_str_opt(doc, \"2fa_lang\")")),
            "{out}"
        );
    }

    /// An array row's `from_struct` decodes a code sub-field's `<name>_lang`
    /// companion; a code field without an allow-list has none.
    #[test]
    fn proto_array_row_decodes_the_language_companion() {
        let items = FieldDefinition::builder("items", FieldType::Array)
            .fields(vec![
                code_with_languages("example"),
                FieldDefinition::builder("plain", FieldType::Code).build(),
            ])
            .build();
        let col = make_col("snippets", vec![items]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("example_lang: s.fields.get(\"example_lang\")"),
            "{out}"
        );
        assert!(!out.contains("plain_lang"), "{out}");
    }

    #[test]
    fn proto_collection_output() {
        let col = make_col(
            "posts",
            vec![text_field("title", true), text_field("content", false)],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(out.contains("impl Posts {"));
        assert!(out.contains("fn from_document(doc: &Document) -> Self"));
        assert!(out.contains("id: doc.id.clone()"));
        assert!(out.contains("title: get_str_opt(doc, \"title\")"));
        assert!(out.contains("content: get_str_opt(doc, \"content\")"));
        assert!(out.contains("created_at: doc.created_at.clone()"));
    }

    /// Alignment with `client/rust.rs`: a select/radio WITH options decodes
    /// through the generated enum's `From<String>` (the client field is the enum).
    #[test]
    fn proto_select_with_options_wraps_in_enum() {
        let col = make_col(
            "tasks",
            vec![
                FieldDefinition::builder("status", FieldType::Select)
                    .required(true)
                    .options(vec![SelectOption::new(
                        LocalizedString::Plain("Todo".into()),
                        "todo",
                    )])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);
        assert!(
            out.contains("status: get_str_opt(doc, \"status\").map(TasksStatus::from)"),
            "select→enum: {out}"
        );
    }

    /// A required single relationship is `Option<Rel<T>>` on the client (populate
    /// can null it), so proto must NOT unwrap it.
    #[test]
    fn proto_single_relationship_is_optional() {
        let col = make_col(
            "comments",
            vec![
                FieldDefinition::builder("author", FieldType::Relationship)
                    .required(true)
                    .relationship(RelationshipConfig::new("users", false))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);
        assert!(out.contains("author: get_rel(doc, \"author\"),"), "{out}");
        assert!(!out.contains("unwrap_or(Rel::Id"), "no unwrap: {out}");
    }

    /// A relationship nested inside a group/array decodes BOTH forms — the id
    /// string and the populated document (the gap the old sub-field path missed).
    #[test]
    fn proto_nested_relationship_decodes_populated_doc() {
        let author = FieldDefinition::builder("author", FieldType::Relationship)
            .relationship(RelationshipConfig::new("users", false))
            .build();
        let group = FieldDefinition::builder("meta", FieldType::Group)
            .fields(vec![author])
            .build();
        let col = make_col("posts", vec![group]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);
        assert!(
            out.contains("Rel::Doc(Box::new(Users::from_document(&struct_to_document(m))))"),
            "nested relationship decodes the populated document: {out}"
        );
    }

    /// A polymorphic relationship decodes into the generated discriminated enum —
    /// id string → `Id`, `{collection, ...}` struct → the matching doc variant.
    #[test]
    fn proto_polymorphic_decodes_discriminated_enum() {
        let mut rc = RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".into(), "pages".into()];
        let col = make_col(
            "comments",
            vec![
                FieldDefinition::builder("subject", FieldType::Relationship)
                    .required(true)
                    .relationship(rc)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);
        assert!(
            out.contains("CommentsSubject::Id(s.clone())"),
            "id form: {out}"
        );
        assert!(
            out.contains(
                "Some(\"posts\") => Some(CommentsSubject::Doc(CommentsSubjectRef::Posts(Box::new(Posts::from_document"
            ),
            "populated variant: {out}"
        );
        assert!(
            out.contains("struct_to_document(m)"),
            "reads the struct: {out}"
        );
    }

    #[test]
    fn proto_number_and_bool_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("price", FieldType::Number)
                    .required(true)
                    .build(),
                FieldDefinition::builder("active", FieldType::Checkbox).build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(out.contains("price: get_num_opt(doc, \"price\")"));
        assert!(out.contains("active: get_bool_opt(doc, \"active\")"));
    }

    #[test]
    fn proto_relationship_fields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("author", FieldType::Relationship)
                    .required(true)
                    .relationship(RelationshipConfig::new("users", false))
                    .build(),
                FieldDefinition::builder("tags", FieldType::Relationship)
                    .relationship(RelationshipConfig::new("tags", true))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("author: get_rel(doc, \"author\")"),
            "required has-one should use get_rel: {out}"
        );
        assert!(
            out.contains("get_rel_list(doc, \"tags\")"),
            "optional has-many should use get_rel_list: {out}"
        );
    }

    /// Regression: a required relationship SUB-field (inside an array row) must
    /// decode to `Rel::Id`, not `Default::default()` — `Rel` has no `Default`, so
    /// the old fallback produced non-compiling client code (E0277).
    #[test]
    fn proto_sub_field_relationship_uses_rel_not_default() {
        let product = FieldDefinition::builder("product", FieldType::Relationship)
            .required(true)
            .relationship(RelationshipConfig::new("products", false))
            .build();
        let items = FieldDefinition::builder("items", FieldType::Array)
            .fields(vec![text_field("label", true), product])
            .build();
        let col = make_col("orders", vec![items]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(out.contains("impl OrdersItems {"), "sub-type impl: {out}");
        assert!(
            out.contains("Some(Kind::StringValue(s)) if !s.is_empty() => Some(Rel::Id(s.clone()))"),
            "relationship sub-field must decode to Rel::Id: {out}"
        );
        assert!(
            !out.contains("product: Default::default()"),
            "relationship must not fall back to Default: {out}"
        );
    }

    /// Regression: a `has_many` NUMBER sub-field must decode as a numeric list
    /// (`Vec<f64>`), not a string list — the old code routed it through
    /// `get_str_list`, an E0308 against the `Vec<f64>` struct field.
    #[test]
    fn proto_sub_field_has_many_number_decodes_numeric() {
        let mut scores = FieldDefinition::builder("scores", FieldType::Number).build();
        scores.has_many = true;
        let items = FieldDefinition::builder("items", FieldType::Array)
            .fields(vec![scores])
            .build();
        let col = make_col("games", vec![items]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("impl GamesItems {"),
            "compound sub-type: {out}"
        );
        assert!(
            out.contains("Some(Kind::IntValue(n)) => Some(*n as f64)"),
            "has-many number sub-field must decode numerically: {out}"
        );
    }

    /// Regression: a group nested inside an array row uses the COMPOUND sub-type
    /// name and decodes via that sub-type's `from_struct` — previously it fell
    /// back to `Default::default()` (silent empty / E0277).
    #[test]
    fn proto_nested_group_in_array_uses_compound_from_struct() {
        let meta = FieldDefinition::builder("meta", FieldType::Group)
            .fields(vec![text_field("author", true)])
            .build();
        let items = FieldDefinition::builder("items", FieldType::Array)
            .fields(vec![meta])
            .build();
        let col = make_col("posts", vec![items]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("impl PostsItemsMeta {"),
            "nested group must get a compound sub-type: {out}"
        );
        assert!(
            out.contains("PostsItemsMeta::from_struct"),
            "nested group must decode via from_struct: {out}"
        );
    }

    /// Regression (compound-path collision): a top-level group AND a same-named
    /// group nested in an array must produce DISTINCT sub-types, not two `impl
    /// PostsSeo` (which redeclares/collides in the generated client).
    #[test]
    fn proto_same_name_group_at_two_depths_no_collision() {
        let nested_seo = FieldDefinition::builder("seo", FieldType::Group)
            .fields(vec![text_field("keyword", true)])
            .build();
        let variants = FieldDefinition::builder("variants", FieldType::Array)
            .fields(vec![nested_seo])
            .build();
        let top_seo = FieldDefinition::builder("seo", FieldType::Group)
            .fields(vec![text_field("title", true)])
            .build();
        let col = make_col("posts", vec![top_seo, variants]);
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(out.contains("impl PostsSeo {"), "top-level: {out}");
        assert!(
            out.contains("impl PostsVariantsSeo {"),
            "nested must be compound-named, not a second PostsSeo: {out}"
        );
    }

    #[test]
    fn proto_array_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![
                        text_field("label", true),
                        FieldDefinition::builder("done", FieldType::Checkbox).build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("impl PostsItems {"),
            "should generate sub-type impl: {out}"
        );
        assert!(
            out.contains("fn from_struct(s: &DataMap)"),
            "should have from_struct: {out}"
        );
        assert!(
            out.contains("PostsItems::from_struct(s)"),
            "should call from_struct in array extraction: {out}"
        );
    }

    #[test]
    fn proto_group_calls_from_struct_not_default() {
        // Regression: a top-level Group used to fall through to
        // `Default::default()` (silent data loss) even though its `from_struct`
        // impl is generated. It must extract the nested struct.
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("seo", FieldType::Group)
                    .fields(vec![text_field("title", true)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("impl PostsSeo {"),
            "should generate group sub-type impl: {out}"
        );
        assert!(
            out.contains("PostsSeo::from_struct(s)"),
            "group must extract via from_struct, not default: {out}"
        );
    }

    #[test]
    fn proto_helpers_output() {
        let mut out = String::new();
        render_helpers(&mut out);

        assert!(out.contains("fn get_str(doc: &Document, name: &str) -> String"));
        assert!(out.contains("fn get_str_opt(doc: &Document, name: &str) -> Option<String>"));
        assert!(out.contains("fn get_num_opt(doc: &Document, name: &str) -> Option<f64>"));
        assert!(out.contains("fn get_bool_opt(doc: &Document, name: &str) -> Option<bool>"));
        // Every decoded field is optional, so no non-optional numeric or boolean
        // getter is emitted for the generated code to leave unused.
        assert!(!out.contains("fn get_num(doc"), "{out}");
        assert!(!out.contains("fn get_bool(doc"), "{out}");
        assert!(out.contains("fn get_str_list(doc: &Document, name: &str) -> Vec<String>"));
    }

    #[test]
    fn proto_full_render() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        let out = render(&registry, "crate::proto");

        assert!(out.contains("use crate::proto::{DataMap, Document};"));
        assert!(out.contains("use crate::proto::field_value::Kind;"));
        assert!(out.contains("impl Posts {"));
    }

    /// Regression: the generated Rust client must decode the typed `FieldValue`
    /// wire format, never the removed `google.protobuf.Struct`. It references
    /// `field_value::Kind` + `IntValue`/`DoubleValue`/`DataMap`, and must NOT
    /// emit `prost_types` or the removed `NumberValue` variant.
    #[test]
    fn proto_uses_typed_field_value_not_struct() {
        let mut registry = Registry::new();
        registry.register_collection(make_col(
            "items",
            vec![
                FieldDefinition::builder("price", FieldType::Number)
                    .required(true)
                    .build(),
            ],
        ));
        let out = render(&registry, "crate::proto");

        assert!(
            out.contains("use crate::proto::field_value::Kind;"),
            "{out}"
        );
        assert!(
            out.contains("use crate::proto::{DataMap, Document};"),
            "{out}"
        );
        assert!(
            out.contains("Some(Kind::IntValue(n)) => Some(*n as f64)"),
            "{out}"
        );
        assert!(
            out.contains("Some(Kind::DoubleValue(n)) => Some(*n)"),
            "{out}"
        );
        assert!(out.contains("fn struct_to_document(s: &DataMap)"), "{out}");

        assert!(
            !out.contains("prost_types"),
            "generated client must not reference prost_types: {out}"
        );
        assert!(
            !out.contains("NumberValue"),
            "generated client must not reference the removed NumberValue: {out}"
        );
    }

    #[test]
    fn proto_row_promotes_subfields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("row", FieldType::Row)
                    .fields(vec![text_field("first", true), text_field("last", false)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection_impl(&mut out, &col);

        assert!(
            out.contains("first: get_str_opt(doc, \"first\")"),
            "row sub-fields promoted: {out}"
        );
        assert!(
            out.contains("last: get_str_opt(doc, \"last\")"),
            "row sub-fields promoted: {out}"
        );
        assert!(
            !out.contains("row:"),
            "row field itself should not appear: {out}"
        );
    }
}
