//! Rust type definition generator — structs with serde derives for gRPC clients.

use std::fmt::Write;

use crate::core::collection::{CollectionDefinition, GlobalDefinition};
use crate::core::field::{FieldDefinition, FieldType};
use crate::core::Registry;

use super::{is_optional, rel_has_many, sorted_collection_slugs, sorted_global_slugs, to_pascal_case};

pub(super) fn render(registry: &Registry) -> String {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by crap-cms. Do not edit.").expect("write to String");
    writeln!(out).expect("write to String");
    writeln!(out, "use serde::{{Deserialize, Serialize}};\n").expect("write to String");

    for slug in sorted_collection_slugs(registry) {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    for slug in sorted_global_slugs(registry) {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    out
}

fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Array sub-types
    for f in &col.fields {
        if f.field_type == FieldType::Array && !f.fields.is_empty() {
            let sub_pascal = format!("{}{}", pascal, to_pascal_case(&f.name));
            writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").expect("write to String");
            writeln!(out, "pub struct {} {{", sub_pascal).expect("write to String");
            for sf in &f.fields {
                write_field(out, sf);
            }
            writeln!(out, "}}\n").expect("write to String");
        }
    }

    // Document struct
    writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").expect("write to String");
    writeln!(out, "pub struct {} {{", pascal).expect("write to String");
    writeln!(out, "    pub id: String,").expect("write to String");
    for f in &col.fields {
        write_field_with_context(out, f, &pascal);
    }
    if col.timestamps {
        writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").expect("write to String");
        writeln!(out, "    pub created_at: Option<String>,").expect("write to String");
        writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").expect("write to String");
        writeln!(out, "    pub updated_at: Option<String>,").expect("write to String");
    }
    writeln!(out, "}}\n").expect("write to String");
}

fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    writeln!(out, "#[derive(Debug, Clone, Serialize, Deserialize)]").expect("write to String");
    writeln!(out, "pub struct {} {{", pascal).expect("write to String");
    writeln!(out, "    pub id: String,").expect("write to String");
    for f in &global.fields {
        write_field(out, f);
    }
    writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").expect("write to String");
    writeln!(out, "    pub created_at: Option<String>,").expect("write to String");
    writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").expect("write to String");
    writeln!(out, "    pub updated_at: Option<String>,").expect("write to String");
    writeln!(out, "}}\n").expect("write to String");
}

fn write_field(out: &mut String, field: &FieldDefinition) {
    write_field_with_context(out, field, "");
}

fn write_field_with_context(out: &mut String, field: &FieldDefinition, parent_pascal: &str) {
    // Row is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Row {
        for sub in &field.fields {
            write_field_with_context(out, sub, parent_pascal);
        }
        return;
    }
    // Collapsible is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Collapsible {
        for sub in &field.fields {
            write_field_with_context(out, sub, parent_pascal);
        }
        return;
    }
    // Tabs is layout-only — promote sub-fields to parent level (no prefix)
    if field.field_type == FieldType::Tabs {
        for tab in &field.tabs {
            for sub in &tab.fields {
                write_field_with_context(out, sub, parent_pascal);
            }
        }
        return;
    }
    // Emit a comment for polymorphic relationships listing target collections
    if field.field_type == FieldType::Relationship {
        if let Some(rc) = &field.relationship {
            if rc.is_polymorphic() {
                let targets = rc.all_collections().join(", ");
                writeln!(out, "    /// Polymorphic relationship — targets: {}", targets).expect("write to String");
            }
        }
    }
    let rust_type = field_to_rust(field, parent_pascal);
    if is_optional(field) {
        writeln!(out, "    #[serde(skip_serializing_if = \"Option::is_none\")]").expect("write to String");
        writeln!(out, "    pub {}: Option<{}>,", field.name, rust_type).expect("write to String");
    } else {
        writeln!(out, "    pub {}: {},", field.name, rust_type).expect("write to String");
    }
}

fn field_to_rust(field: &FieldDefinition, parent_pascal: &str) -> String {
    match &field.field_type {
        FieldType::Text => {
            if field.has_many { "Vec<String>".to_string() } else { "String".to_string() }
        }
        FieldType::Textarea | FieldType::Email | FieldType::Date
        | FieldType::Richtext | FieldType::Code => "String".to_string(),
        FieldType::Upload => {
            if rel_has_many(field) {
                "Vec<String>".to_string()
            } else {
                "String".to_string()
            }
        }
        FieldType::Select | FieldType::Radio => {
            if field.has_many {
                "Vec<String>".to_string()
            } else {
                "String".to_string()
            }
        }
        FieldType::Number => {
            if field.has_many { "Vec<f64>".to_string() } else { "f64".to_string() }
        }
        FieldType::Checkbox => "bool".to_string(),
        FieldType::Json => "serde_json::Value".to_string(),
        FieldType::Relationship => {
            match &field.relationship {
                Some(rc) if rc.is_polymorphic() && rc.has_many => "Vec<String>".to_string(),
                Some(rc) if rc.is_polymorphic() => "String".to_string(),
                Some(rc) if rc.has_many => "Vec<String>".to_string(),
                _ => "String".to_string(),
            }
        }
        FieldType::Array => {
            if field.fields.is_empty() {
                "Vec<serde_json::Value>".to_string()
            } else {
                format!("Vec<{}{}>", parent_pascal, to_pascal_case(&field.name))
            }
        }
        FieldType::Group => "serde_json::Value".to_string(),
        FieldType::Row => "serde_json::Value".to_string(), // layout-only; sub-fields are promoted
        FieldType::Collapsible => "serde_json::Value".to_string(), // layout-only; sub-fields are promoted
        FieldType::Tabs => "serde_json::Value".to_string(), // layout-only; sub-fields are promoted
        FieldType::Blocks => "Vec<serde_json::Value>".to_string(),
        FieldType::Join => "Vec<serde_json::Value>".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::collection::{
        CollectionAccess, CollectionAdmin, CollectionHooks, CollectionLabels,
    };
    use crate::core::field::{BlockDefinition, LocalizedString, RelationshipConfig, SelectOption};

    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition {
            name: name.to_string(),
            required,
            ..Default::default()
        }
    }

    fn make_col(slug: &str, fields: Vec<FieldDefinition>) -> CollectionDefinition {
        CollectionDefinition {
            slug: slug.to_string(),
            labels: CollectionLabels::default(),
            timestamps: true,
            fields,
            admin: CollectionAdmin::default(),
            hooks: CollectionHooks::default(),
            auth: None,
            upload: None,
            access: CollectionAccess::default(),
            mcp: Default::default(),
            live: None,
            versions: None,
            indexes: Vec::new(),
        }
    }

    #[test]
    fn rust_collection_output() {
        let col = make_col("posts", vec![text_field("title", true), text_field("content", false)]);

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("#[derive(Debug, Clone, Serialize, Deserialize)]"));
        assert!(out.contains("pub struct Posts {"));
        assert!(out.contains("    pub id: String,"));
        assert!(out.contains("    pub title: String,"));
        assert!(out.contains("    pub content: Option<String>,"));
        assert!(out.contains("    pub created_at: Option<String>,"));
    }

    #[test]
    fn rust_relationship_has_many() {
        let col = make_col("posts", vec![
            FieldDefinition {
                name: "tags".to_string(),
                field_type: FieldType::Relationship,
                relationship: Some(RelationshipConfig {
                    collection: "tags".to_string(),
                    has_many: true,
                    max_depth: None,
                    polymorphic: vec![],
                }),
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Option<Vec<String>>"));
    }

    #[test]
    fn rust_polymorphic_has_one() {
        let col = make_col("comments", vec![
            FieldDefinition {
                name: "subject".to_string(),
                field_type: FieldType::Relationship,
                required: true,
                relationship: Some(RelationshipConfig {
                    collection: "posts".to_string(),
                    has_many: false,
                    max_depth: None,
                    polymorphic: vec!["posts".to_string(), "pages".to_string()],
                }),
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Polymorphic has-one = String (stores "collection/id" composite)
        assert!(out.contains("pub subject: String,"), "polymorphic has-one should be String: {}", out);
        assert!(out.contains("Polymorphic relationship"), "should have polymorphic comment: {}", out);
        assert!(out.contains("posts"), "comment should list target collections: {}", out);
        assert!(out.contains("pages"), "comment should list target collections: {}", out);
    }

    #[test]
    fn rust_polymorphic_has_many() {
        let col = make_col("posts", vec![
            FieldDefinition {
                name: "related".to_string(),
                field_type: FieldType::Relationship,
                relationship: Some(RelationshipConfig {
                    collection: "articles".to_string(),
                    has_many: true,
                    max_depth: None,
                    polymorphic: vec!["articles".to_string(), "videos".to_string()],
                }),
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Polymorphic has-many = Vec<String> (array of "collection/id" composites)
        assert!(out.contains("Vec<String>"), "polymorphic has-many should be Vec<String>: {}", out);
        assert!(out.contains("Polymorphic relationship"), "should have polymorphic comment: {}", out);
        assert!(out.contains("articles"), "comment should list target collections: {}", out);
        assert!(out.contains("videos"), "comment should list target collections: {}", out);
    }

    #[test]
    fn rust_relationship_has_one_required() {
        let col = make_col("posts", vec![
            FieldDefinition {
                name: "author".to_string(),
                field_type: FieldType::Relationship,
                required: true,
                relationship: Some(RelationshipConfig {
                    collection: "users".to_string(),
                    has_many: false,
                    max_depth: None,
                    polymorphic: vec![],
                }),
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub author: String,"));
    }

    #[test]
    fn rust_number_checkbox_json_fields() {
        let col = make_col("items", vec![
            FieldDefinition { name: "price".to_string(), field_type: FieldType::Number, required: true, ..Default::default() },
            FieldDefinition { name: "active".to_string(), field_type: FieldType::Checkbox, ..Default::default() },
            FieldDefinition { name: "meta".to_string(), field_type: FieldType::Json, ..Default::default() },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub price: f64,"));
        assert!(out.contains("Option<bool>"));
        assert!(out.contains("Option<serde_json::Value>"));
    }

    #[test]
    fn rust_array_with_subfields() {
        let col = make_col("posts", vec![
            FieldDefinition {
                name: "items".to_string(),
                field_type: FieldType::Array,
                fields: vec![text_field("label", true)],
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub struct PostsItems {"));
        assert!(out.contains("Option<Vec<PostsItems>>"));
    }

    #[test]
    fn rust_array_without_subfields() {
        let col = make_col("posts", vec![
            FieldDefinition {
                name: "data".to_string(),
                field_type: FieldType::Array,
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Option<Vec<serde_json::Value>>"));
    }

    #[test]
    fn rust_group_and_blocks_fields() {
        let col = make_col("pages", vec![
            FieldDefinition { name: "seo".to_string(), field_type: FieldType::Group, ..Default::default() },
            FieldDefinition {
                name: "content".to_string(),
                field_type: FieldType::Blocks,
                blocks: vec![BlockDefinition {
                    block_type: "text".to_string(),
                    fields: vec![text_field("body", true)],
                    ..Default::default()
                }],
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Option<serde_json::Value>"), "group should be serde_json::Value");
        assert!(out.contains("Option<Vec<serde_json::Value>>"), "blocks should be Vec<serde_json::Value>");
    }

    #[test]
    fn rust_upload_and_select_fields() {
        let col = make_col("items", vec![
            FieldDefinition { name: "image".to_string(), field_type: FieldType::Upload, required: true, ..Default::default() },
            FieldDefinition {
                name: "status".to_string(),
                field_type: FieldType::Select,
                required: true,
                options: vec![
                    SelectOption { label: LocalizedString::Plain("Draft".into()), value: "draft".into() },
                ],
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub image: String,"));
        assert!(out.contains("pub status: String,"));
    }

    #[test]
    fn upload_has_many_generates_array_type() {
        let col = make_col("items", vec![
            FieldDefinition {
                name: "images".to_string(),
                field_type: FieldType::Upload,
                required: true,
                relationship: Some(RelationshipConfig {
                    collection: String::new(),
                    has_many: true,
                    max_depth: None,
                    polymorphic: vec![],
                }),
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub images: Vec<String>,"), "has-many upload should be Vec<String>: {}", out);
    }

    #[test]
    fn rust_global_output() {
        let global = crate::core::collection::GlobalDefinition {
            slug: "site_settings".to_string(),
            labels: CollectionLabels::default(),
            fields: vec![text_field("site_name", true)],
            hooks: CollectionHooks::default(),
            access: CollectionAccess::default(),
            mcp: Default::default(),
            live: None,
            versions: None,
        };
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(out.contains("pub struct SiteSettings {"));
        assert!(out.contains("pub id: String,"));
        assert!(out.contains("pub site_name: String,"));
        assert!(out.contains("pub created_at: Option<String>,"));
    }

    #[test]
    fn rust_full_render() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        registry.register_global(crate::core::collection::GlobalDefinition {
            slug: "settings".to_string(),
            labels: CollectionLabels::default(),
            fields: vec![text_field("name", true)],
            hooks: CollectionHooks::default(),
            access: CollectionAccess::default(),
            mcp: Default::default(),
            live: None,
            versions: None,
        });
        let out = render(&registry);
        assert!(out.contains("use serde::{Deserialize, Serialize};"));
        assert!(out.contains("pub struct Posts {"));
        assert!(out.contains("pub struct Settings {"));
    }

    #[test]
    fn rust_no_timestamps() {
        let mut col = make_col("tags", vec![text_field("name", true)]);
        col.timestamps = false;
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(!out.contains("created_at"));
    }

    #[test]
    fn rust_text_has_many() {
        let col = make_col("items", vec![
            FieldDefinition {
                name: "tags".to_string(),
                field_type: FieldType::Text,
                has_many: true,
                required: true,
                ..Default::default()
            },
            FieldDefinition {
                name: "labels".to_string(),
                field_type: FieldType::Text,
                has_many: true,
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub tags: Vec<String>,"), "required has-many text should be Vec<String>: {}", out);
        assert!(out.contains("Option<Vec<String>>"), "optional has-many text should be Option<Vec<String>>: {}", out);
    }

    #[test]
    fn rust_number_has_many() {
        let col = make_col("items", vec![
            FieldDefinition {
                name: "scores".to_string(),
                field_type: FieldType::Number,
                has_many: true,
                required: true,
                ..Default::default()
            },
            FieldDefinition {
                name: "weights".to_string(),
                field_type: FieldType::Number,
                has_many: true,
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub scores: Vec<f64>,"), "required has-many number should be Vec<f64>: {}", out);
        assert!(out.contains("Option<Vec<f64>>"), "optional has-many number should be Option<Vec<f64>>: {}", out);
    }

    #[test]
    fn rust_email_date_richtext_textarea() {
        let col = make_col("items", vec![
            FieldDefinition { name: "email".to_string(), field_type: FieldType::Email, required: true, ..Default::default() },
            FieldDefinition { name: "date".to_string(), field_type: FieldType::Date, required: true, ..Default::default() },
            FieldDefinition { name: "body".to_string(), field_type: FieldType::Richtext, required: true, ..Default::default() },
            FieldDefinition { name: "notes".to_string(), field_type: FieldType::Textarea, required: true, ..Default::default() },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        // All string types
        assert!(out.contains("pub email: String,"));
        assert!(out.contains("pub date: String,"));
        assert!(out.contains("pub body: String,"));
        assert!(out.contains("pub notes: String,"));
    }

    #[test]
    fn rust_code_join_radio_fields() {
        let col = make_col("items", vec![
            FieldDefinition { name: "snippet".to_string(), field_type: FieldType::Code, required: true, ..Default::default() },
            FieldDefinition { name: "refs".to_string(), field_type: FieldType::Join, ..Default::default() },
            FieldDefinition { name: "color".to_string(), field_type: FieldType::Radio, required: true, ..Default::default() },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub snippet: String,"), "code field should map to String: {}", out);
        assert!(out.contains("Option<Vec<serde_json::Value>>"), "join field should map to Vec<serde_json::Value>: {}", out);
        assert!(out.contains("pub color: String,"), "radio without options should be String: {}", out);
    }

    #[test]
    fn rust_select_has_many() {
        let col = make_col("items", vec![
            FieldDefinition {
                name: "tags".to_string(),
                field_type: FieldType::Select,
                has_many: true,
                required: true,
                ..Default::default()
            },
            FieldDefinition {
                name: "sizes".to_string(),
                field_type: FieldType::Radio,
                has_many: true,
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("pub tags: Vec<String>,"), "required select has-many should be Vec<String>: {}", out);
        assert!(out.contains("Option<Vec<String>>"), "optional radio has-many should be Option<Vec<String>>: {}", out);
    }

    #[test]
    fn rust_row_collapsible_tabs_promote_subfields() {
        use crate::core::field::FieldTab;
        let col = make_col("items", vec![
            FieldDefinition {
                name: "layout_row".to_string(),
                field_type: FieldType::Row,
                fields: vec![text_field("first_name", true), text_field("last_name", false)],
                ..Default::default()
            },
            FieldDefinition {
                name: "details".to_string(),
                field_type: FieldType::Collapsible,
                fields: vec![text_field("bio", false)],
                ..Default::default()
            },
            FieldDefinition {
                name: "sections".to_string(),
                field_type: FieldType::Tabs,
                tabs: vec![FieldTab {
                    label: "Tab1".to_string(),
                    description: None,
                    fields: vec![text_field("tab_field", true)],
                }],
                ..Default::default()
            },
        ]);
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Row sub-fields promoted — layout_row should not appear as a field
        assert!(!out.contains("layout_row"), "row field name should not appear as a struct field: {}", out);
        assert!(out.contains("pub first_name: String,"), "row required sub-field promoted: {}", out);
        assert!(out.contains("pub last_name: Option<String>,"), "row optional sub-field promoted: {}", out);
        // Collapsible sub-fields promoted
        assert!(!out.contains("details"), "collapsible field name should not appear: {}", out);
        assert!(out.contains("pub bio: Option<String>,"), "collapsible sub-field promoted: {}", out);
        // Tabs sub-fields promoted
        assert!(!out.contains("sections"), "tabs field name should not appear: {}", out);
        assert!(out.contains("pub tab_field: String,"), "tabs sub-field promoted: {}", out);
    }
}
