//! TypeScript type definition generator — interfaces for gRPC client wrappers.

use std::slice::from_ref;

use crate::core::{
    CollectionDefinition, FieldDefinition, FieldType, Registry, collection::GlobalDefinition,
    flatten_array_sub_fields,
};

use super::helpers::{
    collect_sub_type_fields, is_optional, rel_has_many, sorted_collection_slugs,
    sorted_global_slugs, to_pascal_case, w,
};

/// Render all TypeScript type definitions.
pub(super) fn render(registry: &Registry) -> String {
    let mut out = String::from("// Auto-generated by crap-cms. Do not edit.\n\n");

    for slug in sorted_collection_slugs(registry) {
        let col = &registry.collections[slug];
        render_collection(&mut out, col);
    }

    for slug in sorted_global_slugs(registry) {
        let global = &registry.globals[slug];
        render_global(&mut out, global);
    }

    render_collection_slug_type(&mut out, registry);

    out
}

/// Render type definitions for a single collection.
fn render_collection(out: &mut String, col: &CollectionDefinition) {
    let pascal = to_pascal_case(&col.slug);

    // Sub-types (Array rows and Group shapes)
    for stf in collect_sub_type_fields(&col.fields, &pascal) {
        let sub_pascal = format!("{}{}", stf.parent_pascal, to_pascal_case(&stf.field.name));
        w!(out, "export interface {} {{", sub_pascal);
        for sf in &stf.field.fields {
            write_field(out, sf, &sub_pascal);
        }
        w!(out, "}}\n");
    }

    // Input data interface
    w!(out, "/** Input data for creating/updating a {} */", pascal);
    w!(out, "export interface {}Data {{", pascal);
    for f in &col.fields {
        write_field(out, f, &pascal);
    }
    w!(out, "}}\n");

    // Document interface (extends data with id + timestamps)
    w!(out, "/** {} document returned from the API */", pascal);
    w!(
        out,
        "export interface {}Document extends {}Data {{",
        pascal,
        pascal
    );
    w!(out, "  id: string;");

    if col.timestamps {
        w!(out, "  created_at?: string;");
        w!(out, "  updated_at?: string;");
    }
    w!(out, "}}\n");
}

/// Render type definitions for a single global.
fn render_global(out: &mut String, global: &GlobalDefinition) {
    let pascal = to_pascal_case(&global.slug);

    // Sub-types (Array rows and Group shapes)
    for stf in collect_sub_type_fields(&global.fields, &pascal) {
        let sub_pascal = format!("{}{}", stf.parent_pascal, to_pascal_case(&stf.field.name));
        w!(out, "export interface {} {{", sub_pascal);
        for sf in &stf.field.fields {
            write_field(out, sf, &sub_pascal);
        }
        w!(out, "}}\n");
    }

    w!(out, "/** Input data for {} global */", pascal);
    w!(out, "export interface {}Data {{", pascal);
    for f in &global.fields {
        write_field(out, f, &pascal);
    }
    w!(out, "}}\n");

    w!(out, "/** {} global document */", pascal);
    w!(
        out,
        "export interface {}Document extends {}Data {{",
        pascal,
        pascal
    );
    w!(out, "  id: string;");
    w!(out, "  created_at?: string;");
    w!(out, "  updated_at?: string;");
    w!(out, "}}\n");
}

/// Render the `CollectionSlug` union type.
fn render_collection_slug_type(out: &mut String, registry: &Registry) {
    let slugs = sorted_collection_slugs(registry);

    if slugs.is_empty() {
        return;
    }
    let union = slugs
        .iter()
        .map(|s| format!("\"{s}\""))
        .collect::<Vec<_>>()
        .join(" | ");
    w!(out, "/** All collection slugs */");
    w!(out, "export type CollectionSlug = {};", union);
}

/// Write a `JSDoc` comment for polymorphic relationship fields.
fn write_polymorphic_comment(out: &mut String, field: &FieldDefinition, indent: &str) {
    if field.field_type == FieldType::Relationship
        && let Some(rc) = &field.relationship
        && rc.is_polymorphic()
    {
        let targets = rc.all_collections().join(", ");
        w!(
            out,
            "{}/** Polymorphic relationship — targets: {} */",
            indent,
            targets
        );
    }
}

/// Write a single field's type definition.
fn write_field(out: &mut String, field: &FieldDefinition, parent_pascal: &str) {
    // Layout wrappers are transparent — emit their sub-fields at this level.
    // The canonical wrapper-flatten (`flatten_array_sub_fields`) owns the
    // promotion rules.
    if field.field_type.is_layout_wrapper() {
        for sub in flatten_array_sub_fields(from_ref(field)) {
            write_field(out, sub, parent_pascal);
        }
        return;
    }
    write_polymorphic_comment(out, field, "  ");
    let ts_type = field_to_ts(field, parent_pascal);
    let opt = if is_optional(field) { "?" } else { "" };
    w!(out, "  {}{}: {};", field.name, opt, ts_type);
}

/// Map a field definition to its TypeScript type string.
fn field_to_ts(field: &FieldDefinition, parent_pascal: &str) -> String {
    match &field.field_type {
        FieldType::Text => {
            if field.has_many {
                "string[]".to_string()
            } else {
                "string".to_string()
            }
        }
        FieldType::Textarea
        | FieldType::Email
        | FieldType::Date
        | FieldType::Richtext
        | FieldType::Code => "string".to_string(),
        FieldType::Number => {
            if field.has_many {
                "number[]".to_string()
            } else {
                "number".to_string()
            }
        }
        FieldType::Checkbox => "boolean".to_string(),
        FieldType::Json => "unknown".to_string(),
        FieldType::Select | FieldType::Radio => {
            let base = if field.options.is_empty() {
                "string".to_string()
            } else {
                field
                    .options
                    .iter()
                    .map(|o| format!("\"{}\"", o.value))
                    .collect::<Vec<_>>()
                    .join(" | ")
            };

            if field.has_many {
                if field.options.is_empty() {
                    "string[]".to_string()
                } else {
                    format!("({base})[]")
                }
            } else {
                base
            }
        }
        FieldType::Relationship => match &field.relationship {
            Some(rc) if rc.is_polymorphic() && rc.has_many => "string[]".to_string(),
            Some(rc) if rc.is_polymorphic() => "string".to_string(),
            Some(rc) if rc.has_many => "string[]".to_string(),
            _ => "string".to_string(),
        },
        FieldType::Array => {
            if field.fields.is_empty() {
                "Record<string, unknown>[]".to_string()
            } else {
                format!("{}{}[]", parent_pascal, to_pascal_case(&field.name))
            }
        }
        FieldType::Group => {
            if field.fields.is_empty() {
                "Record<string, unknown>".to_string()
            } else {
                format!("{}{}", parent_pascal, to_pascal_case(&field.name))
            }
        }
        // Layout-only; sub-fields are promoted
        FieldType::Row | FieldType::Collapsible | FieldType::Tabs => {
            "Record<string, unknown>".to_string()
        }
        FieldType::Upload => {
            if rel_has_many(field) {
                "string[]".to_string()
            } else {
                "string".to_string()
            }
        }
        FieldType::Blocks | FieldType::Join => "Record<string, unknown>[]".to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::core::FieldTab;
    use crate::core::{BlockDefinition, LocalizedString, RelationshipConfig, SelectOption};
    fn text_field(name: &str, required: bool) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Text)
            .required(required)
            .build()
    }

    fn select_field(name: &str, opts: &[&str]) -> FieldDefinition {
        FieldDefinition::builder(name, FieldType::Select)
            .required(true)
            .options(
                opts.iter()
                    .map(|v| SelectOption::new(LocalizedString::Plain(v.to_string()), *v))
                    .collect(),
            )
            .build()
    }

    fn make_col(slug: &str, fields: Vec<FieldDefinition>) -> CollectionDefinition {
        let mut def = CollectionDefinition::new(slug);
        def.timestamps = true;
        def.fields = fields;
        def
    }

    #[test]
    fn typescript_collection_output() {
        let col = make_col(
            "posts",
            vec![
                text_field("title", true),
                text_field("content", false),
                select_field("status", &["draft", "published"]),
            ],
        );

        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(out.contains("export interface PostsData {"));
        assert!(out.contains("  title: string;"));
        assert!(out.contains("  content?: string;"));
        assert!(out.contains("  status: \"draft\" | \"published\";"));
        assert!(out.contains("export interface PostsDocument extends PostsData {"));
        assert!(out.contains("  id: string;"));
        assert!(out.contains("  created_at?: string;"));
        assert!(out.contains("  updated_at?: string;"));
    }

    #[test]
    fn typescript_global_output() {
        let mut global = GlobalDefinition::new("site_settings");
        global.fields = vec![text_field("site_name", true)];

        let mut out = String::new();
        render_global(&mut out, &global);

        assert!(out.contains("export interface SiteSettingsData {"));
        assert!(out.contains("export interface SiteSettingsDocument extends SiteSettingsData {"));
    }

    #[test]
    fn typescript_relationship_has_many() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("tags", FieldType::Relationship)
                    .relationship(RelationshipConfig::new("tags", true))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("tags?: string[];"));
    }

    #[test]
    fn typescript_polymorphic_has_one() {
        let mut rc = RelationshipConfig::new("posts", false);
        rc.polymorphic = vec!["posts".into(), "pages".into()];
        let col = make_col(
            "comments",
            vec![
                FieldDefinition::builder("subject", FieldType::Relationship)
                    .required(true)
                    .relationship(rc)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Polymorphic has-one = string (stores "collection/id" composite)
        assert!(
            out.contains("  subject: string;"),
            "polymorphic has-one should be string: {out}"
        );
        // Comment listing target collections
        assert!(
            out.contains("Polymorphic relationship"),
            "should have polymorphic comment: {out}"
        );
        assert!(
            out.contains("posts"),
            "comment should list target collections: {out}"
        );
        assert!(
            out.contains("pages"),
            "comment should list target collections: {out}"
        );
    }

    #[test]
    fn typescript_polymorphic_has_many() {
        let mut rc = RelationshipConfig::new("articles", true);
        rc.polymorphic = vec!["articles".into(), "videos".into()];
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("related", FieldType::Relationship)
                    .has_many(true)
                    .relationship(rc)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Polymorphic has-many = string[] (array of "collection/id" composites)
        assert!(
            out.contains("string[]"),
            "polymorphic has-many should be string[]: {out}"
        );
        assert!(
            out.contains("Polymorphic relationship"),
            "should have polymorphic comment: {out}"
        );
        assert!(
            out.contains("articles"),
            "comment should list target collections: {out}"
        );
        assert!(
            out.contains("videos"),
            "comment should list target collections: {out}"
        );
    }

    #[test]
    fn typescript_relationship_has_one() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("author", FieldType::Relationship)
                    .required(true)
                    .relationship(RelationshipConfig::new("users", false))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  author: string;"));
    }

    #[test]
    fn typescript_number_checkbox_json_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("price", FieldType::Number)
                    .required(true)
                    .build(),
                FieldDefinition::builder("active", FieldType::Checkbox).build(),
                FieldDefinition::builder("meta", FieldType::Json).build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  price: number;"));
        assert!(out.contains("  active?: boolean;"));
        assert!(out.contains("  meta?: unknown;"));
    }

    #[test]
    fn typescript_array_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![text_field("label", true), text_field("value", false)])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("export interface PostsItems {"));
        assert!(out.contains("  label: string;"));
        assert!(out.contains("  value?: string;"));
        assert!(out.contains("PostsItems[]"));
    }

    #[test]
    fn typescript_nested_group_in_array_uses_compound_pascal() {
        // Regression: a Group nested inside an array row must be declared and
        // referenced with the *compound* parent path (PostsItemsMeta), not the
        // collection pascal (PostsMeta) — otherwise the reference dangles.
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("items", FieldType::Array)
                    .fields(vec![
                        FieldDefinition::builder("meta", FieldType::Group)
                            .fields(vec![text_field("title", true)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);

        assert!(
            out.contains("export interface PostsItemsMeta {"),
            "nested group sub-type must use compound pascal: {out}"
        );
        assert!(
            out.contains("PostsItemsMeta;"),
            "the PostsItems body must reference PostsItemsMeta: {out}"
        );
        assert!(
            !out.contains("PostsMeta"),
            "must not emit the wrong collection-pascal name: {out}"
        );
    }

    #[test]
    fn typescript_array_without_subfields() {
        let col = make_col(
            "posts",
            vec![FieldDefinition::builder("data", FieldType::Array).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Record<string, unknown>[]"));
    }

    #[test]
    fn typescript_group_field_empty() {
        let col = make_col(
            "items",
            vec![FieldDefinition::builder("seo", FieldType::Group).build()],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Record<string, unknown>"));
    }

    #[test]
    fn typescript_group_field_with_subfields() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("seo", FieldType::Group)
                    .fields(vec![
                        text_field("title", true),
                        text_field("description", false),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("export interface PostsSeo {"),
            "group sub-type interface should be emitted: {out}"
        );
        assert!(out.contains("  title: string;"), "group sub-field: {out}");
        assert!(
            out.contains("  description?: string;"),
            "group optional sub-field: {out}"
        );
        assert!(
            out.contains("PostsSeo"),
            "parent should reference group sub-type: {out}"
        );
    }

    #[test]
    fn typescript_blocks_field() {
        let mut bd = BlockDefinition::new("text", vec![text_field("body", true)]);
        bd.label = Some(LocalizedString::Plain("Text".to_string()));
        let col = make_col(
            "pages",
            vec![
                FieldDefinition::builder("content", FieldType::Blocks)
                    .blocks(vec![bd])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("Record<string, unknown>[]"));
    }

    #[test]
    fn typescript_upload_field() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("image", FieldType::Upload)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  image: string;"));
    }

    #[test]
    fn upload_has_many_generates_array_type() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("images", FieldType::Upload)
                    .required(true)
                    .relationship(RelationshipConfig::new("", true))
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("  images: string[];"),
            "has-many upload should be string[]: {out}"
        );
    }

    #[test]
    fn typescript_select_without_options() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("category", FieldType::Select)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  category: string;"));
    }

    #[test]
    fn typescript_collection_slug_type() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        registry.register_collection(make_col("pages", vec![text_field("body", true)]));
        let out = render(&registry);
        assert!(out.contains("export type CollectionSlug = \"pages\" | \"posts\";"));
    }

    #[test]
    fn typescript_collection_slug_type_empty() {
        let registry = Registry::new();
        let out = render(&registry);
        assert!(!out.contains("CollectionSlug"));
    }

    #[test]
    fn typescript_no_timestamps() {
        let mut col = make_col("tags", vec![text_field("name", true)]);
        col.timestamps = false;
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(!out.contains("created_at"));
        assert!(!out.contains("updated_at"));
    }

    #[test]
    fn typescript_text_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("tags", FieldType::Text)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("labels", FieldType::Text)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("  tags: string[];"),
            "required has-many text should be string[]: {out}"
        );
        assert!(
            out.contains("  labels?: string[];"),
            "optional has-many text should be string[]?: {out}"
        );
    }

    #[test]
    fn typescript_number_has_many() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("scores", FieldType::Number)
                    .has_many(true)
                    .required(true)
                    .build(),
                FieldDefinition::builder("weights", FieldType::Number)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("  scores: number[];"),
            "required has-many number should be number[]: {out}"
        );
        assert!(
            out.contains("  weights?: number[];"),
            "optional has-many number should be number[]?: {out}"
        );
    }

    #[test]
    fn typescript_email_date_richtext_textarea() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("contact", FieldType::Email)
                    .required(true)
                    .build(),
                FieldDefinition::builder("at", FieldType::Date)
                    .required(true)
                    .build(),
                FieldDefinition::builder("body", FieldType::Richtext)
                    .required(true)
                    .build(),
                FieldDefinition::builder("notes", FieldType::Textarea)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(out.contains("  contact: string;"));
        assert!(out.contains("  at: string;"));
        assert!(out.contains("  body: string;"));
        assert!(out.contains("  notes: string;"));
    }

    #[test]
    fn typescript_code_join_radio_fields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("snippet", FieldType::Code)
                    .required(true)
                    .build(),
                FieldDefinition::builder("refs", FieldType::Join).build(),
                FieldDefinition::builder("color", FieldType::Radio)
                    .required(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("  snippet: string;"),
            "code field should map to string: {out}"
        );
        assert!(
            out.contains("  refs?: Record<string, unknown>[];"),
            "join field should map to Record[]: {out}"
        );
        assert!(
            out.contains("  color: string;"),
            "radio without options should be string: {out}"
        );
    }

    #[test]
    fn typescript_select_has_many_with_options() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("tags", FieldType::Select)
                    .has_many(true)
                    .required(true)
                    .options(vec![
                        SelectOption::new(LocalizedString::Plain("A".into()), "a"),
                        SelectOption::new(LocalizedString::Plain("B".into()), "b"),
                    ])
                    .build(),
                FieldDefinition::builder("cats", FieldType::Select)
                    .has_many(true)
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // has_many with options → (opt1 | opt2)[]
        assert!(
            out.contains("(\"a\" | \"b\")[]"),
            "select has-many with options should be union array: {out}"
        );
        // has_many without options → string[]
        assert!(
            out.contains("string[]"),
            "select has-many without options should be string[]: {out}"
        );
    }

    #[test]
    fn typescript_radio_has_many_with_options() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("sizes", FieldType::Radio)
                    .has_many(true)
                    .required(true)
                    .options(vec![
                        SelectOption::new(LocalizedString::Plain("S".into()), "s"),
                        SelectOption::new(LocalizedString::Plain("L".into()), "l"),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("(\"s\" | \"l\")[]"),
            "radio has-many with options should be union array: {out}"
        );
    }

    #[test]
    fn typescript_row_collapsible_tabs_promote_subfields() {
        let col = make_col(
            "items",
            vec![
                FieldDefinition::builder("layout_row", FieldType::Row)
                    .fields(vec![
                        text_field("first_name", true),
                        text_field("last_name", false),
                    ])
                    .build(),
                FieldDefinition::builder("details", FieldType::Collapsible)
                    .fields(vec![text_field("bio", false)])
                    .build(),
                FieldDefinition::builder("sections", FieldType::Tabs)
                    .tabs(vec![FieldTab::new(
                        "Tab1",
                        vec![text_field("tab_field", true)],
                    )])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        // Row sub-fields promoted to parent — no "layout_row" key
        assert!(
            !out.contains("layout_row:"),
            "row field name should not appear as a key: {out}"
        );
        assert!(
            out.contains("  first_name: string;"),
            "row sub-field should be promoted: {out}"
        );
        assert!(
            out.contains("  last_name?: string;"),
            "row optional sub-field should be promoted: {out}"
        );
        // Collapsible sub-fields promoted
        assert!(
            !out.contains("details:"),
            "collapsible field name should not appear as a key: {out}"
        );
        assert!(
            out.contains("  bio?: string;"),
            "collapsible sub-field should be promoted: {out}"
        );
        // Tabs sub-fields promoted
        assert!(
            !out.contains("sections:"),
            "tabs field name should not appear as a key: {out}"
        );
        assert!(
            out.contains("  tab_field: string;"),
            "tabs sub-field should be promoted: {out}"
        );
    }

    #[test]
    fn typescript_array_nested_in_row() {
        let col = make_col(
            "posts",
            vec![
                FieldDefinition::builder("layout", FieldType::Row)
                    .fields(vec![
                        FieldDefinition::builder("items", FieldType::Array)
                            .fields(vec![text_field("label", true)])
                            .build(),
                    ])
                    .build(),
            ],
        );
        let mut out = String::new();
        render_collection(&mut out, &col);
        assert!(
            out.contains("export interface PostsItems {"),
            "array nested in Row should emit sub-type: {out}"
        );
        assert!(
            out.contains("PostsItems[]"),
            "field should reference sub-type: {out}"
        );
    }

    #[test]
    fn typescript_global_with_subtypes() {
        let mut global = GlobalDefinition::new("settings");
        global.fields = vec![
            FieldDefinition::builder("nav", FieldType::Array)
                .fields(vec![text_field("label", true), text_field("url", true)])
                .build(),
            FieldDefinition::builder("seo", FieldType::Group)
                .fields(vec![text_field("title", true)])
                .build(),
        ];
        let mut out = String::new();
        render_global(&mut out, &global);
        assert!(
            out.contains("export interface SettingsNav {"),
            "global array sub-type should be emitted: {out}"
        );
        assert!(
            out.contains("export interface SettingsSeo {"),
            "global group sub-type should be emitted: {out}"
        );
    }

    #[test]
    fn typescript_full_render_with_globals() {
        let mut registry = Registry::new();
        registry.register_collection(make_col("posts", vec![text_field("title", true)]));
        let mut settings = GlobalDefinition::new("settings");
        settings.fields = vec![text_field("name", true)];
        registry.register_global(settings);
        let out = render(&registry);
        assert!(out.contains("Auto-generated"));
        assert!(out.contains("export interface PostsData {"));
        assert!(out.contains("export interface SettingsData {"));
        assert!(out.contains("export interface SettingsDocument extends SettingsData {"));
        assert!(out.contains("export type CollectionSlug = \"posts\";"));
    }
}
